In [1]:
import pandas as pd

# Célula 1: Ler o ficheiro
df = pd.read_csv(r'C:\Users\LISARR\Documents\python\00.Metadados\CP7COORDS.CSV', sep=';')
df.head()

    CP4  CP3            POINT_X           POINT_Y
0  1000    1  -9,13868674899993  38,7330982610001
1  1000    2  -9,13936248099998      38,733887425
2  1000    3  -9,13994047099993       38,73459504
3  1000    4  -9,13864372599994  38,7331130320001
4  1000    5  -9,13953588199996  38,7341647800001

In [2]:
# Célula 2: Criar a coluna CP com formatting condicional (SEM "CP ")
df['CP'] = df['CP4'].astype(str) + '-' + df['CP3'].astype(str).str.zfill(3)
df[['CP', 'POINT_X', 'POINT_Y']].head()

         CP            POINT_X           POINT_Y
0  1000-001  -9,13868674899993  38,7330982610001
1  1000-002  -9,13936248099998      38,733887425
2  1000-003  -9,13994047099993       38,73459504
3  1000-004  -9,13864372599994  38,7331130320001
4  1000-005  -9,13953588199996  38,7341647800001

In [3]:
# Célula 3: Ver resultado final
df[['CP', 'POINT_X', 'POINT_Y']].head()

         CP            POINT_X           POINT_Y
0  1000-001  -9,13868674899993  38,7330982610001
1  1000-002  -9,13936248099998      38,733887425
2  1000-003  -9,13994047099993       38,73459504
3  1000-004  -9,13864372599994  38,7331130320001
4  1000-005  -9,13953588199996  38,7341647800001

In [4]:
# Célula 1: Conectar à base de dados
import sqlite3
DB_PATH = r"C:\Users\LISARR\Documents\python\00.DB\2026.db"
con = sqlite3.connect(DB_PATH)
print("✓ Conectado à base de dados")

✓ Conectado à base de dados

In [5]:
# Célula 2: Criar tabela
cursor = con.cursor()

cursor.execute('''
    CREATE TABLE IF NOT EXISTS coordenadas (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        cp TEXT NOT NULL,
        point_x REAL,
        point_y REAL
    )
''')

con.commit()
print("✓ Tabela 'coordenadas' criada")

✓ Tabela 'coordenadas' criada

In [6]:
# Célula 3c: Selecionar e renomear colunas
df_inserir = df[['CP', 'POINT_X', 'POINT_Y']].copy()
df_inserir.columns = ['cp', 'point_x', 'point_y']
df_inserir.head()

         cp            point_x           point_y
0  1000-001  -9,13868674899993  38,7330982610001
1  1000-002  -9,13936248099998      38,733887425
2  1000-003  -9,13994047099993       38,73459504
3  1000-004  -9,13864372599994  38,7331130320001
4  1000-005  -9,13953588199996  38,7341647800001

In [7]:
# Célula 3d: Inserir dados na BD
df_inserir.to_sql('coordenadas', con, if_exists='append', index=False)
con.commit()

print(f"✓ {len(df_inserir)} registos inseridos")

✓ 178409 registos inseridos