In [1]:
import sqlite3
import pandas as pd
import platform
import warnings
warnings.filterwarnings('ignore')

# Detecção do SO e caminho BD
if platform.system() == 'Windows':
    DB_PATH = r"C:\Users\LISARR\Documents\python\01.Financeiro\inform_27.db"
elif platform.system() == 'Darwin':
    DB_PATH = "/Volumes/RR/DB/inform_27.db"
else:
    DB_PATH = "inform_27.db"

# Conectar
con = sqlite3.connect(DB_PATH)
cursor = con.cursor()

In [2]:
df = pd.read_sql_query("SELECT * FROM inform_27_2026", con)
con.close()

In [3]:
print(f"Shape: {df.shape}")
print(f"\nColunas: {df.shape[1]}")
df.head()

Shape: (108219, 58)

Colunas: 58

,id,PROPIETARIO,TRAYECTO,TRANSPORTISTA,TRACTORA,REMOLQUE,INGRESODT,COSTEDT,RENTADT,PALETSDT,...,LOCDES,LUGARDESCARGA,TEMP_MERC_PED,TIPOPALETA,CAMION_TIPO,CAMION_CAPACIDAD,TIPO_COMBUSTIBLE,KMREALES,ALBARAN,ficheiro_origem
0,1,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,SOLIDO CLICK LDA,0000XXX,0000XXX,10.69,4.64,6.05,0.49,...,573897,"PLAT. COOPLECNORTE,S.A.",RFGRFG,EUR,Trailer 33 plts,33,DIESEL,194.134,NO,SAL_DAT027 (11).xls
1,2,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,SOLIDO CLICK LDA,0000XXX,0000XXX,125.04,236.86,-111.82,25,...,573897,"PLAT. COOPLECNORTE,S.A.",RFGRFG,EUR,Trailer 33 plts,33,DIESEL,194.134,NO,SAL_DAT027 (11).xls
2,3,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,0000XXX,0,12.02,-12.02,0.8,...,298515,DL Transportes Fernando Simões Monteiro Unip. Lda,RFGRFG,EUR,Trailer 33 plts,33,DIESEL,151.803,NO,SAL_DAT027 (11).xls
3,4,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,0000XXX,0,10.82,-10.82,0.72,...,298515,DL Transportes Fernando Simões Monteiro Unip. Lda,RFGRFG,EUR,Trailer 33 plts,33,DIESEL,151.803,NO,SAL_DAT027 (11).xls
4,5,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,0000XXX,0,6.01,-6.01,0.4,...,298515,DL Transportes Fernando Simões Monteiro Unip. Lda,RFGRFG,EUR,Trailer 33 plts,33,DIESEL,151.803,NO,SAL_DAT027 (11).xls

In [4]:
# Converter tipos de dados numéricos
df['INGRESODT'] = pd.to_numeric(df['INGRESODT'], errors='coerce')
df['COSTEDT'] = pd.to_numeric(df['COSTEDT'], errors='coerce')
df['RENTADT'] = pd.to_numeric(df['RENTADT'], errors='coerce')
df['PALETSDT'] = pd.to_numeric(df['PALETSDT'], errors='coerce')
df['PESO_BRUTO'] = pd.to_numeric(df['PESO_BRUTO'], errors='coerce')
df['PALETS'] = pd.to_numeric(df['PALETS'], errors='coerce')
df['KM'] = pd.to_numeric(df['KM'], errors='coerce')
df['KMREALES'] = pd.to_numeric(df['KMREALES'], errors='coerce')

# CODEUT como string
df['CODEUT'] = df['CODEUT'].astype(str)

# Trim em strings (ANTES de converter as datas)
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

# Datas como datetime (sem hora, prontas para PBI) - DEPOIS do trim
df['FCARGA'] = pd.to_datetime(df['FCARGA'], format='%Y%m%d', errors='coerce').dt.date
df['FENTREGA'] = pd.to_datetime(df['FENTREGA'], format='%Y%m%d', errors='coerce').dt.date

In [5]:
print(f"Shape: {df.shape}")
print(f"\nTipos de dados:")
print(df.dtypes)
print(f"\nNulos por coluna:")
print(df.isnull().sum())
df.head()

Shape: (108219, 58)

Tipos de dados:
id                    int64
PROPIETARIO             str
TRAYECTO                str
TRANSPORTISTA           str
TRACTORA                str
REMOLQUE                str
INGRESODT           float64
COSTEDT             float64
RENTADT             float64
PALETSDT            float64
PESO_BRUTO          float64
CODEUT                  str
ESTADO_UT               str
RANGO_UT                str
FCARGA               object
ACTIVIDAD               str
CODEDT                  str
ESTADO_DT               str
REFERENCIA              str
CODACT                  str
LOCORIGEN               str
PROV_ORIGEN             str
PAISORIGEN              str
CPOSTAL                 str
LOCDESTINO              str
PROV_DESTINO            str
PAISDESTINO             str
CPOSTAD                 str
KM                  float64
FENTREGA             object
ORIGEN                  str
ENTREGAR                str
PROV_ENTREGAR           str
PAISENTREGAR            str
DESTINO                 str
PALETS              float64
PREFAC                  str
RUTA                    str
COBROREAL               str
GESTION                 str
DEPART                  str
USCODE                  str
USUARIO                 str
TIPOCLIENTE             str
TIPOFLUJO               str
WMSCODRGT               str
LOCCAR                  str
LUGARCARGA              str
LOCDES                  str
LUGARDESCARGA           str
TEMP_MERC_PED           str
TIPOPALETA              str
CAMION_TIPO             str
CAMION_CAPACIDAD        str
TIPO_COMBUSTIBLE        str
KMREALES            float64
ALBARAN                 str
ficheiro_origem         str
dtype: object

Nulos por coluna:
id                       0
PROPIETARIO              0
TRAYECTO              5952
TRANSPORTISTA            0
TRACTORA              2260
REMOLQUE                 0
INGRESODT                0
COSTEDT                  0
RENTADT                  0
PALETSDT                 0
PESO_BRUTO               0
CODEUT                   0
ESTADO_UT                0
RANGO_UT                 0
FCARGA                   0
ACTIVIDAD                0
CODEDT                   0
ESTADO_DT                0
REFERENCIA               0
CODACT                   0
LOCORIGEN                6
PROV_ORIGEN              6
PAISORIGEN               0
CPOSTAL                  0
LOCDESTINO           15256
PROV_DESTINO         15280
PAISDESTINO             20
CPOSTAD                 20
KM                  108101
FENTREGA                 0
ORIGEN               11198
ENTREGAR                24
PROV_ENTREGAR        15432
PAISENTREGAR            24
DESTINO              12529
PALETS                   0
PREFAC                   0
RUTA                     0
COBROREAL                0
GESTION                  6
DEPART                   6
USCODE                   0
USUARIO                  0
TIPOCLIENTE          70433
TIPOFLUJO                0
WMSCODRGT            10606
LOCCAR                   0
LUGARCARGA               0
LOCDES                  20
LUGARDESCARGA           20
TEMP_MERC_PED            0
TIPOPALETA               0
CAMION_TIPO              1
CAMION_CAPACIDAD         0
TIPO_COMBUSTIBLE         0
KMREALES                 0
ALBARAN                  0
ficheiro_origem          0
dtype: int64

,id,PROPIETARIO,TRAYECTO,TRANSPORTISTA,TRACTORA,REMOLQUE,INGRESODT,COSTEDT,RENTADT,PALETSDT,...,LOCDES,LUGARDESCARGA,TEMP_MERC_PED,TIPOPALETA,CAMION_TIPO,CAMION_CAPACIDAD,TIPO_COMBUSTIBLE,KMREALES,ALBARAN,ficheiro_origem
0,1,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,SOLIDO CLICK LDA,0000XXX,0000XXX,10.69,4.64,6.05,0.49,...,573897,"PLAT. COOPLECNORTE,S.A.",RFGRFG,EUR,Trailer 33 plts,33,DIESEL,194.134,NO,SAL_DAT027 (11).xls
1,2,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,SOLIDO CLICK LDA,0000XXX,0000XXX,125.04,236.86,-111.82,25.00,...,573897,"PLAT. COOPLECNORTE,S.A.",RFGRFG,EUR,Trailer 33 plts,33,DIESEL,194.134,NO,SAL_DAT027 (11).xls
2,3,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,0000XXX,0.00,12.02,-12.02,0.80,...,298515,DL Transportes Fernando Simões Monteiro Unip. Lda,RFGRFG,EUR,Trailer 33 plts,33,DIESEL,151.803,NO,SAL_DAT027 (11).xls
3,4,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,0000XXX,0.00,10.82,-10.82,0.72,...,298515,DL Transportes Fernando Simões Monteiro Unip. Lda,RFGRFG,EUR,Trailer 33 plts,33,DIESEL,151.803,NO,SAL_DAT027 (11).xls
4,5,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,0000XXX,0.00,6.01,-6.01,0.40,...,298515,DL Transportes Fernando Simões Monteiro Unip. Lda,RFGRFG,EUR,Trailer 33 plts,33,DIESEL,151.803,NO,SAL_DAT027 (11).xls

In [6]:
# Caminho do ficheiro
caminho = r"C:\Users\LISARR\Documents\python\01.Financeiro\Danone_Custos_V2.xlsx"

# Ler sheet "Ingreso y coste" colunas 0-4 (A-E) a partir da linha 2
df_danone = pd.read_excel(
    caminho,
    sheet_name="Ingreso y coste",
    usecols=range(5),
    skiprows=1,
    header=None
)

# Renomear colunas
df_danone.columns = ['A', 'B', 'C', 'D', 'E']

print(f"Shape: {df_danone.shape}")
df_danone.head()

Shape: (16499, 5)

          A                                                  B    C    D    E
0       NaN                                                NaN  NaN  NaN  NaN
1       NaN                                                NaN  NaN  NaN  NaN
2   DESTINO  ALDI ENTREPOSTO LOG MOITA / Danone Portugal (011)  NaN  NaN  NaN
3  FENTREGA                                   (Multiple Items)  NaN  NaN  NaN
4       NaN                                                NaN  NaN  NaN  NaN

In [7]:
# Preparar df_danone (renomear colunas)
df_danone.columns = ['CODEDT', 'REFERENCIA', 'CODEUT', 'COSTEDT_DANONE', 'Ingreso']

# Remover primeira linha se for header
if df_danone.iloc[0, 0] == 'CODEDT':
    df_danone = df_danone.iloc[1:].reset_index(drop=True)

# Converter tipos de dados
df_danone['CODEDT'] = pd.to_numeric(df_danone['CODEDT'], errors='coerce').fillna(0).astype('Int64')
df_danone['CODEUT'] = df_danone['CODEUT'].astype(str).str.strip()
df_danone['REFERENCIA'] = df_danone['REFERENCIA'].astype(str).str.strip()
df_danone['Ingreso'] = pd.to_numeric(df_danone['Ingreso'], errors='coerce')

# Limpeza de espaços no df
df['REFERENCIA'] = df['REFERENCIA'].astype(str).str.strip()
df['CODEUT'] = df['CODEUT'].astype(str).str.strip()
df['CODEDT'] = pd.to_numeric(df['CODEDT'], errors='coerce').fillna(0).astype('Int64')

# Função de lookup com cascata - SEM CRITÉRIOS DE FILTRO
def buscar_ingreso_danone(row):
    codeut = str(row['CODEUT']).strip()
    referencia = str(row['REFERENCIA']).strip()
    codedt = int(row['CODEDT']) if pd.notna(row['CODEDT']) else None
    
    # Tentativa 1: CODEUT + REFERENCIA
    match1 = df_danone[(df_danone['CODEUT'] == codeut) & (df_danone['REFERENCIA'] == referencia)]
    if not match1.empty:
        return match1['Ingreso'].iloc[0]
    
    # Tentativa 2: CODEUT + CODEDT
    if codedt is not None:
        match2 = df_danone[(df_danone['CODEUT'] == codeut) & (df_danone['CODEDT'] == codedt)]
        if not match2.empty:
            return match2['Ingreso'].iloc[0]
    
    return None

# Aplicar função
df['ingresso_danone'] = df.apply(buscar_ingreso_danone, axis=1)

# Estatísticas
total_linhas = len(df)
matches = df['ingresso_danone'].notna().sum()
sum_ingresso_danone = df['ingresso_danone'].sum()
sum_ingreso_excel = df_danone['Ingreso'].sum()

print(f"Total de linhas df: {total_linhas}")
print(f"Matches encontrados: {matches}")
print(f"Taxa sucesso: {(matches/total_linhas*100):.2f}%")
print(f"\nSum ingresso_danone: {sum_ingresso_danone:,.2f}")
print(f"Sum Ingreso Excel: {sum_ingreso_excel:,.2f}")
print(f"Diferença: {(sum_ingreso_excel - sum_ingresso_danone):,.2f}")

df[['CODEDT', 'REFERENCIA', 'CODEUT', 'INGRESODT', 'ingresso_danone']].head(10)

Total de linhas df: 108219
Matches encontrados: 25
Taxa sucesso: 0.02%

Sum ingresso_danone: 1,949.48
Sum Ingreso Excel: 3,898.96
Diferença: 1,949.48

     CODEDT                REFERENCIA   CODEUT  INGRESODT  ingresso_danone
0  25387086  5021705579     413948820  3344051      10.69              NaN
1  25398553  5021695753     413975730  3344051     125.04              NaN
2  25392919  5021718153     413962673  3344052       0.00              NaN
3  25393741  5021741334     413968895  3344052       0.00              NaN
4  25393743  5021740631     413963593  3344052       0.00              NaN
5  25392920  5021718153     413962673  3344163       0.00              NaN
6  25393742  5021741334     413968895  3344163       0.00              NaN
7  25393744  5021740631     413963593  3344163       0.00              NaN
8  25391965  5021762386     413948513  3344178      23.54              NaN
9  25394896  5021760653     413972484  3344178      15.07              NaN

In [8]:
# Validação: Linhas do Excel que têm/não têm match no df

print("="*70)
print("VALIDAÇÃO - LINHAS DO EXCEL (df_danone)")
print("="*70)

# Total de linhas no Excel
total_danone = len(df_danone)
print(f"\nTotal de linhas no Excel: {total_danone}")

# Função para verificar se linha do Excel tem match no df
def tem_match_no_df(row_danone):
    codeut = str(row_danone['CODEUT']).strip()
    referencia = str(row_danone['REFERENCIA']).strip()
    codedt = int(row_danone['CODEDT']) if pd.notna(row_danone['CODEDT']) else None
    
    # Tentativa 1: CODEUT + REFERENCIA
    match1 = df[(df['CODEUT'] == codeut) & (df['REFERENCIA'] == referencia)]
    if not match1.empty:
        return True
    
    # Tentativa 2: CODEUT + CODEDT
    if codedt is not None:
        match2 = df[(df['CODEUT'] == codeut) & (df['CODEDT'] == codedt)]
        if not match2.empty:
            return True
    
    return False

# Aplicar função
df_danone['tem_match'] = df_danone.apply(tem_match_no_df, axis=1)

# Contar
com_match = df_danone['tem_match'].sum()
sem_match = total_danone - com_match

print(f"\nLinhas com match no df: {com_match}")
print(f"Linhas SEM match no df: {sem_match}")
print(f"Taxa cobertura: {(com_match/total_danone*100):.2f}%")

# Somas dos Ingreso
sum_com_match = df_danone[df_danone['tem_match']]['Ingreso'].sum()
sum_sem_match = df_danone[~df_danone['tem_match']]['Ingreso'].sum()

print(f"\nSum Ingreso (com match): {sum_com_match:,.2f}")
print(f"Sum Ingreso (SEM match): {sum_sem_match:,.2f}")
print(f"Total: {(sum_com_match + sum_sem_match):,.2f}")

print("\n" + "="*70)
print("LINHAS DO EXCEL SEM MATCH NO DF (primeiras 20)")
print("="*70)
df_danone[~df_danone['tem_match']][['CODEDT', 'REFERENCIA', 'CODEUT', 'Ingreso']].head(20)

======================================================================
VALIDAÇÃO - LINHAS DO EXCEL (df_danone)
======================================================================

Total de linhas no Excel: 16499

Linhas com match no df: 25
Linhas SEM match no df: 16474
Taxa cobertura: 0.15%

Sum Ingreso (com match): 1,949.48
Sum Ingreso (SEM match): 1,949.48
Total: 3,898.96

======================================================================
LINHAS DO EXCEL SEM MATCH NO DF (primeiras 20)
======================================================================

    CODEDT                                         REFERENCIA  CODEUT  Ingreso
0        0                                                NaN     NaN      NaN
1        0                                                NaN     NaN      NaN
2        0  ALDI ENTREPOSTO LOG MOITA / Danone Portugal (011)     NaN      NaN
3        0                                   (Multiple Items)     NaN      NaN
4        0                                                NaN     NaN      NaN
5        0                                         REFERENCIA  CODEUT      NaN
31       0                                                NaN     NaN  1949.48
32       0                                                NaN     NaN      NaN
33       0                                                NaN     NaN      NaN
34       0                                                NaN     NaN      NaN
35       0                                                NaN     NaN      NaN
36       0                                                NaN     NaN      NaN
37       0                                                NaN     NaN      NaN
38       0                                                NaN     NaN      NaN
39       0                                                NaN     NaN      NaN
40       0                                                NaN     NaN      NaN
41       0                                                NaN     NaN      NaN
42       0                                                NaN     NaN      NaN
43       0                                                NaN     NaN      NaN
44       0                                                NaN     NaN      NaN

In [9]:
# Número de DT (linhas) por mês

print("="*70)
print("DISTRIBUIÇÃO DE DT POR MÊS")
print("="*70)

# Extrair mês de FCARGA
df['mes'] = pd.to_datetime(df['FENTREGA']).dt.month
df['mes_nome'] = pd.to_datetime(df['FENTREGA']).dt.strftime('%B')

# Contar por mês
dt_por_mes = df['mes'].value_counts().sort_index()

print("\nNúmero de DT por mês:")
for mes, count in dt_por_mes.items():
    mes_nome = ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'][mes-1]
    pct = (count / len(df) * 100)
    print(f"  {mes_nome}: {count:>6} DT ({pct:>5.2f}%)")

print(f"\nTotal: {len(df)} DT")

======================================================================
DISTRIBUIÇÃO DE DT POR MÊS
======================================================================

Número de DT por mês:
  Jan:  14122 DT (13.05%)
  Fev:  13466 DT (12.44%)
  Mar:  14862 DT (13.73%)
  Abr:  15001 DT (13.86%)
  Mai:  14811 DT (13.69%)
  Jun:  14815 DT (13.69%)
  Jul:  16737 DT (15.47%)
  Ago:   4405 DT ( 4.07%)

Total: 108219 DT

In [10]:
# Criar novas colunas antes de exportar para parquet

# Converter FCARGA para datetime para extrair informações
df['data'] = pd.to_datetime(df['FCARGA'])

# Week number (ISO week)
df['week_number'] = df['data'].dt.isocalendar().week

# Week day (0=Segunda, 6=Domingo)
df['week_day'] = df['data'].dt.day_name()

# Total ingresso = ingresso_danone + INGRESODT
df['total_ingresso'] = df['ingresso_danone'].fillna(0) + df['INGRESODT']

print("Colunas criadas:")
print(f"  ✓ week_number")
print(f"  ✓ week_day")
print(f"  ✓ total_ingresso")

print(f"\nExemplos:")
df[['FCARGA', 'week_number', 'week_day', 'INGRESODT', 'ingresso_danone', 'total_ingresso']].head(10)

Colunas criadas:
  ✓ week_number
  ✓ week_day
  ✓ total_ingresso

Exemplos:

,FCARGA,week_number,week_day,INGRESODT,ingresso_danone,total_ingresso
0,2025-12-29,1,Monday,10.69,NaN,10.69
1,2025-12-29,1,Monday,125.04,NaN,125.04
2,2025-12-30,1,Tuesday,0.00,NaN,0.00
3,2025-12-30,1,Tuesday,0.00,NaN,0.00
4,2025-12-30,1,Tuesday,0.00,NaN,0.00
5,2025-12-30,1,Tuesday,0.00,NaN,0.00
6,2025-12-30,1,Tuesday,0.00,NaN,0.00
7,2025-12-30,1,Tuesday,0.00,NaN,0.00
8,2026-01-02,1,Friday,23.54,NaN,23.54
9,2026-01-02,1,Friday,15.07,NaN,15.07

tratamento antes das metricas

In [11]:
# Garantir que capacidade_norm existe
if 'capacidade_norm' not in df.columns:
    print("Criando capacidade_norm...")
    
    # Converter para número
    df['CAMION_CAPACIDAD_NUM'] = pd.to_numeric(df['CAMION_CAPACIDAD'], errors='coerce')
    
    # Mapeamento de normalização
    mapeamento = {
        4: 6, 5: 6, 6: 6,
        8: 12, 12: 12,
        14: 20, 15: 20, 16: 20, 18: 20, 20: 20,
        22: 24, 24: 24,
        33: 33, 66: 66
    }
    
    # Aplicar mapeamento
    df['capacidade_norm'] = df['CAMION_CAPACIDAD_NUM'].map(mapeamento)
    
    # Tratar zeros
    linhas_zero = df['CAMION_CAPACIDAD_NUM'] == 0
    if linhas_zero.sum() > 0:
        capacidade_por_codeut = df[df['CAMION_CAPACIDAD_NUM'] > 0].groupby('CODEUT')['capacidade_norm'].agg(lambda x: x.mode()[0] if len(x.mode()) > 0 else x.max())
        for cu in df[linhas_zero]['CODEUT'].unique():
            if cu in capacidade_por_codeut.index:
                df.loc[(df['CODEUT'] == cu) & linhas_zero, 'capacidade_norm'] = capacidade_por_codeut[cu]

# Criar coluna indicadora
df['dados_validos'] = df['capacidade_norm'].notna()

print("="*80)
print("MARCAÇÃO DE DADOS")
print("="*80)

print(f"Total linhas: {len(df):,}")
print(f"Dados válidos: {df['dados_validos'].sum():,}")
print(f"Dados incompletos (ignorar): {(~df['dados_validos']).sum():,}")

print(f"\n--- Cálculos usarão apenas linhas com dados_validos = True ---")

Criando capacidade_norm...
================================================================================
MARCAÇÃO DE DADOS
================================================================================
Total linhas: 108,219
Dados válidos: 107,958
Dados incompletos (ignorar): 261

--- Cálculos usarão apenas linhas com dados_validos = True ---

In [ ]:
# Configurar pandas para ver tudo
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

# Calcular colunas derivadas
df['custo_por_palete'] = df['COSTEDT'] / df['PALETS'].replace(0, 1)
df['ingresso_por_palete'] = df['INGRESODT'] / df['PALETS'].replace(0, 1)
df['taxa_ocupacao'] = (df['PALETS'] / df['capacidade_norm'].replace(0, 1)) * 100
df['margem'] = df['INGRESODT'] - df['COSTEDT']

# Lista de colunas finais
colunas_finais = [
    'FENTREGA', 'CODEUT', 'capacidade_norm', 'PALETS', 'INGRESODT', 'COSTEDT',
    'PROV_ORIGEN', 'LOCORIGEN', 'PROV_DESTINO', 'LOCDESTINO', 'CPOSTAL', 'CPOSTAD',
    'TRANSPORTISTA', 'week_day', 'week_number', 'mes', 'mes_nome', 'data',
    'dados_validos', 'LOCCAR', 'LUGARCARGA', 'LOCDES', 'LUGARDESCARGA', 'TRACTORA',
    'PESO_BRUTO', 'CODEDT', 'CODACT', 'TIPOCLIENTE', 'TIPOFLUJO',
    'PROV_ENTREGAR', 'PAISENTREGAR', 'ACTIVIDAD',
    'custo_por_palete', 'ingresso_por_palete', 'taxa_ocupacao', 'margem'
]

# Selecionar colunas
df_sel = df[colunas_finais].copy()

print(f"df_sel criado: {len(df_sel):,} linhas x {len(df_sel.columns)} colunas")
print(f"CPOSTAL únicos: {df_sel['CPOSTAL'].nunique()}")

In [12]:
# Ler ficheiro de coordenadas
import platform
if platform.system() == 'Windows':
    coords_path = r"C:\Users\LISARR\Documents\python\00.Metadados\CP7COORDS_FORMATADO.CSV"
elif platform.system() == 'Darwin':
    coords_path = "/Volumes/RR/DB/CP7COORDS_FORMATADO.CSV"
else:
    coords_path = "CP7COORDS_FORMATADO.CSV"

coords = pd.read_csv(coords_path, sep=';', encoding='utf-8')
coords['POINT_X'] = coords['POINT_X'].str.replace(',', '.').astype(float)
coords['POINT_Y'] = coords['POINT_Y'].str.replace(',', '.').astype(float)

print(f"Coordenadas carregadas: {len(coords):,} registos")

Coordenadas carregadas: 178,409 registos

In [13]:
# Preparar dados para origem e destino
coords_origem = coords[['CP', 'POINT_X', 'POINT_Y']].copy()
coords_origem.columns = ['CPOSTAL', 'longitude_origem', 'latitude_origem']

coords_destino = coords[['CP', 'POINT_X', 'POINT_Y']].copy()
coords_destino.columns = ['CPOSTAD', 'longitude_destino', 'latitude_destino']

# Join com origem
df_sel = df_sel.merge(coords_origem, on='CPOSTAL', how='left')

# Join com destino
df_sel = df_sel.merge(coords_destino, on='CPOSTAD', how='left')

print(f"\n✓ Coordenadas adicionadas a df_sel")
print(f"Linhas com coordenadas origem: {df_sel['latitude_origem'].notna().sum():,}")
print(f"Linhas com coordenadas destino: {df_sel['latitude_destino'].notna().sum():,}")
print(f"Total colunas: {len(df_sel.columns)}")

NameError: name 'df_sel' is not defined

JOIN CSV COORDENADAS

In [ ]:
import platform

# Detecção do caminho do ficheiro de coordenadas
if platform.system() == 'Windows':
    coords_path = r"C:\Users\LISARR\Documents\python\00.Metadados\CP7COORDS_FORMATADO.CSV"
elif platform.system() == 'Darwin':
    coords_path = "/Volumes/RR/DB/CP7COORDS_FORMATADO.CSV"
else:
    coords_path = "CP7COORDS_FORMATADO.CSV"

# Ler ficheiro de coordenadas
coords = pd.read_csv(coords_path, sep=';', encoding='utf-8')

# Converter coordenadas de vírgula para ponto
coords['POINT_X'] = coords['POINT_X'].str.replace(',', '.').astype(float)
coords['POINT_Y'] = coords['POINT_Y'].str.replace(',', '.').astype(float)

print(f"Coordenadas carregadas: {len(coords):,} registos")

# Preparar dados para origem
coords_origem = coords[['CP', 'POINT_X', 'POINT_Y']].copy()
coords_origem.columns = ['CPOSTAL', 'longitude_origem', 'latitude_origem']

# Preparar dados para destino
coords_destino = coords[['CP', 'POINT_X', 'POINT_Y']].copy()
coords_destino.columns = ['CPOSTAD', 'longitude_destino', 'latitude_destino']

# Join com origem
df_sel = df_sel.merge(coords_origem, on='CPOSTAL', how='left')

# Join com destino
df_sel = df_sel.merge(coords_destino, on='CPOSTAD', how='left')

print(f"\n✓ Coordenadas adicionadas a df_sel")
print(f"Linhas com coordenadas origem: {df_sel['latitude_origem'].notna().sum():,}")
print(f"Linhas com coordenadas destino: {df_sel['latitude_destino'].notna().sum():,}")
print(f"Total colunas: {len(df_sel.columns)}")

Coordenadas carregadas: 178,409 registos

✓ Coordenadas adicionadas a df_sel
Linhas com coordenadas origem: 5
Linhas com coordenadas destino: 5
Total colunas: 48

In [ ]:
# Diagnosticar join de coordenadas
print("="*80)
print("DIAGNÓSTICO: POR QUE FALHARAM OS JOINS?")
print("="*80)

print(f"\nExemplos de CPOSTAL em df_sel:")
print(df_sel['CPOSTAL'].head(20).tolist())

print(f"\nExemplos de CP em coords:")
print(coords['CP'].head(20).tolist())

print(f"\n--- Verificar match ---")
cpostal_unicos = set(df_sel['CPOSTAL'].dropna().unique())
cp_unicos = set(coords['CP'].unique())

match = cpostal_unicos.intersection(cp_unicos)
print(f"CPOSTAL únicos em df_sel: {len(cpostal_unicos)}")
print(f"CP únicos em coords: {len(cp_unicos)}")
print(f"Match encontrado: {len(match)}")

print(f"\n--- Exemplos de CPOSTAL que têm match ---")
print(list(match)[:10])

print(f"\n--- Exemplos de CPOSTAL que NÃO têm match ---")
sem_match = list(cpostal_unicos - cp_unicos)[:10]
print(sem_match)

print(f"\n--- Verificar espaços/caracteres especiais ---")
print(f"CPOSTAL amostra: '{df_sel['CPOSTAL'].iloc[0]}'")
print(f"CP amostra: '{coords['CP'].iloc[0]}'")
print(f"Tamanho CPOSTAL: {len(str(df_sel['CPOSTAL'].iloc[0]))}")
print(f"Tamanho CP: {len(str(coords['CP'].iloc[0]))}")

================================================================================
DIAGNÓSTICO: POR QUE FALHARAM OS JOINS?
================================================================================

Exemplos de CPOSTAL em df_sel:
['2050-540', '2050-540', '2050-540', '2050-540', '2050-540']

Exemplos de CP em coords:
['1000-001', '1000-002', '1000-003', '1000-004', '1000-005', '1000-007', '1000-008', '1000-009', '1000-010', '1000-011', '1000-012', '1000-013', '1000-014', '1000-015', '1000-016', '1000-017', '1000-018', '1000-019', '1000-020', '1000-021']

--- Verificar match ---
CPOSTAL únicos em df_sel: 1
CP únicos em coords: 178409
Match encontrado: 1

--- Exemplos de CPOSTAL que têm match ---
['2050-540']

--- Exemplos de CPOSTAL que NÃO têm match ---
[]

--- Verificar espaços/caracteres especiais ---
CPOSTAL amostra: '2050-540'
CP amostra: '1000-001'
Tamanho CPOSTAL: 8
Tamanho CP: 8

In [ ]:
df_sel.head()

,FENTREGA,CODEUT,capacidade_norm,PALETS,INGRESODT,COSTEDT,PROV_ORIGEN,LOCORIGEN,PROV_DESTINO,LOCDESTINO,CPOSTAL,CPOSTAD,TRANSPORTISTA,week_day,week_number,mes,mes_nome,data,dados_validos,LOCCAR,LUGARCARGA,LOCDES,LUGARDESCARGA,TRACTORA,PESO_BRUTO,CODEDT,CODACT,TIPOCLIENTE,TIPOFLUJO,PROV_ENTREGAR,PAISENTREGAR,ACTIVIDAD,custo_por_palete,ingresso_por_palete,taxa_ocupacao,margem,longitude_origem_x,latitude_origem_x,longitude_destino_x,latitude_destino_x,longitude_origem_y,latitude_origem_y,longitude_destino_y,latitude_destino_y,longitude_origem,latitude_origem,longitude_destino,latitude_destino
0,2026-01-02,3344051,33.0,1.0,10.69,4.64,Lisboa,Vila Nova da Rainha,Aveiro,Oliveira do Bairro,2050-540,3770-305,SOLIDO CLICK LDA,Monday,1,1,January,2025-12-29,True,137998,SALVESEN LOGISTICA PORTUGAL,573897,"PLAT. COOPLECNORTE,S.A.",0000XXX,227.26,25387086,011,TLD PORTUGAL,Directo,Aveiro,PORTUGAL,DANONE PORTUGAL,4.6400,10.6900,3.030303,6.05,-8.920854,39.047635,-8.523268,40.512134,-8.920854,39.047635,-8.523268,40.512134,-8.920854,39.047635,-8.523268,40.512134
1,2026-01-02,3344051,33.0,25.0,125.04,236.86,Lisboa,Vila Nova da Rainha,Aveiro,Oliveira do Bairro,2050-540,3770-305,SOLIDO CLICK LDA,Monday,1,1,January,2025-12-29,True,137998,SALVESEN LOGISTICA PORTUGAL,573897,"PLAT. COOPLECNORTE,S.A.",0000XXX,2719.88,25398553,011,TLD PORTUGAL,Directo,Aveiro,PORTUGAL,DANONE PORTUGAL,9.4744,5.0016,75.757576,-111.82,-8.920854,39.047635,-8.523268,40.512134,-8.920854,39.047635,-8.523268,40.512134,-8.920854,39.047635,-8.523268,40.512134
2,2026-01-02,3344052,33.0,1.0,0.00,12.02,Lisboa,Vila Nova da Rainha,Coimbra,Condeixa-a-Nova,2050-540,3150-020,Transportes Fernando Simões Monteiro Unip. Lda,Tuesday,1,1,January,2025-12-30,True,137998,SALVESEN LOGISTICA PORTUGAL,298515,DL Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,487.26,25392919,011,TLD PORTUGAL,DLS,Aveiro,PORTUGAL,DANONE PORTUGAL,12.0200,0.0000,3.030303,-12.02,-8.920854,39.047635,-8.531480,40.167186,-8.920854,39.047635,-8.531480,40.167186,-8.920854,39.047635,-8.531480,40.167186
3,2026-01-02,3344052,33.0,1.0,0.00,10.82,Lisboa,Vila Nova da Rainha,Coimbra,Condeixa-a-Nova,2050-540,3150-020,Transportes Fernando Simões Monteiro Unip. Lda,Tuesday,1,1,January,2025-12-30,True,137998,SALVESEN LOGISTICA PORTUGAL,298515,DL Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,423.44,25393741,011,TLD PORTUGAL,DLS,Aveiro,PORTUGAL,DANONE PORTUGAL,10.8200,0.0000,3.030303,-10.82,-8.920854,39.047635,-8.531480,40.167186,-8.920854,39.047635,-8.531480,40.167186,-8.920854,39.047635,-8.531480,40.167186
4,2026-01-02,3344052,33.0,1.0,0.00,6.01,Lisboa,Vila Nova da Rainha,Coimbra,Condeixa-a-Nova,2050-540,3150-020,Transportes Fernando Simões Monteiro Unip. Lda,Tuesday,1,1,January,2025-12-30,True,137998,SALVESEN LOGISTICA PORTUGAL,298515,DL Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,236.29,25393743,011,TLD PORTUGAL,DLS,Leiria,PORTUGAL,DANONE PORTUGAL,6.0100,0.0000,3.030303,-6.01,-8.920854,39.047635,-8.531480,40.167186,-8.920854,39.047635,-8.531480,40.167186,-8.920854,39.047635,-8.531480,40.167186

TRATAMENTO DE KM

In [ ]:
import sqlite3

# Conectar à BD
if platform.system() == 'Windows':
    DB_PATH = r"C:\Users\LISARR\Documents\python\01.Financeiro\inform_27.db"
elif platform.system() == 'Darwin':
    DB_PATH = "/Volumes/RR/DB/inform_27.db"
else:
    DB_PATH = "inform_27.db"

con = sqlite3.connect(DB_PATH)

# Ler tabela km_diario_2026
km_diario = pd.read_sql_query("SELECT * FROM km_diario_2026", con)
con.close()

print(f"km_diario_2026 carregada: {len(km_diario):,} linhas")

# Converter data para datetime
km_diario['data'] = pd.to_datetime(km_diario['data'])

# Renomear coluna trator para TRACTORA para match
km_diario.rename(columns={'trator': 'TRACTORA'}, inplace=True)

# Converter TRACTORA em df_sel para datetime (se necessário)
df_sel['data'] = pd.to_datetime(df_sel['data'])

# Join: data + TRACTORA
df_merged = df_sel.merge(
    km_diario[['TRACTORA', 'data', 'km']],
    on=['TRACTORA', 'data'],
    how='left'
)

# Verificar duplicatas (mesma matrícula, mesma data, múltiplos CODEUT)
duplicatas = df_merged[df_merged.duplicated(subset=['TRACTORA', 'data'], keep=False)]

if len(duplicatas) > 0:
    print(f"\n⚠ Encontradas {len(duplicatas):,} linhas com múltiplos CODEUT por matrícula/data")
    print("Distribuindo KM proporcionalmente...")
    
    # Distribuir KM
    for (tractor, data_val), group in df_merged.groupby(['TRACTORA', 'data']):
        if len(group) > 1 and group['km'].notna().any():
            km_total = group['km'].iloc[0]
            km_distribuido = km_total / len(group)
            df_merged.loc[(df_merged['TRACTORA'] == tractor) & (df_merged['data'] == data_val), 'km'] = km_distribuido

print(f"\n✓ KM adicionado a df_sel")
print(f"Linhas com KM: {df_merged['km'].notna().sum():,}")
print(f"Total colunas: {len(df_merged.columns)}")

# Atualizar df_sel
df_sel = df_merged.copy()

km_diario_2026 carregada: 3,874 linhas

⚠ Encontradas 5 linhas com múltiplos CODEUT por matrícula/data
Distribuindo KM proporcionalmente...

✓ KM adicionado a df_sel
Linhas com KM: 0
Total colunas: 49

In [ ]:
df_sel.head(10)

,FENTREGA,CODEUT,capacidade_norm,PALETS,INGRESODT,COSTEDT,PROV_ORIGEN,LOCORIGEN,PROV_DESTINO,LOCDESTINO,CPOSTAL,CPOSTAD,TRANSPORTISTA,week_day,week_number,mes,mes_nome,data,dados_validos,LOCCAR,LUGARCARGA,LOCDES,LUGARDESCARGA,TRACTORA,PESO_BRUTO,CODEDT,CODACT,TIPOCLIENTE,TIPOFLUJO,PROV_ENTREGAR,PAISENTREGAR,ACTIVIDAD,custo_por_palete,ingresso_por_palete,taxa_ocupacao,margem,longitude_origem_x,latitude_origem_x,longitude_destino_x,latitude_destino_x,longitude_origem_y,latitude_origem_y,longitude_destino_y,latitude_destino_y,longitude_origem,latitude_origem,longitude_destino,latitude_destino,km
0,2026-01-02,3344051,33.0,1.0,10.69,4.64,Lisboa,Vila Nova da Rainha,Aveiro,Oliveira do Bairro,2050-540,3770-305,SOLIDO CLICK LDA,Monday,1,1,January,2025-12-29,True,137998,SALVESEN LOGISTICA PORTUGAL,573897,"PLAT. COOPLECNORTE,S.A.",0000XXX,227.26,25387086,011,TLD PORTUGAL,Directo,Aveiro,PORTUGAL,DANONE PORTUGAL,4.6400,10.6900,3.030303,6.05,-8.920854,39.047635,-8.523268,40.512134,-8.920854,39.047635,-8.523268,40.512134,-8.920854,39.047635,-8.523268,40.512134,NaN
1,2026-01-02,3344051,33.0,25.0,125.04,236.86,Lisboa,Vila Nova da Rainha,Aveiro,Oliveira do Bairro,2050-540,3770-305,SOLIDO CLICK LDA,Monday,1,1,January,2025-12-29,True,137998,SALVESEN LOGISTICA PORTUGAL,573897,"PLAT. COOPLECNORTE,S.A.",0000XXX,2719.88,25398553,011,TLD PORTUGAL,Directo,Aveiro,PORTUGAL,DANONE PORTUGAL,9.4744,5.0016,75.757576,-111.82,-8.920854,39.047635,-8.523268,40.512134,-8.920854,39.047635,-8.523268,40.512134,-8.920854,39.047635,-8.523268,40.512134,NaN
2,2026-01-02,3344052,33.0,1.0,0.00,12.02,Lisboa,Vila Nova da Rainha,Coimbra,Condeixa-a-Nova,2050-540,3150-020,Transportes Fernando Simões Monteiro Unip. Lda,Tuesday,1,1,January,2025-12-30,True,137998,SALVESEN LOGISTICA PORTUGAL,298515,DL Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,487.26,25392919,011,TLD PORTUGAL,DLS,Aveiro,PORTUGAL,DANONE PORTUGAL,12.0200,0.0000,3.030303,-12.02,-8.920854,39.047635,-8.531480,40.167186,-8.920854,39.047635,-8.531480,40.167186,-8.920854,39.047635,-8.531480,40.167186,NaN
3,2026-01-02,3344052,33.0,1.0,0.00,10.82,Lisboa,Vila Nova da Rainha,Coimbra,Condeixa-a-Nova,2050-540,3150-020,Transportes Fernando Simões Monteiro Unip. Lda,Tuesday,1,1,January,2025-12-30,True,137998,SALVESEN LOGISTICA PORTUGAL,298515,DL Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,423.44,25393741,011,TLD PORTUGAL,DLS,Aveiro,PORTUGAL,DANONE PORTUGAL,10.8200,0.0000,3.030303,-10.82,-8.920854,39.047635,-8.531480,40.167186,-8.920854,39.047635,-8.531480,40.167186,-8.920854,39.047635,-8.531480,40.167186,NaN
4,2026-01-02,3344052,33.0,1.0,0.00,6.01,Lisboa,Vila Nova da Rainha,Coimbra,Condeixa-a-Nova,2050-540,3150-020,Transportes Fernando Simões Monteiro Unip. Lda,Tuesday,1,1,January,2025-12-30,True,137998,SALVESEN LOGISTICA PORTUGAL,298515,DL Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,236.29,25393743,011,TLD PORTUGAL,DLS,Leiria,PORTUGAL,DANONE PORTUGAL,6.0100,0.0000,3.030303,-6.01,-8.920854,39.047635,-8.531480,40.167186,-8.920854,39.047635,-8.531480,40.167186,-8.920854,39.047635,-8.531480,40.167186,NaN

In [ ]:
# Verificar quantas linhas têm KM
print("="*80)
print("ANÁLISE DE KM")
print("="*80)

print(f"\nTotal linhas df_sel: {len(df_sel):,}")
print(f"Linhas com KM: {df_sel['km'].notna().sum():,}")
print(f"Linhas sem KM: {df_sel['km'].isna().sum():,}")
print(f"Percentagem com KM: {(df_sel['km'].notna().sum() / len(df_sel) * 100):.2f}%")

print(f"\n--- Estatísticas KM ---")
print(df_sel['km'].describe())

================================================================================
ANÁLISE DE KM
================================================================================

Total linhas df_sel: 5
Linhas com KM: 0
Linhas sem KM: 5
Percentagem com KM: 0.00%

--- Estatísticas KM ---
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: km, dtype: float64

Exportar ficheiro

In [ ]:
caminho_parquet = r"C:\Users\LISARR\Documents\python\01.Financeiro\inform_27_2026_final.parquet"

# Exportar para parquet
df.to_parquet(caminho_parquet, index=False)

print(f"✅ Ficheiro exportado: {caminho_parquet}")
print(f"Linhas: {len(df)}")
print(f"Colunas: {len(df.columns)}")
print(f"Tamanho: {df.memory_usage(deep=True).sum() / 1024**2:.2f} MB")

✅ Ficheiro exportado: C:\Users\LISARR\Documents\python\01.Financeiro\inform_27_2026_final.parquet
Linhas: 108219
Colunas: 65
Tamanho: 138.08 MB