In [14]:
import sqlite3
import pandas as pd
import platform
import warnings
warnings.filterwarnings('ignore')

# Detecção do SO e caminho BD
if platform.system() == 'Windows':
    DB_PATH = r"C:\Users\LISARR\Documents\python\01.Financeiro\inform_27.db"
elif platform.system() == 'Darwin':
    DB_PATH = "/Volumes/RR/DB/inform_27.db"
else:
    DB_PATH = "inform_27.db"

# Conectar
con = sqlite3.connect(DB_PATH)
cursor = con.cursor()

In [15]:
df = pd.read_sql_query("SELECT * FROM inform_27_2026", con)
con.close()

In [16]:
print(f"Shape: {df.shape}")
print(f"\nColunas: {df.shape[1]}")
df.head()

Shape: (83610, 58)

Colunas: 58

,id,PROPIETARIO,TRAYECTO,TRANSPORTISTA,TRACTORA,REMOLQUE,INGRESODT,COSTEDT,RENTADT,PALETSDT,...,LOCDES,LUGARDESCARGA,TEMP_MERC_PED,TIPOPALETA,CAMION_TIPO,CAMION_CAPACIDAD,TIPO_COMBUSTIBLE,KMREALES,ALBARAN,ficheiro_origem
0,1,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,SOLIDO CLICK LDA,0000XXX,0000XXX,10.69,4.64,6.05,0.49,...,573897,"PLAT. COOPLECNORTE,S.A.",RFGRFG,EUR,Trailer 33 plts,33,DIESEL,194.134,NO,SAL_DAT027 (11).xls
1,2,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,SOLIDO CLICK LDA,0000XXX,0000XXX,125.04,236.86,-111.82,25,...,573897,"PLAT. COOPLECNORTE,S.A.",RFGRFG,EUR,Trailer 33 plts,33,DIESEL,194.134,NO,SAL_DAT027 (11).xls
2,3,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,0000XXX,0,12.02,-12.02,0.8,...,298515,DL Transportes Fernando Simões Monteiro Unip. Lda,RFGRFG,EUR,Trailer 33 plts,33,DIESEL,151.803,NO,SAL_DAT027 (11).xls
3,4,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,0000XXX,0,10.82,-10.82,0.72,...,298515,DL Transportes Fernando Simões Monteiro Unip. Lda,RFGRFG,EUR,Trailer 33 plts,33,DIESEL,151.803,NO,SAL_DAT027 (11).xls
4,5,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,0000XXX,0,6.01,-6.01,0.4,...,298515,DL Transportes Fernando Simões Monteiro Unip. Lda,RFGRFG,EUR,Trailer 33 plts,33,DIESEL,151.803,NO,SAL_DAT027 (11).xls

In [17]:
# Converter tipos de dados numéricos
df['INGRESODT'] = pd.to_numeric(df['INGRESODT'], errors='coerce')
df['COSTEDT'] = pd.to_numeric(df['COSTEDT'], errors='coerce')
df['RENTADT'] = pd.to_numeric(df['RENTADT'], errors='coerce')
df['PALETSDT'] = pd.to_numeric(df['PALETSDT'], errors='coerce')
df['PESO_BRUTO'] = pd.to_numeric(df['PESO_BRUTO'], errors='coerce')
df['PALETS'] = pd.to_numeric(df['PALETS'], errors='coerce')
df['KM'] = pd.to_numeric(df['KM'], errors='coerce')
df['KMREALES'] = pd.to_numeric(df['KMREALES'], errors='coerce')

# CODEUT como string
df['CODEUT'] = df['CODEUT'].astype(str)

# Trim em strings (ANTES de converter as datas)
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

# Datas como datetime (sem hora, prontas para PBI) - DEPOIS do trim
df['FCARGA'] = pd.to_datetime(df['FCARGA'], format='%Y%m%d', errors='coerce').dt.date
df['FENTREGA'] = pd.to_datetime(df['FENTREGA'], format='%Y%m%d', errors='coerce').dt.date

In [18]:
print(f"Shape: {df.shape}")
print(f"\nTipos de dados:")
print(df.dtypes)
print(f"\nNulos por coluna:")
print(df.isnull().sum())
df.head()

Shape: (83610, 58)

Tipos de dados:
id                    int64
PROPIETARIO             str
TRAYECTO                str
TRANSPORTISTA           str
TRACTORA                str
REMOLQUE                str
INGRESODT           float64
COSTEDT             float64
RENTADT             float64
PALETSDT            float64
PESO_BRUTO          float64
CODEUT                  str
ESTADO_UT               str
RANGO_UT                str
FCARGA               object
ACTIVIDAD               str
CODEDT                  str
ESTADO_DT               str
REFERENCIA              str
CODACT                  str
LOCORIGEN               str
PROV_ORIGEN             str
PAISORIGEN              str
CPOSTAL                 str
LOCDESTINO              str
PROV_DESTINO            str
PAISDESTINO             str
CPOSTAD                 str
KM                  float64
FENTREGA             object
ORIGEN                  str
ENTREGAR                str
PROV_ENTREGAR           str
PAISENTREGAR            str
DESTINO                 str
PALETS              float64
PREFAC                  str
RUTA                    str
COBROREAL               str
GESTION                 str
DEPART                  str
USCODE                  str
USUARIO                 str
TIPOCLIENTE             str
TIPOFLUJO               str
WMSCODRGT               str
LOCCAR                  str
LUGARCARGA              str
LOCDES                  str
LUGARDESCARGA           str
TEMP_MERC_PED           str
TIPOPALETA              str
CAMION_TIPO             str
CAMION_CAPACIDAD        str
TIPO_COMBUSTIBLE        str
KMREALES            float64
ALBARAN                 str
ficheiro_origem         str
dtype: object

Nulos por coluna:
id                      0
PROPIETARIO             0
TRAYECTO             4568
TRANSPORTISTA           0
TRACTORA             1763
REMOLQUE                0
INGRESODT               0
COSTEDT                 0
RENTADT                 0
PALETSDT                0
PESO_BRUTO              0
CODEUT                  0
ESTADO_UT               0
RANGO_UT                0
FCARGA                  0
ACTIVIDAD               0
CODEDT                  0
ESTADO_DT               0
REFERENCIA              0
CODACT                  0
LOCORIGEN               4
PROV_ORIGEN             4
PAISORIGEN              0
CPOSTAL                 0
LOCDESTINO          11793
PROV_DESTINO        11811
PAISDESTINO            17
CPOSTAD                17
KM                  83511
FENTREGA                0
ORIGEN               8610
ENTREGAR               21
PROV_ENTREGAR       11931
PAISENTREGAR           21
DESTINO              9609
PALETS                  0
PREFAC                  0
RUTA                    0
COBROREAL               0
GESTION                 6
DEPART                  6
USCODE                  0
USUARIO                 0
TIPOCLIENTE         54363
TIPOFLUJO               0
WMSCODRGT            8121
LOCCAR                  0
LUGARCARGA              0
LOCDES                 17
LUGARDESCARGA          17
TEMP_MERC_PED           0
TIPOPALETA              0
CAMION_TIPO             1
CAMION_CAPACIDAD        0
TIPO_COMBUSTIBLE        0
KMREALES                0
ALBARAN                 0
ficheiro_origem         0
dtype: int64

,id,PROPIETARIO,TRAYECTO,TRANSPORTISTA,TRACTORA,REMOLQUE,INGRESODT,COSTEDT,RENTADT,PALETSDT,...,LOCDES,LUGARDESCARGA,TEMP_MERC_PED,TIPOPALETA,CAMION_TIPO,CAMION_CAPACIDAD,TIPO_COMBUSTIBLE,KMREALES,ALBARAN,ficheiro_origem
0,1,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,SOLIDO CLICK LDA,0000XXX,0000XXX,10.69,4.64,6.05,0.49,...,573897,"PLAT. COOPLECNORTE,S.A.",RFGRFG,EUR,Trailer 33 plts,33,DIESEL,194.134,NO,SAL_DAT027 (11).xls
1,2,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,SOLIDO CLICK LDA,0000XXX,0000XXX,125.04,236.86,-111.82,25.00,...,573897,"PLAT. COOPLECNORTE,S.A.",RFGRFG,EUR,Trailer 33 plts,33,DIESEL,194.134,NO,SAL_DAT027 (11).xls
2,3,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,0000XXX,0.00,12.02,-12.02,0.80,...,298515,DL Transportes Fernando Simões Monteiro Unip. Lda,RFGRFG,EUR,Trailer 33 plts,33,DIESEL,151.803,NO,SAL_DAT027 (11).xls
3,4,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,0000XXX,0.00,10.82,-10.82,0.72,...,298515,DL Transportes Fernando Simões Monteiro Unip. Lda,RFGRFG,EUR,Trailer 33 plts,33,DIESEL,151.803,NO,SAL_DAT027 (11).xls
4,5,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,0000XXX,0.00,6.01,-6.01,0.40,...,298515,DL Transportes Fernando Simões Monteiro Unip. Lda,RFGRFG,EUR,Trailer 33 plts,33,DIESEL,151.803,NO,SAL_DAT027 (11).xls

In [19]:
# Agrupar por TRANSPORTISTA (soma todas as linhas de entregas)
df_transp = df.groupby('TRANSPORTISTA').agg({
    'COSTEDT': 'sum',
    'PALETSDT': 'sum'
})

# Calcular custo por palete
df_transp['custo_palete'] = (df_transp['COSTEDT'] / df_transp['PALETSDT']).round(2)

# Ordenar por custo_palete
df_transp = df_transp.sort_values('custo_palete', ascending=False)

# Formatar para apresentação
df_transp_display = df_transp.copy()
df_transp_display['COSTEDT'] = df_transp_display['COSTEDT'].apply(lambda x: f"{x:,.2f}")
df_transp_display['PALETSDT'] = df_transp_display['PALETSDT'].apply(lambda x: f"{x:,.2f}")
df_transp_display['custo_palete'] = df_transp_display['custo_palete'].apply(lambda x: f"{x:,.2f}")

print(f"Transportadores: {len(df_transp)}")
df_transp_display

Transportadores: 27

,COSTEDT,PALETSDT,custo_palete
TRANSPORTISTA,,,
JOTAVIO TRANSPORTES LDA,66.21,0.04,"1,655.25"
JOJULOCU S.L,150.00,1.00,150.00
TORRESTIR - TRANSPORTES NACIONAIS E INTERNACIONAIS S.A.,"134,623.66",929.86,144.78
"Logislink - Terminal Logistica, Lda","25,365.08",186.01,136.36
CMTIR TRANSPORTES NAC. INTERN. S.A,"164,885.06","3,448.24",47.82
Transportes Fernando Simões Monteiro Unip. Lda,"175,934.17","4,022.54",43.74
"TRANSPORTES FIGUEIREDO & FIGUEIREDO, LDA","79,097.64","1,992.98",39.69
SOLIDO CLICK LDA,"15,241.22",513.86,29.66
DF LOGISTICA LDA,273.00,10.61,25.73
"TRANSPARENTODISSEIA - Transportes Unipessoal, Lda.","90,344.91","3,876.56",23.31
J. MARCOS FABIO E SEATLLE TRANSPORTES LDA,"7,201.85",309.64,23.26
TRANSPORTES PAULO COSTA & FERREIRA LDA,"172,240.36","7,714.71",22.33
"TRANSPORTES GOMEZ MANRIQUE, S.L.",161.06,8.00,20.13
TRANSPORTES ROSALIA LDA,"52,268.86","2,784.07",18.77
MOSCA PORTUGAL LDA,"35,160.00","2,079.00",16.91
LOGISTA FREIGHT S.A.U.,"8,768.89",530.00,16.55
NO USAR,"4,860.00",297.00,16.36
"TRANSPORTES FLORENCIO SILVA, LDA. -","889,935.49","65,706.79",13.54
"TJA-TRANSPORTES J.AMARAL, S.A. -","138,832.71","10,621.71",13.07
RAMITRANS TRANSPORTES LDA,"31,606.51","3,231.52",9.78
WORLD RUNNERS UNIPESSOAL LDA,"51,740.33","5,998.87",8.63
MODELO CONTINENTE HIPERMERCADOS S.A.,"222,122.92","26,605.76",8.35
TRANSBASE - TRANSPORTES E LOGISTICA S.A.,"22,115.33","2,857.14",7.74
JMR PRESTAÇAO DE SERVIÇOS PARA A DISTRIBUÇAO S.A,"345,594.83","44,940.14",7.69
TRANSAURA TRANSPORTES LDA,"76,627.78","12,870.50",5.95
SALVESEN,0.00,"10,014.14",0.00
EL MOSCA S.A.,-60.00,132.00,-0.45

In [20]:
# Caminho do ficheiro
caminho = r"C:\Users\LISARR\Documents\python\01.Financeiro\Danone_Custos.xlsx"

# Ler sheet "Ingreso y coste" colunas 0-4 (A-E) a partir da linha 2
df_danone = pd.read_excel(
    caminho,
    sheet_name="Ingreso y coste",
    usecols=range(5),
    skiprows=1,
    header=None
)

# Renomear colunas
df_danone.columns = ['A', 'B', 'C', 'D', 'E']

print(f"Shape: {df_danone.shape}")
df_danone.head()

Shape: (12810, 5)

                          A                B   C           D          E
0         Etiquetas de fila  Suma de COSTEDT NaN     Ingreso  Resultado
1  5021683309     414004258           191.88 NaN  208.037374  16.157374
2  5021683310     414004258            69.77 NaN   60.002498  -9.767502
3  5021688514     413992813             8.51 NaN   26.738081  18.228081
4  5021688515     414010084             1.44 NaN    3.813613   2.373613

In [21]:
# Limpar espaços/caracteres não numéricos

# Remover linha de cabeçalho "Etiquetas de fila" se existir
df_danone_clean = df_danone[df_danone['A'] != 'Etiquetas de fila'].copy()

print(f"Registos df_danone_clean: {len(df_danone_clean)}")
df_danone_clean.head()
df_danone_clean['A_numeros_limpo'] = df_danone_clean['A'].str.replace(r'\D', '', regex=True)
df['REFERENCIA_limpo'] = df['REFERENCIA'].astype(str).str.replace(r'\D', '', regex=True)

# Primeira sequência (antes do espaço original no Excel)
df_danone_clean['primeira_seq_numeros'] = df_danone_clean['A'].str.split().str[0]
df_danone_clean['primeira_seq_numeros'] = df_danone_clean['primeira_seq_numeros'].str.replace(r'\D', '', regex=True)

# Set para procura rápida
referencias_set = set(df['REFERENCIA_limpo'].dropna())

# Estratégia 1: sequência completa
df_danone_clean['match_tipo'] = 'sem_match'
match_completo = df_danone_clean['A_numeros_limpo'].isin(referencias_set)
df_danone_clean.loc[match_completo, 'match_tipo'] = 'completo'

# Estratégia 2: primeira sequência (só para os que falharam na 1)
sem_match_mask = df_danone_clean['match_tipo'] == 'sem_match'
match_primeira = df_danone_clean.loc[sem_match_mask, 'primeira_seq_numeros'].isin(referencias_set)
df_danone_clean.loc[sem_match_mask & match_primeira.reindex(df_danone_clean.index, fill_value=False), 'match_tipo'] = 'primeira_seq'

print(f"Matches com sequência completa: {(df_danone_clean['match_tipo'] == 'completo').sum()}")
print(f"Matches com primeira sequência: {(df_danone_clean['match_tipo'] == 'primeira_seq').sum()}")
print(f"Sem match: {(df_danone_clean['match_tipo'] == 'sem_match').sum()}")
print(f"Taxa total de match: {(df_danone_clean['match_tipo'] != 'sem_match').sum() / len(df_danone_clean) * 100:.2f}%")

Registos df_danone_clean: 12809
Matches com sequência completa: 10059
Matches com primeira sequência: 55
Sem match: 2695
Taxa total de match: 78.96%

In [22]:
# Criar chave de match única (usa sequência completa, senão primeira sequência)
df_danone_clean['match_key'] = df_danone_clean.apply(
    lambda row: row['A_numeros_limpo'] if row['match_tipo'] == 'completo' 
    else (row['primeira_seq_numeros'] if row['match_tipo'] == 'primeira_seq' else None),
    axis=1
)

# Agrupar Danone por match_key (somar Ingreso = coluna D, caso haja duplicados)
danone_ingreso = df_danone_clean.dropna(subset=['match_key']).groupby('match_key')['D'].sum().reset_index()
danone_ingreso.columns = ['match_key', 'Ingreso']

# Merge no df
df = df.merge(
    danone_ingreso,
    left_on='REFERENCIA_limpo',
    right_on='match_key',
    how='left'
)
df = df.drop(columns=['match_key'])

# Preencher NaN com 0 (linhas sem correspondência Danone)
df['Ingreso'] = df['Ingreso'].fillna(0)

# Zerar Ingreso nas linhas duplicadas de REFERENCIA (cliente só paga 1x por REFERENCIA)
primeira_ocorrencia = ~df['REFERENCIA_limpo'].duplicated()
df['Ingreso'] = df['Ingreso'].where(primeira_ocorrencia, 0)

# Calcular ingresso total
df['ingresso_total'] = df['INGRESODT'] + df['Ingreso']

print(f"Linhas com Ingreso > 0: {(df['Ingreso'] > 0).sum()}")
print(f"\nValidação:")
print(f"Soma INGRESODT: {df['INGRESODT'].sum():,.2f}")
print(f"Soma Ingreso: {df['Ingreso'].sum():,.2f}")
print(f"Soma ingresso_total: {df['ingresso_total'].sum():,.2f}")

df[['REFERENCIA', 'INGRESODT', 'Ingreso', 'ingresso_total']].head(10)

Linhas com Ingreso > 0: 8310

Validação:
Soma INGRESODT: 2,296,469.26
Soma Ingreso: 777,173.26
Soma ingresso_total: 3,073,642.52

                 REFERENCIA  INGRESODT Ingreso ingresso_total
0  5021705579     413948820      10.69       0          10.69
1  5021695753     413975730     125.04       0         125.04
2  5021718153     413962673       0.00       0            0.0
3  5021741334     413968895       0.00       0            0.0
4  5021740631     413963593       0.00       0            0.0
5  5021718153     413962673       0.00       0            0.0
6  5021741334     413968895       0.00       0            0.0
7  5021740631     413963593       0.00       0            0.0
8  5021762386     413948513      23.54       0          23.54
9  5021760653     413972484      15.07       0          15.07

In [23]:
# Somar INGRESODT normalmente (é por linha de entrega, isso está correto)
soma_ingresodt = df['INGRESODT'].sum()

# Para ingresso_danone, só contar 1x por REFERENCIA_limpo (evitar duplicar)
ingresso_danone_unico = df.drop_duplicates(subset='REFERENCIA_limpo')['Ingreso'].sum()

print(f"Soma INGRESODT (todas as linhas): {soma_ingresodt:,.2f}")
print(f"Soma Ingreso (1x por REFERENCIA): {ingresso_danone_unico:,.2f}")
print(f"Total correto: {soma_ingresodt + ingresso_danone_unico:,.2f}")

print(f"\n{'='*50}")
print("Comparação com soma errada (linha a linha, com duplicação):")
print(f"Soma Ingreso (todas as linhas, ERRADO): {df['Ingreso'].sum():,.2f}")
print(f"Diferença por duplicação: {df['Ingreso'].sum() - ingresso_danone_unico:,.2f}")

Soma INGRESODT (todas as linhas): 2,296,469.26
Soma Ingreso (1x por REFERENCIA): 777,173.26
Total correto: 3,073,642.52

==================================================
Comparação com soma errada (linha a linha, com duplicação):
Soma Ingreso (todas as linhas, ERRADO): 777,173.26
Diferença por duplicação: 0.00

In [24]:
df

,id,PROPIETARIO,TRAYECTO,TRANSPORTISTA,TRACTORA,REMOLQUE,INGRESODT,COSTEDT,RENTADT,PALETSDT,...,TIPOPALETA,CAMION_TIPO,CAMION_CAPACIDAD,TIPO_COMBUSTIBLE,KMREALES,ALBARAN,ficheiro_origem,REFERENCIA_limpo,Ingreso,ingresso_total
0,1,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,SOLIDO CLICK LDA,0000XXX,0000XXX,10.69,4.64,6.05,0.49,...,EUR,Trailer 33 plts,33,DIESEL,194.134,NO,SAL_DAT027 (11).xls,5021705579413948820,0,10.69
1,2,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,SOLIDO CLICK LDA,0000XXX,0000XXX,125.04,236.86,-111.82,25.00,...,EUR,Trailer 33 plts,33,DIESEL,194.134,NO,SAL_DAT027 (11).xls,5021695753413975730,0,125.04
2,3,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,0000XXX,0.00,12.02,-12.02,0.80,...,EUR,Trailer 33 plts,33,DIESEL,151.803,NO,SAL_DAT027 (11).xls,5021718153413962673,0,0.0
3,4,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,0000XXX,0.00,10.82,-10.82,0.72,...,EUR,Trailer 33 plts,33,DIESEL,151.803,NO,SAL_DAT027 (11).xls,5021741334413968895,0,0.0
4,5,CEP,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,0000XXX,0.00,6.01,-6.01,0.40,...,EUR,Trailer 33 plts,33,DIESEL,151.803,NO,SAL_DAT027 (11).xls,5021740631413963593,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83605,92995,PTG,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,"TJA-TRANSPORTES J.AMARAL, S.A. -",AZ-70-DB,AV52146,624.43,39.46,584.97,5.43,...,EUR,Trailer doble piso,66,DIESEL,300.377,NO,SAL_DAT027 (63).xls,3700663440,0,624.43
83606,92996,PTG,DIANICOL (PONTA DELGADA) / DL Logislink - Term...,"Logislink - Terminal Logistica, Lda",0000XXX,0000XXX,624.43,1181.27,-556.84,5.43,...,EUR,Trailer 33 plts,33,DIESEL,0.000,NO,SAL_DAT027 (63).xls,3700663440,0,624.43
83607,92997,PTG,SALVESEN LOGISTICA PORTUGAL / FORMULAB - ADITI...,TRANSPORTES ROSALIA LDA,L200519,L200519,0.00,376.00,-376.00,23.98,...,EUR,Trailer 33 plts,33,DIESEL,271.494,NO,SAL_DAT027 (63).xls,8100405971,0,0.0
83608,92998,PTG,SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTI...,"TRANSPORTES FLORENCIO SILVA, LDA. -",97-LF-45,97-LF-45,12.00,107.95,-95.95,1.00,...,EUR,Rígido 24 palés,24,DIESEL,82.644,NO,SAL_DAT027 (63).xls,8100405980,0,12.0
83609,92999,AZA,SALVESEN LOGISTICA AZAMBUJA 2 / SALVESEN LOGIS...,"TRANSPORTES FLORENCIO SILVA, LDA. -",97-LF-46,97-LF-46,0.00,78.81,-78.81,1.00,...,EUR,Rígido 20 palés,20,DIESEL,99.617,NO,SAL_DAT027 (9).xls,3700661529,0,0.0

In [25]:
df['mes'] = pd.to_datetime(df['FCARGA']).dt.to_period('M')

df_transp_mes = df.groupby(['TRANSPORTISTA', 'mes']).agg({
    'COSTEDT': 'sum',
    'ingresso_total': 'sum',
    'PALETSDT': 'sum'
})

df_transp_mes['custo_palete'] = (df_transp_mes['COSTEDT'] / df_transp_mes['PALETSDT']).round(2)
df_transp_mes['ingresso_palete'] = (df_transp_mes['ingresso_total'] / df_transp_mes['PALETSDT']).round(2)

df_transp_mes = df_transp_mes[['custo_palete', 'ingresso_palete']].reset_index()

# Filtrar apenas mês 6 e 7
df_transp_mes = df_transp_mes[df_transp_mes['mes'].astype(str).isin(['2026-06', '2026-07'])]

# Pivot: mês nas colunas, custo/ingresso como sub-colunas
resultado = df_transp_mes.pivot(index='TRANSPORTISTA', columns='mes', values=['custo_palete', 'ingresso_palete'])
resultado = resultado.swaplevel(axis=1).sort_index(axis=1, level=0)

resultado

mes                                                     2026-06  \
                                                   custo_palete
TRANSPORTISTA
CMTIR TRANSPORTES NAC. INTERN. S.A                        52.06
EL MOSCA S.A.                                            -50.91
J. MARCOS FABIO E SEATLLE TRANSPORTES LDA                 39.48
JMR PRESTAÇAO DE SERVIÇOS PARA A DISTRIBUÇAO S.A           7.83
LOGISTA FREIGHT S.A.U.                                    17.58
Logislink - Terminal Logistica, Lda                      115.02
MODELO CONTINENTE HIPERMERCADOS S.A.                       8.23
MOSCA PORTUGAL LDA                                        23.27
RAMITRANS TRANSPORTES LDA                                  9.64
SALVESEN                                                    0.0
SOLIDO CLICK LDA                                          27.35
TJA-TRANSPORTES J.AMARAL, S.A.       -                    13.27
TORRESTIR - TRANSPORTES NACIONAIS E INTERNACION...        104.0
TRANSAURA TRANSPORTES LDA                                  6.26
TRANSBASE - TRANSPORTES E LOGISTICA S.A.                   7.68
TRANSPARENTODISSEIA - Transportes Unipessoal, Lda.        24.18
TRANSPORTES FIGUEIREDO & FIGUEIREDO, LDA                  45.57
TRANSPORTES FLORENCIO SILVA, LDA.  -                      14.33
TRANSPORTES PAULO COSTA & FERREIRA LDA                    22.36
TRANSPORTES ROSALIA LDA                                   14.08
Transportes Fernando Simões Monteiro Unip. Lda             40.0
WORLD RUNNERS UNIPESSOAL LDA                              10.06

mes                                                                 \
                                                   ingresso_palete
TRANSPORTISTA
CMTIR TRANSPORTES NAC. INTERN. S.A                           29.44
EL MOSCA S.A.                                                18.18
J. MARCOS FABIO E SEATLLE TRANSPORTES LDA                    21.06
JMR PRESTAÇAO DE SERVIÇOS PARA A DISTRIBUÇAO S.A             11.97
LOGISTA FREIGHT S.A.U.                                       18.18
Logislink - Terminal Logistica, Lda                         121.38
MODELO CONTINENTE HIPERMERCADOS S.A.                         13.13
MOSCA PORTUGAL LDA                                           18.18
RAMITRANS TRANSPORTES LDA                                     10.9
SALVESEN                                                      8.72
SOLIDO CLICK LDA                                             49.35
TJA-TRANSPORTES J.AMARAL, S.A.       -                       26.78
TORRESTIR - TRANSPORTES NACIONAIS E INTERNACION...           90.52
TRANSAURA TRANSPORTES LDA                                     9.94
TRANSBASE - TRANSPORTES E LOGISTICA S.A.                     25.96
TRANSPARENTODISSEIA - Transportes Unipessoal, Lda.           30.17
TRANSPORTES FIGUEIREDO & FIGUEIREDO, LDA                     50.75
TRANSPORTES FLORENCIO SILVA, LDA.  -                         10.63
TRANSPORTES PAULO COSTA & FERREIRA LDA                       26.49
TRANSPORTES ROSALIA LDA                                      26.99
Transportes Fernando Simões Monteiro Unip. Lda               14.81
WORLD RUNNERS UNIPESSOAL LDA                                  15.4

mes                                                     2026-07  \
                                                   custo_palete
TRANSPORTISTA
CMTIR TRANSPORTES NAC. INTERN. S.A                        50.45
EL MOSCA S.A.                                               NaN
J. MARCOS FABIO E SEATLLE TRANSPORTES LDA                 14.25
JMR PRESTAÇAO DE SERVIÇOS PARA A DISTRIBUÇAO S.A           8.95
LOGISTA FREIGHT S.A.U.                                      NaN
Logislink - Terminal Logistica, Lda                       79.69
MODELO CONTINENTE HIPERMERCADOS S.A.                       7.22
MOSCA PORTUGAL LDA                                        16.36
RAMITRANS TRANSPORTES LDA                                 12.66
SALVESEN                                                    0.0
SOLIDO CLICK LDA                                          17.45
TJA-TRANSPORTES J.AMARAL, S.A.       -                    14.05
TORRESTIR - TRANSPORTES NACIONAIS E INTERNACION...        99.26
TRANSAURA TRANSPORTES LDA                                  6.35
TRANSBASE - TRANSPORTES E LOGISTICA S.A.                   6.96
TRANSPARENTODISSEIA - Transportes Unipessoal, Lda.        24.15
TRANSPORTES FIGUEIREDO & FIGUEIREDO, LDA                  34.17
TRANSPORTES FLORENCIO SILVA, LDA.  -                       14.5
TRANSPORTES PAULO COSTA & FERREIRA LDA                    25.04
TRANSPORTES ROSALIA LDA                                   11.89
Transportes Fernando Simões Monteiro Unip. Lda            43.36
WORLD RUNNERS UNIPESSOAL LDA                               6.48

mes
                                                   ingresso_palete
TRANSPORTISTA
CMTIR TRANSPORTES NAC. INTERN. S.A                           24.27
EL MOSCA S.A.                                                  NaN
J. MARCOS FABIO E SEATLLE TRANSPORTES LDA                    10.84
JMR PRESTAÇAO DE SERVIÇOS PARA A DISTRIBUÇAO S.A             10.77
LOGISTA FREIGHT S.A.U.                                         NaN
Logislink - Terminal Logistica, Lda                         123.71
MODELO CONTINENTE HIPERMERCADOS S.A.                          9.88
MOSCA PORTUGAL LDA                                           18.18
RAMITRANS TRANSPORTES LDA                                    12.23
SALVESEN                                                      6.24
SOLIDO CLICK LDA                                             32.25
TJA-TRANSPORTES J.AMARAL, S.A.       -                       28.47
TORRESTIR - TRANSPORTES NACIONAIS E INTERNACION...           83.88
TRANSAURA TRANSPORTES LDA                                     8.82
TRANSBASE - TRANSPORTES E LOGISTICA S.A.                     16.51
TRANSPARENTODISSEIA - Transportes Unipessoal, Lda.            31.4
TRANSPORTES FIGUEIREDO & FIGUEIREDO, LDA                      34.1
TRANSPORTES FLORENCIO SILVA, LDA.  -                         10.39
TRANSPORTES PAULO COSTA & FERREIRA LDA                       19.67
TRANSPORTES ROSALIA LDA                                       9.14
Transportes Fernando Simões Monteiro Unip. Lda               15.57
WORLD RUNNERS UNIPESSOAL LDA                                  8.49

In [26]:
print(f"Total colunas: {df.shape[1]}")
print(f"Total linhas: {df.shape[0]}\n")

for col in df.columns:
    print(f"{col:25s} | {str(df[col].dtype):10s} | exemplo: {df[col].dropna().iloc[0] if df[col].notna().any() else 'N/A'}")

Total colunas: 62
Total linhas: 83610

id                        | int64      | exemplo: 1
PROPIETARIO               | str        | exemplo: CEP
TRAYECTO                  | str        | exemplo: SALVESEN LOGISTICA PORTUGAL / SALVESEN LOGISTICA AZAMBUJA 2 / PLAT. COOPLECNORTE,S.A. / COOPLECNORTE-OLIVEIRA BAIRRO
TRANSPORTISTA             | str        | exemplo: SOLIDO CLICK LDA
TRACTORA                  | str        | exemplo: 0000XXX
REMOLQUE                  | str        | exemplo: 0000XXX
INGRESODT                 | float64    | exemplo: 10.69
COSTEDT                   | float64    | exemplo: 4.64
RENTADT                   | float64    | exemplo: 6.05
PALETSDT                  | float64    | exemplo: 0.49
PESO_BRUTO                | float64    | exemplo: 227.26
CODEUT                    | str        | exemplo: 3344051
ESTADO_UT                 | str        | exemplo: 30
RANGO_UT                  | str        | exemplo: 1
FCARGA                    | object     | exemplo: 2025-12-29
ACTIVIDAD                 | str        | exemplo: DANONE PORTUGAL
CODEDT                    | str        | exemplo: 25387086
ESTADO_DT                 | str        | exemplo: 70
REFERENCIA                | str        | exemplo: 5021705579     413948820
CODACT                    | str        | exemplo: 011
LOCORIGEN                 | str        | exemplo: Vila Nova da Rainha
PROV_ORIGEN               | str        | exemplo: Lisboa
PAISORIGEN                | str        | exemplo: PORTUGAL
CPOSTAL                   | str        | exemplo: 2050-540
LOCDESTINO                | str        | exemplo: Oliveira do Bairro
PROV_DESTINO              | str        | exemplo: Aveiro
PAISDESTINO               | str        | exemplo: PORTUGAL
CPOSTAD                   | str        | exemplo: 3770-305
KM                        | float64    | exemplo: 700.0
FENTREGA                  | object     | exemplo: 2026-01-02
ORIGEN                    | str        | exemplo: SALVESEN LOGISTICA PORTUGAL / Danone Portugal (011)
ENTREGAR                  | str        | exemplo: PLAT. COOPLECNORTE,S.A.
PROV_ENTREGAR             | str        | exemplo: Aveiro
PAISENTREGAR              | str        | exemplo: PORTUGAL
DESTINO                   | str        | exemplo: COOPLECNORTE / Danone Portugal (011)
PALETS                    | float64    | exemplo: 1.0
PREFAC                    | str        | exemplo: GEN
RUTA                      | str        | exemplo: 1000
COBROREAL                 | str        | exemplo: 0
GESTION                   | str        | exemplo: LIS
DEPART                    | str        | exemplo: D
USCODE                    | str        | exemplo: LISANSL
USUARIO                   | str        | exemplo: Nuno Santos Lima
TIPOCLIENTE               | str        | exemplo: TLD PORTUGAL
TIPOFLUJO                 | str        | exemplo: Directo
WMSCODRGT                 | str        | exemplo: B12
LOCCAR                    | str        | exemplo: 137998
LUGARCARGA                | str        | exemplo: SALVESEN LOGISTICA PORTUGAL
LOCDES                    | str        | exemplo: 573897
LUGARDESCARGA             | str        | exemplo: PLAT. COOPLECNORTE,S.A.
TEMP_MERC_PED             | str        | exemplo: RFGRFG
TIPOPALETA                | str        | exemplo: EUR
CAMION_TIPO               | str        | exemplo: Trailer 33 plts
CAMION_CAPACIDAD          | str        | exemplo: 33
TIPO_COMBUSTIBLE          | str        | exemplo: DIESEL
KMREALES                  | float64    | exemplo: 194.134
ALBARAN                   | str        | exemplo: NO
ficheiro_origem           | str        | exemplo: SAL_DAT027 (11).xls
REFERENCIA_limpo          | str        | exemplo: 5021705579413948820
Ingreso                   | object     | exemplo: 0
ingresso_total            | object     | exemplo: 10.69
mes                       | period[M]  | exemplo: 2025-12

In [27]:
colunas_finais = [
    'PROPIETARIO', 'TRANSPORTISTA', 'TRACTORA', 'REMOLQUE',
    'INGRESODT', 'COSTEDT', 'RENTADT',
    'PESO_BRUTO', 'PALETS',
    'CODEUT', 'CODEDT',
    'FCARGA', 'FENTREGA', 'mes',
    'ACTIVIDAD', 'CODACT', 'REFERENCIA',
    'LOCORIGEN', 'PROV_ORIGEN', 'PAISORIGEN',
    'LOCDESTINO', 'PROV_DESTINO', 'PAISDESTINO',
    'ENTREGAR', 'DESTINO',
    'LOCCAR', 'LUGARCARGA', 'LOCDES', 'LUGARDESCARGA',
    'TIPOCLIENTE', 'TIPOFLUJO', 'TIPOPALETA', 'TEMP_MERC_PED',
    'CAMION_TIPO', 'CAMION_CAPACIDAD',
    'Ingreso', 'ingresso_total'
]

df_final = df[colunas_finais].copy()

print(f"Shape df_final: {df_final.shape}")
df_final.head()

Shape df_final: (83610, 37)

,PROPIETARIO,TRANSPORTISTA,TRACTORA,REMOLQUE,INGRESODT,COSTEDT,RENTADT,PESO_BRUTO,PALETS,CODEUT,...,LOCDES,LUGARDESCARGA,TIPOCLIENTE,TIPOFLUJO,TIPOPALETA,TEMP_MERC_PED,CAMION_TIPO,CAMION_CAPACIDAD,Ingreso,ingresso_total
0,CEP,SOLIDO CLICK LDA,0000XXX,0000XXX,10.69,4.64,6.05,227.26,1.0,3344051,...,573897,"PLAT. COOPLECNORTE,S.A.",TLD PORTUGAL,Directo,EUR,RFGRFG,Trailer 33 plts,33,0,10.69
1,CEP,SOLIDO CLICK LDA,0000XXX,0000XXX,125.04,236.86,-111.82,2719.88,25.0,3344051,...,573897,"PLAT. COOPLECNORTE,S.A.",TLD PORTUGAL,Directo,EUR,RFGRFG,Trailer 33 plts,33,0,125.04
2,CEP,Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,0000XXX,0.00,12.02,-12.02,487.26,1.0,3344052,...,298515,DL Transportes Fernando Simões Monteiro Unip. Lda,TLD PORTUGAL,DLS,EUR,RFGRFG,Trailer 33 plts,33,0,0.0
3,CEP,Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,0000XXX,0.00,10.82,-10.82,423.44,1.0,3344052,...,298515,DL Transportes Fernando Simões Monteiro Unip. Lda,TLD PORTUGAL,DLS,EUR,RFGRFG,Trailer 33 plts,33,0,0.0
4,CEP,Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,0000XXX,0.00,6.01,-6.01,236.29,1.0,3344052,...,298515,DL Transportes Fernando Simões Monteiro Unip. Lda,TLD PORTUGAL,DLS,EUR,RFGRFG,Trailer 33 plts,33,0,0.0

In [28]:
for col in df_final.columns:
    print(f"\n{'='*60}")
    print(f"Coluna: {col} ({df_final[col].dtype})")
    
    nulos = df_final[col].isna().sum()
    pct_nulo = (nulos / len(df_final) * 100)
    print(f"  Nulos: {nulos:,} ({pct_nulo:.2f}%)")
    
    if pd.api.types.is_numeric_dtype(df_final[col]) or pd.api.types.is_datetime64_any_dtype(df_final[col]):
        print(f"  Mínimo: {df_final[col].min()}")
        print(f"  Máximo: {df_final[col].max()}")
    else:
        print(f"  Valores únicos: {df_final[col].nunique()}")
        print(f"  Exemplo min (alfabético): {df_final[col].dropna().min() if df_final[col].notna().any() else 'N/A'}")
        print(f"  Exemplo max (alfabético): {df_final[col].dropna().max() if df_final[col].notna().any() else 'N/A'}")

============================================================
Coluna: PROPIETARIO (str)
  Nulos: 0 (0.00%)
  Valores únicos: 3
  Exemplo min (alfabético): AZA
  Exemplo max (alfabético): PTG

============================================================
Coluna: TRANSPORTISTA (str)
  Nulos: 0 (0.00%)
  Valores únicos: 27
  Exemplo min (alfabético): CMTIR TRANSPORTES NAC. INTERN. S.A
  Exemplo max (alfabético): WORLD RUNNERS UNIPESSOAL LDA

============================================================
Coluna: TRACTORA (str)
  Nulos: 1,763 (2.11%)
  Valores únicos: 259
  Exemplo min (alfabético): 00-19-XH
  Exemplo max (alfabético): vi9275

============================================================
Coluna: REMOLQUE (str)
  Nulos: 0 (0.00%)
  Valores únicos: 206
  Exemplo min (alfabético): 00-19-XH
  Exemplo max (alfabético):  L221692

============================================================
Coluna: INGRESODT (float64)
  Nulos: 0 (0.00%)
  Mínimo: 0.0
  Máximo: 1275.23

============================================================
Coluna: COSTEDT (float64)
  Nulos: 0 (0.00%)
  Mínimo: -1680.0
  Máximo: 2970.28

============================================================
Coluna: RENTADT (float64)
  Nulos: 0 (0.00%)
  Mínimo: -2970.28
  Máximo: 2280.0

============================================================
Coluna: PESO_BRUTO (float64)
  Nulos: 0 (0.00%)
  Mínimo: 0.0
  Máximo: 1355964.0

============================================================
Coluna: PALETS (float64)
  Nulos: 0 (0.00%)
  Mínimo: 0.0
  Máximo: 156.0

============================================================
Coluna: CODEUT (str)
  Nulos: 0 (0.00%)
  Valores únicos: 11696
  Exemplo min (alfabético): 3344051
  Exemplo max (alfabético): 3501530

============================================================
Coluna: CODEDT (str)
  Nulos: 0 (0.00%)
  Valores únicos: 83610
  Exemplo min (alfabético): 25245565
  Exemplo max (alfabético): 26284393

============================================================
Coluna: FCARGA (object)
  Nulos: 0 (0.00%)
  Valores únicos: 185
  Exemplo min (alfabético): 2025-12-26
  Exemplo max (alfabético): 2026-07-20

============================================================
Coluna: FENTREGA (object)
  Nulos: 0 (0.00%)
  Valores únicos: 154
  Exemplo min (alfabético): 2026-01-02
  Exemplo max (alfabético): 2026-07-22

============================================================
Coluna: mes (period[M])
  Nulos: 0 (0.00%)
  Valores únicos: 8
  Exemplo min (alfabético): 2025-12
  Exemplo max (alfabético): 2026-07

============================================================
Coluna: ACTIVIDAD (str)
  Nulos: 0 (0.00%)
  Valores únicos: 43
  Exemplo min (alfabético): ALPRO PORTUGAL
  Exemplo max (alfabético): XPO SUMOLCOMPAL

============================================================
Coluna: CODACT (str)
  Nulos: 0 (0.00%)
  Valores únicos: 43
  Exemplo min (alfabético): 011
  Exemplo max (alfabético): 784

============================================================
Coluna: REFERENCIA (str)
  Nulos: 0 (0.00%)
  Valores únicos: 71160
  Exemplo min (alfabético): "REC. VASILHAME CATERINGPOR"
  Exemplo max (alfabético):  1075387125

============================================================
Coluna: LOCORIGEN (str)
  Nulos: 4 (0.00%)
  Valores únicos: 95
  Exemplo min (alfabético): Abrunheira
  Exemplo max (alfabético): torres nova

============================================================
Coluna: PROV_ORIGEN (str)
  Nulos: 4 (0.00%)
  Valores únicos: 28
  Exemplo min (alfabético): ALBERGARIA-A-VELHA
  Exemplo max (alfabético): ÍLHAVO

============================================================
Coluna: PAISORIGEN (str)
  Nulos: 0 (0.00%)
  Valores únicos: 3
  Exemplo min (alfabético): ESPAÑA
  Exemplo max (alfabético): PORTUGAL sin AT

============================================================
Coluna: LOCDESTINO (str)
  Nulos: 11,793 (14.10%)
  Valores únicos: 473
  Exemplo min (alfabético): ALGOZ
  Exemplo max (alfabético): Óbidos (Santa Maria)

============================================================
Coluna: PROV_DESTINO (str)
  Nulos: 11,811 (14.13%)
  Valores únicos: 41
  Exemplo min (alfabético): ALBERGARIA-A-VELHA
  Exemplo max (alfabético): ÍLHAVO

============================================================
Coluna: PAISDESTINO (str)
  Nulos: 17 (0.02%)
  Valores únicos: 3
  Exemplo min (alfabético): ESPAÑA
  Exemplo max (alfabético): PORTUGAL sin AT

============================================================
Coluna: ENTREGAR (str)
  Nulos: 21 (0.03%)
  Valores únicos: 2760
  Exemplo min (alfabético): (MC INTERNATIOAL) SONAE DISTR.
  Exemplo max (alfabético): ÂNGELO AMARAL, LDA MARMEDSA

============================================================
Coluna: DESTINO (str)
  Nulos: 9,609 (11.49%)
  Valores únicos: 3513
  Exemplo min (alfabético): 4900 HAPS HUB ROW - NUTRICIA N / Nutricia (074)
  Exemplo max (alfabético): ÂNGELO AMARAL, LDA / RTM (404)

============================================================
Coluna: LOCCAR (str)
  Nulos: 0 (0.00%)
  Valores únicos: 166
  Exemplo min (alfabético): 131763
  Exemplo max (alfabético): 854795

============================================================
Coluna: LUGARCARGA (str)
  Nulos: 0 (0.00%)
  Valores únicos: 155
  Exemplo min (alfabético): AJOS JUAN DE DIOS
  Exemplo max (alfabético): cmtir porto

============================================================
Coluna: LOCDES (str)
  Nulos: 17 (0.02%)
  Valores únicos: 3179
  Exemplo min (alfabético): 131763
  Exemplo max (alfabético): 855779

============================================================
Coluna: LUGARDESCARGA (str)
  Nulos: 17 (0.02%)
  Valores únicos: 2769
  Exemplo min (alfabético): (MC INTERNATIOAL) SONAE DISTR.
  Exemplo max (alfabético): ÂNGELO AMARAL, LDA MARMEDSA

============================================================
Coluna: TIPOCLIENTE (str)
  Nulos: 54,363 (65.02%)
  Valores únicos: 4
  Exemplo min (alfabético): TLD PORTUGAL
  Exemplo max (alfabético): TLD RED/DEDICADOS

============================================================
Coluna: TIPOFLUJO (str)
  Nulos: 0 (0.00%)
  Valores únicos: 10
  Exemplo min (alfabético): DED
  Exemplo max (alfabético): Recogida

============================================================
Coluna: TIPOPALETA (str)
  Nulos: 0 (0.00%)
  Valores únicos: 1
  Exemplo min (alfabético): EUR
  Exemplo max (alfabético): EUR

============================================================
Coluna: TEMP_MERC_PED (str)
  Nulos: 0 (0.00%)
  Valores únicos: 8
  Exemplo min (alfabético): 50NPOP
  Exemplo max (alfabético): ààà

============================================================
Coluna: CAMION_TIPO (str)
  Nulos: 1 (0.00%)
  Valores únicos: 15
  Exemplo min (alfabético): Cabeza Tractora
  Exemplo max (alfabético): Trailer doble piso

============================================================
Coluna: CAMION_CAPACIDAD (str)
  Nulos: 0 (0.00%)
  Valores únicos: 14
  Exemplo min (alfabético): 0
  Exemplo max (alfabético): 8

============================================================
Coluna: Ingreso (object)
  Nulos: 0 (0.00%)
  Valores únicos: 7128
  Exemplo min (alfabético): 0
  Exemplo max (alfabético): 2166.408128334962

============================================================
Coluna: ingresso_total (object)
  Nulos: 0 (0.00%)
  Valores únicos: 13943
  Exemplo min (alfabético): 0.0
  Exemplo max (alfabético): 2209.458128334962

In [29]:
df_negativos = df_final[df_final['COSTEDT'] < 0]

print(f"Total de linhas com COSTEDT negativo: {len(df_negativos)}")

resumo_negativos = df_negativos.groupby(['TRANSPORTISTA', 'mes']).agg({
    'RENTADT': 'sum'
}).round(2)

resumo_negativos = resumo_negativos[resumo_negativos['RENTADT'] != 0].sort_values('RENTADT')

resumo_negativos

Total de linhas com COSTEDT negativo: 1

                       RENTADT
TRANSPORTISTA mes
EL MOSCA S.A. 2026-06   2280.0

In [30]:
if platform.system() == 'Windows':
    DB_PATH = r"C:\Users\LISARR\Documents\python\01.Financeiro\inform_27.db"
elif platform.system() == 'Darwin':
    DB_PATH = "/Volumes/RR/DB/inform_27.db"
else:
    DB_PATH = "inform_27.db"

con = sqlite3.connect(DB_PATH)
df_km = pd.read_sql_query("SELECT * FROM km_diario_2026", con)
con.close()

print(f"Shape df_km: {df_km.shape}")
print(f"\nColunas: {df_km.columns.tolist()}")

Shape df_km: (3874, 17)

Colunas: ['id', 'transportador', 'descricao', 'trator', 'reboque', 'data', 'dia', 'mes', 'km', 'portagens', 'preco_base', 'sub_divisao', 'tipo_contrato', 'km_gratis', 'rate_km', 'total', 'criado_em']

In [31]:
print("Exemplos TRACTORA (inform_27):")
print(df_final['TRACTORA'].dropna().unique()[:15])

print("\nExemplos trator (km_diario):")
print(df_km['trator'].dropna().unique()[:15])

print(f"\nTipo TRACTORA: {df_final['TRACTORA'].dtype}")
print(f"Tipo trator: {df_km['trator'].dtype}")

Exemplos TRACTORA (inform_27):
<ArrowStringArray>
[ '0000XXX', 'AV-35-DB', 'BB-70-RN', '18-XO-45', '18-XO-42', 'BL-98-FM',
 '97-LF-46', 'AT-41-AC', 'AT-71-MG', 'AT-30-MG', 'AZ-72-AR', 'AV-76-FC',
  'L201737', '85-ON-73', 'AV-27-DE']
Length: 15, dtype: str

Exemplos trator (km_diario):
<ArrowStringArray>
['AZ-70-DB', '83-94-XB', '85-ON-73', 'AR-59-PH', 'AV-35-DB', 'AV-27-DE',
 'AZ-72-AR', '97-LF-45', 'BM-00-RO', '97-LF-46', 'BO-91-DR', 'BL-98-FM',
 'AT-41-AC', 'BZ-32-CL', 'AS-61-IG']
Length: 15, dtype: str

Tipo TRACTORA: str
Tipo trator: str

In [33]:
# 1. Agregar duplicados de trator+data no km_diario (somar valores numéricos, manter primeiro sub_divisao)
df_km_agg = df_km.groupby(['trator', 'data'], as_index=False).agg({
    'km': 'sum',
    'portagens': 'sum',
    'preco_base': 'sum',
    'sub_divisao': 'first',
    'total': 'sum'
})

print(f"Linhas df_km antes de agregar: {len(df_km)}")
print(f"Linhas df_km após agregar duplicados: {len(df_km_agg)}")

# 2. Preparar chave de join
df_km_agg['data'] = pd.to_datetime(df_km_agg['data']).dt.date
df_final['FCARGA_date'] = pd.to_datetime(df_final['FCARGA']).dt.date

df_final['TRACTORA_limpo'] = df_final['TRACTORA'].str.strip()
df_km_agg['trator_limpo'] = df_km_agg['trator'].str.strip()

# 3. Merge (left, mantendo todas as linhas do df_final)
linhas_antes = len(df_final)

df_final = df_final.merge(
    df_km_agg[['trator_limpo', 'data', 'km', 'portagens', 'preco_base', 'sub_divisao', 'total']],
    left_on=['TRACTORA_limpo', 'FCARGA_date'],
    right_on=['trator_limpo', 'data'],
    how='left'
)

print(f"\nLinhas df_final antes do merge: {linhas_antes}")
print(f"Linhas df_final depois do merge: {len(df_final)}")

# 4. Marcar primeira ocorrência de cada combinação TRACTORA+FCARGA_date (evitar duplicar somas)
primeira_ocorrencia = ~df_final.duplicated(subset=['TRACTORA_limpo', 'FCARGA_date'])

for col in ['km', 'portagens', 'preco_base', 'total']:
    df_final[col] = df_final[col].where(primeira_ocorrencia, 0)

# 5. Limpar colunas auxiliares
df_final = df_final.drop(columns=['TRACTORA_limpo', 'trator_limpo', 'data', 'FCARGA_date'])

print(f"\nLinhas com km preenchido: {(df_final['km'] > 0).sum()} de {len(df_final)}")
print(f"Soma km (df_final): {df_final['km'].sum():,.2f}")
print(f"Soma km (df_km original): {df_km['km'].sum():,.2f}")

Linhas df_km antes de agregar: 3874
Linhas df_km após agregar duplicados: 3682

Linhas df_final antes do merge: 83610
Linhas df_final depois do merge: 83610

Linhas com km preenchido: 2147 de 83610
Soma km (df_final): 494,593.00
Soma km (df_km original): 870,581.00

In [34]:
df_final.head()

,PROPIETARIO,TRANSPORTISTA,TRACTORA,REMOLQUE,INGRESODT,COSTEDT,RENTADT,PESO_BRUTO,PALETS,CODEUT,...,TEMP_MERC_PED,CAMION_TIPO,CAMION_CAPACIDAD,Ingreso,ingresso_total,km,portagens,preco_base,sub_divisao,total
0,CEP,SOLIDO CLICK LDA,0000XXX,0000XXX,10.69,4.64,6.05,227.26,1.0,3344051,...,RFGRFG,Trailer 33 plts,33,0,10.69,NaN,NaN,NaN,NaN,NaN
1,CEP,SOLIDO CLICK LDA,0000XXX,0000XXX,125.04,236.86,-111.82,2719.88,25.0,3344051,...,RFGRFG,Trailer 33 plts,33,0,125.04,0.0,0.0,0.0,NaN,0.0
2,CEP,Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,0000XXX,0.00,12.02,-12.02,487.26,1.0,3344052,...,RFGRFG,Trailer 33 plts,33,0,0.0,NaN,NaN,NaN,NaN,NaN
3,CEP,Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,0000XXX,0.00,10.82,-10.82,423.44,1.0,3344052,...,RFGRFG,Trailer 33 plts,33,0,0.0,0.0,0.0,0.0,NaN,0.0
4,CEP,Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,0000XXX,0.00,6.01,-6.01,236.29,1.0,3344052,...,RFGRFG,Trailer 33 plts,33,0,0.0,0.0,0.0,0.0,NaN,0.0

In [35]:
duplicados = df_km[df_km.duplicated(subset=['trator', 'data'], keep=False)].sort_values(['trator', 'data'])
print(f"Total linhas duplicadas (todas as ocorrências): {len(duplicados)}")
duplicados[['trator', 'data', 'km', 'total']].head(20)

Total linhas duplicadas (todas as ocorrências): 154

        trator                 data   km  total
2551  45-HM-85  2026-05-04 00:00:00  326  234.0
2594  45-HM-85  2026-05-04 00:00:00  176  234.0
2552  45-HM-85  2026-05-05 00:00:00  187  234.0
2595  45-HM-85  2026-05-05 00:00:00  150  234.0
2553  45-HM-85  2026-05-06 00:00:00  224  234.0
2596  45-HM-85  2026-05-06 00:00:00  183  234.0
2554  45-HM-85  2026-05-07 00:00:00  233  234.0
2597  45-HM-85  2026-05-07 00:00:00  255  234.0
2556  45-HM-85  2026-05-11 00:00:00  313  234.0
2598  45-HM-85  2026-05-11 00:00:00  144  234.0
2557  45-HM-85  2026-05-12 00:00:00   93  234.0
2599  45-HM-85  2026-05-12 00:00:00  183  234.0
2558  45-HM-85  2026-05-13 00:00:00  187  234.0
2600  45-HM-85  2026-05-13 00:00:00  137  234.0
2559  45-HM-85  2026-05-14 00:00:00  282  234.0
2601  45-HM-85  2026-05-14 00:00:00  236  234.0
2560  45-HM-85  2026-05-15 00:00:00  112  234.0
2602  45-HM-85  2026-05-15 00:00:00  127  234.0
2561  45-HM-85  2026-05-18 00:00:00  223  234.0
2603  45-HM-85  2026-05-18 00:00:00  240  234.0

In [37]:
# Converter tipos de dados numéricos
df['INGRESODT'] = pd.to_numeric(df['INGRESODT'], errors='coerce')
df['COSTEDT'] = pd.to_numeric(df['COSTEDT'], errors='coerce')
df['RENTADT'] = pd.to_numeric(df['RENTADT'], errors='coerce')
df['PALETSDT'] = pd.to_numeric(df['PALETSDT'], errors='coerce')
df['PESO_BRUTO'] = pd.to_numeric(df['PESO_BRUTO'], errors='coerce')
df['PALETS'] = pd.to_numeric(df['PALETS'], errors='coerce')

# CODEUT como string
df['CODEUT'] = df['CODEUT'].astype(str)

# Trim em strings (apenas colunas efetivamente texto, evita erro com colunas date)
def trim_se_string(col):
    if col.dtype == "object" and col.apply(lambda v: isinstance(v, str) or pd.isna(v)).all():
        return col.str.strip()
    return col

df = df.apply(trim_se_string)

# Datas como datetime (sem hora, prontas para PBI) - DEPOIS do trim
df['FCARGA'] = pd.to_datetime(df['FCARGA'], format='%Y%m%d', errors='coerce').dt.date
df['FENTREGA'] = pd.to_datetime(df['FENTREGA'], format='%Y%m%d', errors='coerce').dt.date

# Colunas auxiliares ano e mês
df['ano'] = pd.to_datetime(df['FCARGA']).dt.year
df['mes_num'] = pd.to_datetime(df['FCARGA']).dt.month
df['mes'] = pd.to_datetime(df['FCARGA']).dt.to_period('M')

# Corrigir tipos numéricos que ficaram como object (Danone)
df['Ingreso'] = pd.to_numeric(df['Ingreso'], errors='coerce')
df['ingresso_total'] = pd.to_numeric(df['ingresso_total'], errors='coerce')

# Selecionar colunas finais
colunas_finais = [
    'PROPIETARIO', 'TRANSPORTISTA', 'TRACTORA', 'REMOLQUE',
    'INGRESODT', 'COSTEDT', 'RENTADT',
    'PALESREAL' if 'PALESREAL' in df.columns else 'PALETSDT', 'PESO_BRUTO', 'PALETS',
    'CODEUT', 'CODEDT',
    'FCARGA', 'FENTREGA', 'ano', 'mes_num', 'mes',
    'ACTIVIDAD', 'CODACT', 'REFERENCIA',
    'LOCORIGEN', 'PROV_ORIGEN', 'PAISORIGEN',
    'LOCDESTINO', 'PROV_DESTINO', 'PAISDESTINO',
    'ENTREGAR', 'DESTINO',
    'LOCCAR', 'LUGARCARGA', 'LOCDES', 'LUGARDESCARGA',
    'TIPOCLIENTE', 'TIPOFLUJO', 'TIPOPALETA', 'TEMP_MERC_PED',
    'CAMION_TIPO', 'CAMION_CAPACIDAD',
    'Ingreso', 'ingresso_total',
    'km', 'portagens', 'preco_base', 'sub_divisao', 'total'
]

df_final = df[[c for c in colunas_finais if c in df.columns]].copy()

print(f"Shape df_final: {df_final.shape}")
print(f"\nTipos de dados:")
print(df_final.dtypes)
print(f"\nNulos por coluna:")
print(df_final.isna().sum()[df_final.isna().sum() > 0])

Shape df_final: (83610, 40)

Tipos de dados:
PROPIETARIO               str
TRANSPORTISTA             str
TRACTORA                  str
REMOLQUE                  str
INGRESODT             float64
COSTEDT               float64
RENTADT               float64
PALETSDT              float64
PESO_BRUTO            float64
PALETS                float64
CODEUT                    str
CODEDT                    str
FCARGA                 object
FENTREGA               object
ano                     int32
mes_num                 int32
mes                 period[M]
ACTIVIDAD                 str
CODACT                    str
REFERENCIA                str
LOCORIGEN                 str
PROV_ORIGEN               str
PAISORIGEN                str
LOCDESTINO                str
PROV_DESTINO              str
PAISDESTINO               str
ENTREGAR                  str
DESTINO                   str
LOCCAR                    str
LUGARCARGA                str
LOCDES                    str
LUGARDESCARGA             str
TIPOCLIENTE               str
TIPOFLUJO                 str
TIPOPALETA                str
TEMP_MERC_PED             str
CAMION_TIPO               str
CAMION_CAPACIDAD          str
Ingreso               float64
ingresso_total        float64
dtype: object

Nulos por coluna:
TRACTORA          1763
LOCORIGEN            4
PROV_ORIGEN          4
LOCDESTINO       11793
PROV_DESTINO     11811
PAISDESTINO         17
ENTREGAR            21
DESTINO           9609
LOCDES              17
LUGARDESCARGA       17
TIPOCLIENTE      54363
CAMION_TIPO          1
dtype: int64

In [38]:
caminho_parquet = r"C:\Users\LISARR\Documents\python\01.Financeiro\inform_27_2026_final.parquet"

df_final.to_parquet(caminho_parquet, index=False)

print(f"Ficheiro exportado para: {caminho_parquet}")
print(f"Linhas: {len(df_final):,}")
print(f"Colunas: {df_final.shape[1]}")

Ficheiro exportado para: C:\Users\LISARR\Documents\python\01.Financeiro\inform_27_2026_final.parquet
Linhas: 83,610
Colunas: 40