In [ ]:
# ==========================
# 1. Imports
# ==========================
from pathlib import Path
import platform

import duckdb
import pandas as pd

# ==========================
# 1. Import
# ==========================
import numpy as np


# ==========================
# 2. Parâmetros
# ==========================
GESTAO = "LIS"

ANOS = [
    2025,
    2026,
]


# ==========================
# 3. Pasta das bases
# ==========================
def get_db_dir():

    sistema = platform.system()

    if sistema == "Windows":
        return Path(
            r"C:\Users\LISARR\OneDrive - Salvesen Logística S.A\python\00.DB"
        )

    if sistema == "Darwin":
        return Path(
            "/Users/rr/Library/Mobile Documents/"
            "com~apple~CloudDocs/05.Salvesen/00_DB"
        )

    return Path.cwd()


DB_DIR = get_db_dir()


# ==========================
# 4. Caminhos
# ==========================
PATHS = {
    ano: DB_DIR / f"{ano}.duckdb"
    for ano in ANOS
}


# ==========================
# 5. Validar bases
# ==========================
for ano, path in PATHS.items():

    if not path.exists():
        raise FileNotFoundError(
            f"Base {ano} não encontrada: {path}"
        )


# ==========================
# 6. Ligações DuckDB
# ==========================
CON = {
    ano: duckdb.connect(
        str(PATHS[ano]),
        read_only=True
    )
    for ano in ANOS
}


# ==========================
# 7. Validar
# ==========================
validacao = pd.DataFrame({
    "Ano": ANOS,
    "Base": [
        PATHS[ano].name
        for ano in ANOS
    ],
    "Tabelas": [
        len(CON[ano].sql("SHOW TABLES").fetchall())
        for ano in ANOS
    ],
})

validacao

    Ano         Base  Tabelas
0  2025  2025.duckdb        8
1  2026  2026.duckdb       11

In [ ]:
# ==========================
# 8. Ler dados das bases
# ==========================

df = pd.concat(
    [
        CON[ano].execute(
            f"""
            SELECT *
            FROM inform_27_{ano}
            WHERE Gestion = ?
            """,
            [GESTAO]
        ).df().assign(ANO=ano)
        for ano in ANOS
    ],
    ignore_index=True
)

print(f"Linhas: {df.shape[0]:,}")
print(f"Colunas: {df.shape[1]}")

display(df.head())

Linhas: 238,314
Colunas: 59

,id,PROPIETARIO,TRAYECTO,TRANSPORTISTA,TRACTORA,REMOLQUE,INGRESODT,COSTEDT,RENTADT,PALETSDT,...,LUGARDESCARGA,TEMP_MERC_PED,TIPOPALETA,CAMION_TIPO,CAMION_CAPACIDAD,TIPO_COMBUSTIBLE,KMREALES,ALBARAN,ficheiro_origem,ANO
0,46355,PTG,DL Transportes Fernando Simões Monteiro Unip. ...,Transportes Fernando Simões Monteiro Unip. Lda,0000XXX,0000XXX,11.82,11.25,0.57,0.31,...,AUCHAN VISEU,TAM,EUR,Trailer 33 plts,33,DIESEL,135.191,NO,SAL_DAT027_2025_01_07.xls,2025
1,46356,PTG,SALVESEN LOGISTICA PORTUGAL / CARMONTI-IND.CAR...,Transportes Fernando Simões Monteiro Unip. Lda,93-QI-75,L153182,11.82,2.8,9.02,0.31,...,DL Transportes Fernando Simões Monteiro Unip. Lda,TAM,EUR,Trailer 33 plts,33,DIESEL,151.803,NO,SAL_DAT027_2025_01_07.xls,2025
2,46357,PTG,SALVESEN LOGISTICA PORTUGAL / CARMONTI-IND.CAR...,Transportes Fernando Simões Monteiro Unip. Lda,93-QI-75,L153182,0,0.27,-0.27,0.03,...,DL Transportes Fernando Simões Monteiro Unip. Lda,RFGRFG,EUR,Trailer 33 plts,33,DIESEL,151.803,NO,SAL_DAT027_2025_01_07.xls,2025
3,46358,PTG,SALVESEN LOGISTICA PORTUGAL / CARMONTI-IND.CAR...,Transportes Fernando Simões Monteiro Unip. Lda,93-QI-75,L153182,11.02,18.07,-7.06,2,...,DL Transportes Fernando Simões Monteiro Unip. Lda,RFGRFG,EUR,Trailer 33 plts,33,DIESEL,151.803,NO,SAL_DAT027_2025_01_07.xls,2025
4,46359,CEP,SALVESEN LOGISTICA PORTUGAL / CARMONTI-IND.CAR...,Transportes Fernando Simões Monteiro Unip. Lda,93-QI-75,L153182,24.36,9.04,15.32,1,...,DL Transportes Fernando Simões Monteiro Unip. Lda,RFGRFG,EUR,Trailer 33 plts,33,DIESEL,151.803,NO,SAL_DAT027_2025_01_07.xls,2025

In [ ]:
# ==========================
# 9. Paletes por cliente e distrito
# ==========================

import unicodedata
import pandas as pd

# ==========================
# 1. Parâmetros
# ==========================

MES = 8  # Agosto (1 a 12)

# Utiliza ANOS, GESTAO e CON já definidos anteriormente


# ==========================
# 2. Distritos
# ==========================

distritos = [
    "Aveiro",
    "Beja",
    "Braga",
    "Bragança",
    "Castelo Branco",
    "Coimbra",
    "Évora",
    "Faro",
    "Guarda",
    "Leiria",
    "Lisboa",
    "Portalegre",
    "Porto",
    "Santarém",
    "Setúbal",
    "Viana do Castelo",
    "Vila Real",
    "Viseu"
]


# ==========================
# 3. Mapeamento
# ==========================

grupos = {
    "Aveiro": [
        "Aveiro", "Albergaria-a-Velha", "Anadia",
        "Arouca", "Espinho", "Estarreja",
        "Mealhada", "Murtosa", "Oliveira de Azeméis",
        "Oliveira do Bairro", "Ovar",
        "Santa Maria da Feira", "Sever do Vouga",
        "São João da Madeira", "Vale de Cambra",
        "Águeda", "Ílhavo"
    ],
    "Beja": ["Beja", "Castro Verde"],
    "Braga": ["Braga"],
    "Bragança": ["Bragança"],
    "Castelo Branco": ["Castelo Branco"],
    "Coimbra": ["Coimbra"],
    "Évora": ["Évora"],
    "Faro": ["Faro"],
    "Guarda": ["Guarda"],
    "Leiria": ["Leiria"],
    "Lisboa": ["Lisboa"],
    "Portalegre": ["Portalegre"],
    "Porto": ["Porto"],
    "Santarém": ["Santarém", "Ourém"],
    "Setúbal": ["Setúbal"],
    "Viana do Castelo": ["Viana do Castelo"],
    "Vila Real": ["Vila Real"],
    "Viseu": ["Viseu"]
}


# ==========================
# 4. Normalização de texto
# ==========================

def normalizar(texto):
    if pd.isna(texto):
        return ""

    texto = unicodedata.normalize(
        "NFKD", str(texto).strip()
    )

    return "".join(
        c for c in texto
        if not unicodedata.combining(c)
    ).upper()


mapa = {
    normalizar(localidade): distrito
    for distrito, localidades in grupos.items()
    for localidade in localidades
}


# ==========================
# 5. Ler dados - Agosto 2026
# ==========================

ANO = 2026
MES = 8

dados = CON[ANO].execute(
    f"""
    SELECT
        CODACT,
        ACTIVIDAD,
        PROV_DESTINO,
        PALETS
    FROM inform_27_{ANO}
    WHERE Gestion = ?
      AND SUBSTR(TRIM(CAST(FENTREGA AS VARCHAR)), 1, 6) = ?
    """,
    [GESTAO, f"{ANO}{MES:02d}"]
).df()

dados["ANO"] = ANO


# ==========================
# 6. Preparar dados
# ==========================

dados["CODACT"] = (
    dados["CODACT"]
    .astype("string")
    .str.strip()
    .str.zfill(3)
)

dados["PALETS"] = pd.to_numeric(
    dados["PALETS"]
    .astype("string")
    .str.replace(",", ".", regex=False),
    errors="coerce"
)

dados["DISTRITO"] = (
    dados["PROV_DESTINO"]
    .map(normalizar)
    .map(mapa)
)


# ==========================
# 7. Validar não mapeados
# ==========================

nao_mapeadas = (
    dados[dados["DISTRITO"].isna()]
    .groupby(
        ["ANO", "PROV_DESTINO"],
        dropna=False
    )["PALETS"]
    .sum()
    .reset_index()
)


# ==========================
# 8. Tabela dinâmica
# ==========================

df_volumes = pd.pivot_table(
    dados[dados["DISTRITO"].notna()],
    index=["ANO", "CODACT", "ACTIVIDAD"],
    columns="DISTRITO",
    values="PALETS",
    aggfunc="sum",
    fill_value=0
)

# Garantir as 18 colunas
df_volumes = df_volumes.reindex(
    columns=distritos,
    fill_value=0
)

# Total por cliente
df_volumes["TOTAL"] = df_volumes[distritos].sum(axis=1)

df_volumes = df_volumes.reset_index()
df_volumes.columns.name = None


# ==========================
# 9. Resultados
# ==========================

print(f"Mês analisado: {MES:02d}")
print(f"Anos: {ANOS}")
print(f"Registos analisados: {len(dados):,}")

print("\nPALETES POR CLIENTE E DISTRITO")

display(df_volumes)

print("\nPROVÍNCIAS NÃO MAPEADAS")

display(nao_mapeadas)

Mês analisado: 08
Anos: [2025, 2026]
Registos analisados: 16,301

PALETES POR CLIENTE E DISTRITO

,ANO,CODACT,ACTIVIDAD,Aveiro,Beja,Braga,Bragança,Castelo Branco,Coimbra,Évora,...,Leiria,Lisboa,Portalegre,Porto,Santarém,Setúbal,Viana do Castelo,Vila Real,Viseu,TOTAL
0,2026,011,DANONE PORTUGAL,405.0,41.0,122.0,81.0,84.0,102.0,5.0,...,50.0,8302.0,17.0,7079.0,668.0,377.0,70.0,1.0,0.0,18324.0
1,2026,013,DANONE PORTUGAL CAPILAR,271.0,2.0,259.0,0.0,0.0,41.0,0.0,...,42.0,118.0,0.0,270.0,34.0,62.0,4.0,0.0,12.0,1120.0
2,2026,015,TROPICANA,8.0,0.0,0.0,0.0,0.0,10.0,0.0,...,0.0,123.0,0.0,51.0,6.0,0.0,0.0,0.0,0.0,216.0
3,2026,028,PLN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,4.0,0.0,21.0,0.0,0.0,0.0,0.0,0.0,25.0
4,2026,074,NUTRICIA,160.0,41.0,196.0,26.0,36.0,251.0,22.0,...,43.0,1336.0,5.0,1418.0,154.0,130.0,41.0,27.0,38.0,4128.0
5,2026,084,DANONE PORTUGAL TLD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,528.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,528.0
6,2026,116,ORANGINA SCHWEPPES ESPAÑA BASE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0
7,2026,117,ORANGINA SCHWEPPES,28.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,26.0,0.0,11.0,0.0,21.0,0.0,0.0,0.0,159.0
8,2026,118,ORANGNA SCHWEPPES PORTUGAL,48.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,234.0,0.0,176.0,66.0,35.0,0.0,0.0,0.0,577.0
9,2026,131,RANA,0.0,0.0,0.0,0.0,0.0,14.0,0.0,...,0.0,663.0,0.0,338.0,88.0,32.0,0.0,0.0,0.0,1219.0
10,2026,211,VERDIFRESH,0.0,0.0,35.0,0.0,0.0,0.0,0.0,...,0.0,431.5,0.0,131.0,219.0,377.0,0.0,0.0,0.0,1193.5
11,2026,260,ANDROS REFRIGERADO,40.0,0.0,2.0,0.0,0.0,12.0,0.0,...,0.0,965.0,0.0,754.0,65.0,0.0,0.0,0.0,0.0,2005.0
12,2026,262,DF LOGISTICA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,52.0,0.0,28.0,0.0,1.0,0.0,0.0,0.0,92.0
13,2026,269,EHRMANN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0
14,2026,275,MANUEL PATRICIO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,841.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,842.0
15,2026,278,TRANSPORTES FIGUEIREDO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,166.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,166.0
16,2026,280,SIMPLES & FRESCAS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,416.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,416.0
17,2026,282,VIDARA,13.0,0.0,0.0,0.0,0.0,2.0,0.0,...,0.0,10.0,0.0,13.0,0.0,0.0,6.0,6.0,0.0,50.0
18,2026,287,SUPREME FRUITS,3.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,335.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,362.0
19,2026,311,ALPRO PORTUGAL,186.0,14.0,136.0,3.0,11.0,191.0,0.0,...,50.0,1059.0,4.0,1333.0,134.0,367.0,80.0,0.0,31.0,3942.0
20,2026,332,JERVIS,11.0,0.0,8.0,0.0,0.0,15.0,0.0,...,1.0,70.0,2.0,70.0,29.0,3.0,0.0,3.0,2.0,320.0
21,2026,338,ARIAS STOCK,33.0,0.0,1.0,0.0,0.0,4.0,0.0,...,3.0,164.0,0.0,133.0,33.0,1.0,1.0,0.0,0.0,425.0
22,2026,391,GL IMPORTAÇÃO E EXPORTAÇÃO,16.0,0.0,0.0,0.0,0.0,3.0,5.0,...,0.0,624.0,0.0,156.0,185.0,118.0,0.0,0.0,0.0,1107.0
23,2026,398,CONFEITARIA CARLOS GONÇALVES LDA,5.0,0.0,3.0,0.0,0.0,12.0,0.0,...,0.0,902.0,0.0,211.0,13.0,4.0,0.0,0.0,0.0,1188.0
24,2026,403,CARMONTI,1.0,0.0,0.0,0.0,2.0,8.0,0.0,...,3.0,579.0,0.0,105.0,67.0,32.0,6.0,0.0,3.0,810.0
25,2026,404,RTM,11.0,2.0,8.0,2.0,0.0,25.0,4.0,...,19.0,1088.0,7.0,52.0,2.0,13.0,6.0,18.0,15.0,1509.0
26,2026,405,LACTACORES,0.0,0.0,0.0,0.0,0.0,160.0,0.0,...,9.0,756.0,0.0,72.0,12.0,25.0,0.0,0.0,0.0,1038.0
27,2026,407,NUVIFRUITS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,768.0,0.0,79.0,4.0,21.0,0.0,0.0,0.0,878.0
28,2026,413,ARCADIE,21.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,45.0
29,2026,415,LOUROFOODS,9.0,0.0,55.0,5.0,6.0,4.0,1.0,...,9.0,836.0,0.0,13.0,45.0,11.0,1.0,3.0,0.0,1066.0
30,2026,418,AUCHAN TLD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,693.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,693.0
31,2026,419,BON NATURA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,293.0,0.0,180.0,318.0,74.0,0.0,0.0,0.0,865.0
32,2026,429,H-3 Carnes,40.0,0.0,61.0,0.0,0.0,83.0,0.0,...,38.0,665.0,0.0,543.0,13.0,57.0,12.0,14.0,22.0,1778.0
33,2026,490,PATATAS MELÉNDEZ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,84.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,84.0
34,2026,491,JMR,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,693.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,693.0
35,2026,539,TRANSPARENTEODISSEIA,8.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,7.0,0.0,34.0,41.0,32.0,0.0,0.0,0.0,124.0
36,2026,546,QUINTA DOS FUMEIROS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2.0
37,2026,560,MODELO CONTINENTE HIPERMERCADOS,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
38,2026,562,COCONUT.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0
39,2026,588,RENOVA-FABRICA DE PAPEL DE ALMONDA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,264.0,0.0,0.0,0.0,264.0
40,2026,660,ANDROS PTG SECO,15.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,63.0,0.0,67.0,0.0,19.0,0.0,0.0,0.0,188.0
41,2026,680,XPO SUMOLCOMPAL,9.0,21.0,2.0,0.0,24.0,36.0,0.0,...,8.0,195.0,16.0,80.0,3.0,8.0,0.0,4.0,6.0,449.0
42,2026,757,SUMOLCOMPAL MARKETING,5.0,1.0,4.0,1.0,1.0,14.0,0.0,...,8.0,3.0,2.0,68.0,70.0,1.0,1.0,2.0,3.0,190.0
43,2026,784,SABORES DO VEZ,7.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,16.0,0.0,8.0,0.0,0.0,1.0,0.0,1.0,36.0
44,2026,AAB,LAS LAGUNAS DE SANCHONUÑO (HUERCASA),0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,46.0,87.0,0.0,52.0,0.0,10.0,0.0,0.0,0.0,222.0

PROVÍNCIAS NÃO MAPEADAS

    ANO PROV_DESTINO  PALETS
0  2026                631.0
1  2026       AÇORES    27.0
2  2026       Madrid   732.0
3  2026          NaN  1512.5

In [ ]:
from pathlib import Path

ficheiro = Path.home() / "Documents" / "Paletes_Distritos_Agosto_2026.xlsx"

df_volumes.to_excel(ficheiro, index=False)

print(f"Excel exportado: {ficheiro}")

Excel exportado: C:\Users\LISARR\Documents\Paletes_Distritos_Agosto_2026.xlsx

In [ ]:
# ==========================
# 10. Ingressos por cliente e distrito
# Agosto 2026
# ==========================

ANO = 2026
MES = 8

# 1. Ler dados
dados_ingresso = CON[ANO].execute(
    f"""
    SELECT
        CODACT,
        ACTIVIDAD,
        PROV_DESTINO,
        INGRESODT
    FROM inform_27_{ANO}
    WHERE Gestion = ?
      AND SUBSTR(TRIM(CAST(FENTREGA AS VARCHAR)), 1, 6) = ?
    """,
    [GESTAO, f"{ANO}{MES:02d}"]
).df()

# 2. Preparar dados
dados_ingresso["CODACT"] = (
    dados_ingresso["CODACT"]
    .astype("string")
    .str.strip()
    .str.zfill(3)
)

dados_ingresso["INGRESODT"] = pd.to_numeric(
    dados_ingresso["INGRESODT"]
    .astype("string")
    .str.replace(",", ".", regex=False),
    errors="coerce"
)

# 3. Normalizar distritos
# Reutiliza 'normalizar', 'mapa' e 'distritos'
# definidos na célula anterior

dados_ingresso["DISTRITO"] = (
    dados_ingresso["PROV_DESTINO"]
    .map(normalizar)
    .map(mapa)
)

# 4. Tabela dinâmica
df_ingressos = pd.pivot_table(
    dados_ingresso[dados_ingresso["DISTRITO"].notna()],
    index=["CODACT", "ACTIVIDAD"],
    columns="DISTRITO",
    values="INGRESODT",
    aggfunc="sum",
    fill_value=0
)

# Garantir os 18 distritos
df_ingressos = df_ingressos.reindex(
    columns=distritos,
    fill_value=0
)

# Total por cliente
df_ingressos["TOTAL"] = df_ingressos[distritos].sum(axis=1)

df_ingressos = df_ingressos.reset_index()
df_ingressos.columns.name = None

# Arredondar valores
df_ingressos[distritos + ["TOTAL"]] = (
    df_ingressos[distritos + ["TOTAL"]].round(2)
)

# 5. Validar províncias não mapeadas
nao_mapeadas_ingresso = (
    dados_ingresso[dados_ingresso["DISTRITO"].isna()]
    .groupby("PROV_DESTINO", dropna=False)["INGRESODT"]
    .sum()
    .reset_index()
)

# 6. Visualizar
display(df_ingressos)

print("Províncias não mapeadas:")
display(nao_mapeadas_ingresso)

# 7. Exportar para Excel
ficheiro = (
    Path.home()
    / "Documents"
    / "Ingressos_Distritos_Agosto_2026.xlsx"
)

df_ingressos.to_excel(ficheiro, index=False)

print(f"Excel exportado: {ficheiro}")

,CODACT,ACTIVIDAD,Aveiro,Beja,Braga,Bragança,Castelo Branco,Coimbra,Évora,Faro,...,Leiria,Lisboa,Portalegre,Porto,Santarém,Setúbal,Viana do Castelo,Vila Real,Viseu,TOTAL
0,011,DANONE PORTUGAL,1703.28,2435.78,514.16,938.99,1240.66,0.0,0.0,11747.8,...,737.79,18758.36,1048.75,26677.37,9212.75,5694.69,423.92,0.0,0.0,81134.3
1,013,DANONE PORTUGAL CAPILAR,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,015,TROPICANA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,028,PLN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,171.14,0.0,0.0,0.0,0.0,0.0,171.14
4,074,NUTRICIA,1248.98,697.86,1732.7,703.6,678.65,2785.07,548.36,3621.37,...,770.73,15164.11,112.2,16384.54,3633.38,1850.09,397.8,452.49,548.82,51825.87
5,084,DANONE PORTUGAL TLD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2271.52,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2271.52
6,116,ORANGINA SCHWEPPES ESPAÑA BASE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,117,ORANGINA SCHWEPPES,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,118,ORANGNA SCHWEPPES PORTUGAL,3236.96,0.0,0.0,0.0,0.0,0.0,0.0,1088.47,...,0.0,8752.17,0.0,10168.5,2936.81,1239.59,0.0,0.0,0.0,27422.5
9,131,RANA,0.0,0.0,0.0,0.0,0.0,169.12,0.0,2283.07,...,0.0,7383.15,0.0,7451.52,1516.76,1035.19,0.0,0.0,0.0,19838.81
10,211,VERDIFRESH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,260,ANDROS REFRIGERADO,755.98,0.0,37.8,0.0,0.0,172.08,0.0,4616.84,...,0.0,5505.67,0.0,15065.8,938.38,0.0,0.0,0.0,0.0,27092.55
12,262,DF LOGISTICA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,401.61,...,0.0,511.0,0.0,706.92,0.0,20.44,0.0,0.0,0.0,1639.97
13,269,EHRMANN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,275,MANUEL PATRICIO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3755.07,0.0,0.0,0.0,19.09,0.0,0.0,0.0,3774.16
15,278,TRANSPORTES FIGUEIREDO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,838.25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,838.25
16,280,SIMPLES & FRESCAS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,5222.44,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5222.44
17,282,VIDARA,377.99,0.0,0.0,0.0,0.0,28.54,0.0,0.0,...,0.0,220.9,0.0,243.85,0.0,0.0,69.39,153.83,0.0,1094.5
18,287,SUPREME FRUITS,57.15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,4407.67,0.0,0.0,0.0,528.72,0.0,0.0,0.0,4993.54
19,311,ALPRO PORTUGAL,169.38,198.22,441.18,72.51,398.69,0.0,0.0,1466.89,...,53.98,4294.81,61.28,12296.67,1153.88,1433.2,279.44,0.0,0.0,22320.13
20,332,JERVIS,145.59,0.0,122.52,0.0,0.0,220.22,0.0,1012.06,...,15.03,791.05,222.0,1376.71,605.73,31.89,0.0,36.03,24.02,4602.85
21,338,ARIAS STOCK,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,391,GL IMPORTAÇÃO E EXPORTAÇÃO,307.16,0.0,0.0,0.0,0.0,121.05,201.75,0.0,...,0.0,1912.09,0.0,4639.26,3470.16,2261.5,0.0,0.0,0.0,12912.97
23,398,CONFEITARIA CARLOS GONÇALVES LDA,102.3,0.0,51.15,0.0,0.0,101.68,0.0,923.46,...,0.0,2008.23,0.0,3926.21,234.26,58.2,0.0,0.0,0.0,7619.89
24,403,CARMONTI,18.15,0.0,0.0,0.0,103.22,198.9,0.0,0.0,...,95.79,1829.55,0.0,2757.29,1603.66,573.08,151.56,0.0,82.35,7511.95
25,404,RTM,285.0,102.32,149.16,59.1,0.0,405.0,166.5,6991.48,...,407.69,2509.41,329.89,1002.32,47.24,439.84,114.11,387.98,228.06,13625.1
26,405,LACTACORES,0.0,0.0,0.0,0.0,0.0,2823.26,0.0,54.84,...,254.23,3379.68,0.0,1205.88,427.38,842.95,0.0,0.0,0.0,8988.22
27,407,NUVIFRUITS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.4,...,0.0,5326.26,0.0,1751.19,99.82,467.83,0.0,0.0,0.0,7685.5
28,413,ARCADIE,1850.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2114.4,0.0,0.0,0.0,0.0,3964.5
29,415,LOUROFOODS,257.81,0.0,1506.79,180.65,325.8,58.36,62.94,1924.29,...,148.14,13596.53,0.0,323.33,875.01,357.2,30.64,66.62,0.0,19714.11
30,418,AUCHAN TLD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3359.79,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3359.79
31,419,BON NATURA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,472.92,0.0,3505.74,3817.49,1118.87,0.0,0.0,0.0,8915.02
32,429,H-3 Carnes,1558.01,0.0,2530.59,0.0,0.0,5107.15,0.0,11313.52,...,4141.13,2143.68,0.0,24074.0,1356.19,4995.23,402.44,787.96,1728.22,60138.12
33,490,PATATAS MELÉNDEZ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,491,JMR,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2215.92,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2215.92
35,539,TRANSPARENTEODISSEIA,233.24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,119.28,0.0,818.18,727.27,672.33,0.0,0.0,0.0,2570.3
36,546,QUINTA DOS FUMEIROS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,560,MODELO CONTINENTE HIPERMERCADOS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38,562,COCONUT.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,588,RENOVA-FABRICA DE PAPEL DE ALMONDA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1848.48,0.0,0.0,0.0,1848.48
40,660,ANDROS PTG SECO,259.65,0.0,0.0,0.0,0.0,0.0,0.0,400.48,...,0.0,577.64,0.0,1325.68,0.0,357.33,0.0,0.0,0.0,2920.78
41,680,XPO SUMOLCOMPAL,71.07,235.95,18.22,0.0,1274.31,325.63,0.0,490.9,...,116.39,3934.99,682.61,990.7,35.29,200.25,0.0,97.88,88.16,8562.35
42,757,SUMOLCOMPAL MARKETING,98.47,33.0,38.6,21.95,38.54,119.09,0.0,83.96,...,96.32,31.45,60.65,753.5,924.67,14.24,22.06,24.6,15.43,2376.53
43,784,SABORES DO VEZ,300.89,0.0,0.0,0.0,0.0,58.71,0.0,0.0,...,0.0,268.08,0.0,235.94,0.0,0.0,29.87,0.0,69.17,962.66
44,AAB,LAS LAGUNAS DE SANCHONUÑO (HUERCASA),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Províncias não mapeadas:

  PROV_DESTINO  INGRESODT
0                  348.59
1       AÇORES    2095.88
2       Madrid    13200.0
3          NaN     547.23

Excel exportado: C:\Users\LISARR\Documents\Ingressos_Distritos_Agosto_2026.xlsx

In [ ]:
# ==========================
# 11. Custos por cliente e distrito
# Agosto 2026
# ==========================

ANO = 2026
MES = 8

# 1. Ler dados
dados_custo = CON[ANO].execute(
    f"""
    SELECT
        CODACT,
        ACTIVIDAD,
        PROV_DESTINO,
        COSTEDT
    FROM inform_27_{ANO}
    WHERE Gestion = ?
      AND SUBSTR(TRIM(CAST(FENTREGA AS VARCHAR)), 1, 6) = ?
    """,
    [GESTAO, f"{ANO}{MES:02d}"]
).df()

# 2. Preparar dados
dados_custo["CODACT"] = (
    dados_custo["CODACT"]
    .astype("string")
    .str.strip()
    .str.zfill(3)
)

dados_custo["COSTEDT"] = pd.to_numeric(
    dados_custo["COSTEDT"]
    .astype("string")
    .str.replace(",", ".", regex=False),
    errors="coerce"
)

# 3. Normalizar distritos
# Reutiliza 'normalizar', 'mapa' e 'distritos'
# definidos anteriormente

dados_custo["DISTRITO"] = (
    dados_custo["PROV_DESTINO"]
    .map(normalizar)
    .map(mapa)
)

# 4. Tabela dinâmica
df_custos = pd.pivot_table(
    dados_custo[dados_custo["DISTRITO"].notna()],
    index=["CODACT", "ACTIVIDAD"],
    columns="DISTRITO",
    values="COSTEDT",
    aggfunc="sum",
    fill_value=0
)

# Garantir os 18 distritos
df_custos = df_custos.reindex(
    columns=distritos,
    fill_value=0
)

# Total por cliente
df_custos["TOTAL"] = df_custos[distritos].sum(axis=1)

df_custos = df_custos.reset_index()
df_custos.columns.name = None

# Arredondar valores
df_custos[distritos + ["TOTAL"]] = (
    df_custos[distritos + ["TOTAL"]].round(2)
)

# 5. Validar províncias não mapeadas
nao_mapeadas_custo = (
    dados_custo[dados_custo["DISTRITO"].isna()]
    .groupby("PROV_DESTINO", dropna=False)["COSTEDT"]
    .sum()
    .reset_index()
)

# 6. Visualizar
display(df_custos)

print("Províncias não mapeadas:")
display(nao_mapeadas_custo)

# 7. Exportar para Excel
ficheiro = (
    Path.home()
    / "Documents"
    / "Custos_Distritos_Agosto_2026.xlsx"
)

df_custos.to_excel(ficheiro, index=False)

print(f"Excel exportado: {ficheiro}")

,CODACT,ACTIVIDAD,Aveiro,Beja,Braga,Bragança,Castelo Branco,Coimbra,Évora,Faro,...,Leiria,Lisboa,Portalegre,Porto,Santarém,Setúbal,Viana do Castelo,Vila Real,Viseu,TOTAL
0,011,DANONE PORTUGAL,7994.09,2251.39,5042.91,2982.41,2863.85,450.64,6.72,16946.35,...,1618.37,29835.64,930.37,71518.06,8917.65,5315.53,2831.57,20.27,0.0,159525.82
1,013,DANONE PORTUGAL CAPILAR,5335.44,22.69,6228.1,0.0,0.0,398.28,0.0,3.34,...,487.12,2331.77,0.0,5098.01,452.2,1583.98,177.1,0.0,109.54,22359.52
2,015,TROPICANA,398.7,0.0,0.0,0.0,0.0,154.83,0.0,434.53,...,0.0,1577.93,0.0,849.83,60.69,0.0,0.0,0.0,0.0,3476.51
3,028,PLN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,255.52,0.0,353.81,0.0,0.0,0.0,0.0,0.0,609.33
4,074,NUTRICIA,2126.99,1027.4,3058.63,574.6,457.96,2725.62,320.32,1984.67,...,596.84,13646.08,85.22,19082.72,1949.7,2512.49,463.39,527.81,550.07,51977.48
5,084,DANONE PORTUGAL TLD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2700.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2700.0
6,116,ORANGINA SCHWEPPES ESPAÑA BASE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,54.51,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.51
7,117,ORANGINA SCHWEPPES,302.16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1253.27,0.0,179.26,0.0,236.31,0.0,0.0,0.0,3540.34
8,118,ORANGNA SCHWEPPES PORTUGAL,1003.9,0.0,0.0,0.0,0.0,0.0,0.0,256.05,...,0.0,2140.45,0.0,2663.27,1220.37,379.04,0.0,0.0,0.0,7663.08
9,131,RANA,0.0,0.0,0.0,0.0,0.0,4.15,0.0,1326.25,...,0.0,4220.15,0.0,3370.18,1080.48,817.61,0.0,0.0,0.0,10818.82
10,211,VERDIFRESH,0.0,0.0,1353.28,0.0,0.0,0.0,0.0,0.0,...,0.0,4883.07,0.0,4173.29,3460.34,8730.66,0.0,0.0,0.0,22600.64
11,260,ANDROS REFRIGERADO,335.89,0.0,2.17,0.0,0.0,3.41,0.0,3319.92,...,0.0,4427.81,0.0,9987.24,396.07,0.0,0.0,0.0,0.0,18472.51
12,262,DF LOGISTICA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,165.23,...,0.0,118.99,0.0,436.4,0.0,15.71,0.0,0.0,0.0,736.33
13,269,EHRMANN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,275,MANUEL PATRICIO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,431.9,0.0,0.0,0.0,25.0,0.0,0.0,0.0,456.9
15,278,TRANSPORTES FIGUEIREDO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,280,SIMPLES & FRESCAS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3188.27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3188.27
17,282,VIDARA,480.67,0.0,0.0,0.0,0.0,7.61,0.0,0.0,...,0.0,395.84,0.0,389.28,0.0,0.0,267.86,344.07,0.0,1885.33
18,287,SUPREME FRUITS,2.83,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3212.81,0.0,0.0,0.0,451.28,0.0,0.0,0.0,3666.92
19,311,ALPRO PORTUGAL,1501.18,368.7,740.74,68.43,82.27,368.39,0.0,2135.14,...,344.66,7101.82,16.39,11470.97,1536.69,1769.77,405.39,0.0,19.96,27959.92
20,332,JERVIS,48.18,0.0,45.24,0.0,0.0,21.45,0.0,130.51,...,11.68,990.46,214.47,639.87,138.53,9.11,0.0,5.51,7.67,2262.68
21,338,ARIAS STOCK,1058.17,0.0,36.75,0.0,0.0,59.38,0.0,1084.13,...,329.36,1901.71,0.0,1753.07,720.21,46.35,95.82,0.0,0.0,7084.95
22,391,GL IMPORTAÇÃO E EXPORTAÇÃO,972.24,0.0,0.0,0.0,0.0,184.46,330.69,0.0,...,0.0,2285.1,0.0,5072.0,2731.34,2209.91,0.0,0.0,0.0,13785.74
23,398,CONFEITARIA CARLOS GONÇALVES LDA,160.92,0.0,79.68,0.0,0.0,122.56,0.0,701.82,...,0.0,1688.37,0.0,3531.46,469.17,166.04,0.0,0.0,0.0,7088.03
24,403,CARMONTI,27.42,0.0,0.0,0.0,86.52,87.35,0.0,0.0,...,122.59,1601.95,0.0,2501.79,1258.07,326.44,290.05,0.0,76.84,6452.82
25,404,RTM,710.87,150.24,697.61,87.77,0.0,237.89,537.21,5085.2,...,1428.8,1947.26,602.15,739.88,162.58,749.1,478.47,1078.54,580.41,15273.98
26,405,LACTACORES,0.0,0.0,0.0,0.0,0.0,2102.04,0.0,90.54,...,322.55,6343.12,0.0,1833.35,596.66,1331.97,0.0,0.0,0.0,12620.23
27,407,NUVIFRUITS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.53,...,0.0,6455.42,0.0,1196.88,54.52,201.82,0.0,0.0,0.0,7920.17
28,413,ARCADIE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,786.18,0.0,0.0,0.0,0.0,786.18
29,415,LOUROFOODS,503.07,0.0,1890.97,207.95,184.82,46.29,56.31,1649.76,...,543.69,13836.41,0.0,516.62,1181.18,552.94,24.72,111.62,0.0,21306.35
30,418,AUCHAN TLD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,4586.18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4586.18
31,419,BON NATURA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1662.55,0.0,3532.84,3675.03,797.77,0.0,0.0,0.0,9668.19
32,429,H-3 Carnes,2222.14,0.0,2962.8,0.0,0.0,2761.6,0.0,4375.76,...,1764.02,1186.01,0.0,11579.93,559.43,3989.92,593.25,840.5,1371.75,34207.11
33,490,PATATAS MELÉNDEZ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,491,JMR,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1976.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1976.0
35,539,TRANSPARENTEODISSEIA,285.45,0.0,0.0,0.0,0.0,0.0,0.0,59.29,...,0.0,138.5,0.0,789.53,474.26,441.31,0.0,0.0,0.0,2188.34
36,546,QUINTA DOS FUMEIROS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,27.51,0.0,0.0,127.57,0.0,0.0,155.08
37,560,MODELO CONTINENTE HIPERMERCADOS,74.37,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,74.37
38,562,COCONUT.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,588,RENOVA-FABRICA DE PAPEL DE ALMONDA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1212.0,0.0,0.0,0.0,1212.0
40,660,ANDROS PTG SECO,13.65,0.0,0.0,0.0,0.0,0.0,0.0,196.11,...,0.0,593.8,0.0,748.09,0.0,64.48,0.0,0.0,0.0,1616.13
41,680,XPO SUMOLCOMPAL,158.85,151.76,11.44,0.0,640.14,358.94,0.0,346.58,...,114.54,6968.52,448.28,1840.19,133.38,317.93,0.0,239.74,111.96,11842.25
42,757,SUMOLCOMPAL MARKETING,76.96,20.36,55.3,3.3,2.94,70.48,0.0,18.87,...,190.98,26.69,32.98,1068.27,1195.03,4.07,35.27,16.07,21.68,2839.25
43,784,SABORES DO VEZ,272.97,0.0,0.0,0.0,0.0,22.37,0.0,0.0,...,0.0,235.28,0.0,383.38,0.0,0.0,20.08,0.0,64.33,998.41
44,AAB,LAS LAGUNAS DE SANCHONUÑO (HUERCASA),0.0,0.0,0.0,0.0,0.0,0.0,0.0,588.56,...,1363.83,579.54,0.0,1400.38,0.0,182.16,0.0,0.0,0.0,4114.47

Províncias não mapeadas:

  PROV_DESTINO   COSTEDT
0               10905.73
1       AÇORES   1222.68
2       Madrid  12247.52
3          NaN  24812.38

Excel exportado: C:\Users\LISARR\Documents\Custos_Distritos_Agosto_2026.xlsx

In [ ]:
# ==========================
# 12. Resumo por cliente
# Agosto 2026
# ==========================

ANO = 2026
MES = 8

# 1. Extrair dados
df_resumo = CON[ANO].execute(
    f"""
    SELECT
        LPAD(TRIM(CAST(CODACT AS VARCHAR)), 3, '0') AS CODACT,
        ACTIVIDAD,

        ROUND(SUM(
            TRY_CAST(REPLACE(CAST(INGRESODT AS VARCHAR), ',', '.') AS DOUBLE)
        ), 2) AS INGRESODT,

        ROUND(SUM(
            TRY_CAST(REPLACE(CAST(COSTEDT AS VARCHAR), ',', '.') AS DOUBLE)
        ), 2) AS COSTEDT,

        ROUND(SUM(
            TRY_CAST(REPLACE(CAST(PALETS AS VARCHAR), ',', '.') AS DOUBLE)
        ), 2) AS PALETS

    FROM inform_27_{ANO}

    WHERE Gestion = ?
      AND SUBSTR(TRIM(CAST(FENTREGA AS VARCHAR)), 1, 6) = ?

    GROUP BY CODACT, ACTIVIDAD
    ORDER BY CODACT, ACTIVIDAD
    """,
    [GESTAO, f"{ANO}{MES:02d}"]
).df()

# 2. Visualizar
display(df_resumo)

# 3. Exportar para Excel
ficheiro = (
    Path.home()
    / "Documents"
    / "Resumo_Clientes_Agosto_2026.xlsx"
)

df_resumo.to_excel(ficheiro, index=False)

print(f"Excel exportado: {ficheiro}")

   CODACT                             ACTIVIDAD  INGRESODT    COSTEDT   PALETS
0     011                       DANONE PORTUGAL   81139.92  159709.89  18342.0
1     013               DANONE PORTUGAL CAPILAR       0.00   56853.64   3046.0
2     015                             TROPICANA       0.00    3623.18    234.0
3     028                                   PLN     171.14     609.33     25.0
4     074                              NUTRICIA   51825.87   52335.98   4181.0
5     084                   DANONE PORTUGAL TLD    2271.52    2700.00    528.0
6     116        ORANGINA SCHWEPPES ESPAÑA BASE       0.00      54.51      8.0
7     117                    ORANGINA SCHWEPPES       0.00    4413.41    170.0
8     118            ORANGNA SCHWEPPES PORTUGAL   29443.52    7980.24    588.0
9     131                                  RANA   19854.40   10823.02   1220.0
10    211                            VERDIFRESH       0.00   22749.49   1219.0
11    260                    ANDROS REFRIGERADO   27161.79   18496.09   2009.0
12    262                          DF LOGISTICA    1639.97     736.33     92.0
13    269                               EHRMANN       0.00       0.00     25.0
14    275                       MANUEL PATRICIO    3774.16     456.90    842.0
15    278                TRANSPORTES FIGUEIREDO     838.25       0.00    166.0
16    280                     SIMPLES & FRESCAS    5222.44    3188.27    416.0
17    282                                VIDARA    1094.50    1885.33     50.0
18    287                        SUPREME FRUITS    4993.54    3666.92    362.0
19    311                        ALPRO PORTUGAL   22320.13   28174.40   3970.0
20    332                                JERVIS    4613.48    2275.50    322.0
21    338                           ARIAS STOCK       0.00    7182.47    428.0
22    391            GL IMPORTAÇÃO E EXPORTAÇÃO   12912.97   13785.74   1107.0
23    398      CONFEITARIA CARLOS GONÇALVES LDA    7619.89    7088.03   1188.0
24    403                              CARMONTI    7511.95    6452.82    810.0
25    404                                   RTM   13625.10   15273.98   1509.0
26    405                            LACTACORES    9557.05   12620.23   1105.0
27    407                            NUVIFRUITS    7810.58    7961.29    882.0
28    413                               ARCADIE    3964.50     786.18     45.0
29    415                            LOUROFOODS   19786.36   21407.73   1069.0
30    418                            AUCHAN TLD    3359.79    4586.18    693.0
31    419                            BON NATURA    8915.02    9668.19    865.0
32    429                            H-3 Carnes   60138.12   34207.11   1778.0
33    490                      PATATAS MELÉNDEZ       0.00       0.00     84.0
34    491                                   JMR    2215.92    1976.00    693.0
35    539                  TRANSPARENTEODISSEIA    2570.30    2188.34    124.0
36    546                   QUINTA DOS FUMEIROS       0.00     155.08      2.0
37    551                               UPFIELD   13200.00   12150.00    726.0
38    560       MODELO CONTINENTE HIPERMERCADOS       0.00      74.37      5.0
39    562                              COCONUT.       0.00       0.00     11.0
40    588    RENOVA-FABRICA DE PAPEL DE ALMONDA    1848.48    1212.00    264.0
41    660                       ANDROS PTG SECO    2920.78    1616.13    188.0
42    680                       XPO SUMOLCOMPAL    8562.35   11842.25    449.0
43    757                 SUMOLCOMPAL MARKETING    2376.53    2839.25    190.0
44    784                        SABORES DO VEZ    1066.10    1019.18     38.0
45    AAB  LAS LAGUNAS DE SANCHONUÑO (HUERCASA)       0.00    4114.47    222.0

Excel exportado: C:\Users\LISARR\Documents\Resumo_Clientes_Agosto_2026.xlsx

In [ ]:
# ==========================
# 13. Destinos por cliente
# Agosto 2026
# ==========================

ANO = 2026
MES = 8

CLIENTES = ['391', '404', '405', '407', '415', '551', '680', '757']

# 1. Extrair e agregar dados
df_destinos = CON[ANO].execute(
    f"""
    SELECT
        LPAD(TRIM(CAST(CODACT AS VARCHAR)), 3, '0') AS CODACT,
        ACTIVIDAD,
        DESTINO,

        ROUND(SUM(
            TRY_CAST(REPLACE(CAST(PALETS AS VARCHAR), ',', '.') AS DOUBLE)
        ), 2) AS PALETS,

        ROUND(SUM(
            TRY_CAST(REPLACE(CAST(INGRESODT AS VARCHAR), ',', '.') AS DOUBLE)
        ), 2) AS INGRESODT,

        ROUND(SUM(
            TRY_CAST(REPLACE(CAST(COSTEDT AS VARCHAR), ',', '.') AS DOUBLE)
        ), 2) AS COSTEDT

    FROM inform_27_{ANO}

    WHERE Gestion = ?
      AND SUBSTR(TRIM(CAST(FENTREGA AS VARCHAR)), 1, 6) = ?
      AND LPAD(TRIM(CAST(CODACT AS VARCHAR)), 3, '0')
          IN ({','.join(['?'] * len(CLIENTES))})

    GROUP BY 1, 2, 3

    ORDER BY CODACT, PALETS DESC
    """,
    [GESTAO, f"{ANO}{MES:02d}", *CLIENTES]
).df()

# 2. Visualizar todos os destinos
with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None
):
    display(df_destinos)

# 3. Exportar para Excel
ficheiro = (
    Path.home()
    / "Documents"
    / "Destinos_Clientes_Agosto_2026.xlsx"
)

df_destinos.to_excel(ficheiro, index=False)

print(f"Excel exportado: {ficheiro}")

,CODACT,ACTIVIDAD,DESTINO,PALETS,INGRESODT,COSTEDT
0,391,GL IMPORTAÇÃO E EXPORTAÇÃO,SALVESEN LOGISTICA PORTUGAL / GL Importação E ...,525.0,0.00,537.12
1,391,GL IMPORTAÇÃO E EXPORTAÇÃO,LIDL PALMELA / GL Importação E Exportação (391),118.0,2261.50,2209.91
2,391,GL IMPORTAÇÃO E EXPORTAÇÃO,LIDL TORRES NOVAS / GL Importação E Exportação...,103.0,2034.90,2083.85
3,391,GL IMPORTAÇÃO E EXPORTAÇÃO,LIDL SANTO TIRSO / GL Importação E Exportação ...,102.0,3124.28,4127.91
4,391,GL IMPORTAÇÃO E EXPORTAÇÃO,LIDL LOURES / GL Importação E Exportação (391),97.0,1891.32,1722.02
5,391,GL IMPORTAÇÃO E EXPORTAÇÃO,ITMP ALCANENA / GL Importação E Exportação (391),82.0,1435.26,647.49
6,391,GL IMPORTAÇÃO E EXPORTAÇÃO,ITMP PAÇOS FERREIRA / GL Importação E Exportaç...,36.0,1220.44,583.67
7,391,GL IMPORTAÇÃO E EXPORTAÇÃO,PETRÓLEOS DE PORTUGAL - PETROG / GL Importação...,24.0,629.96,1487.39
8,391,GL IMPORTAÇÃO E EXPORTAÇÃO,LIDL & CIA - SANTO TIRSO / Carmonti (403),9.0,147.27,284.82
9,391,GL IMPORTAÇÃO E EXPORTAÇÃO,NaN,6.0,95.16,51.38
10,391,GL IMPORTAÇÃO E EXPORTAÇÃO,,3.0,52.11,24.22
11,391,GL IMPORTAÇÃO E EXPORTAÇÃO,"GL IMPORTAÇÃO E EXPORTAÇÃO, SA / GL Importação...",2.0,20.77,25.96
12,404,RTM,SALVESEN LOGISTICA PORTUGAL / RTM (404),858.0,0.00,651.97
13,404,RTM,PAÇO-FOOD / RTM (404),237.0,6991.48,5085.20
14,404,RTM,"AUCHAN RETAIL PORTUGAL, S.A. / RTM (404)",196.0,1672.44,156.52
15,404,RTM,NaN,32.0,620.94,338.39
16,404,RTM,,17.0,324.34,163.23
17,404,RTM,TRANP.FERNANDO SIMÕES MONTEIRO / Alpro Portuga...,16.0,240.00,126.61
18,404,RTM,DISTRIHOTEL LDA - SUCURSAL EM / RTM (404),12.0,342.48,173.38
19,404,RTM,"ÁGUA HOTELS SPA & RESORTS, S.A / RTM (404)",9.0,184.49,605.02
20,404,RTM,INTERALCACER - SUPERMERCADOS L / RTM (404),7.0,189.06,456.79
21,404,RTM,"BIDFOOD PORTUGAL, S.A. / RTM (404)",7.0,207.83,475.09
22,404,RTM,"PORTSPAR RETAIL, LDA / RTM (404)",6.0,117.52,459.98
23,404,RTM,"PEDRAIS E SANTOS, LDA / Vitacress Portugal (462)",6.0,92.62,81.13
24,404,RTM,RTM / RTM (404),6.0,101.00,65.48
25,404,RTM,ARCOL CACÉM / RTM (404),6.0,250.78,292.31
26,404,RTM,"HAVI LOGISTICS, UNIPESSOAL LDA / RTM (404)",5.0,69.95,301.97
27,404,RTM,INTERALTER - SUPERMERCADOS LDA / RTM (404),5.0,228.17,504.24
28,404,RTM,"ANDRÉ E BRANCO, LDA / RTM (404)",5.0,96.82,452.62
29,404,RTM,"VENTO DA SERRA HOTEIS, UNIPESS / RTM (404)",5.0,94.41,296.75
30,404,RTM,PALÁCIO DA LOUSA-SERRA DA LOUS / RTM (404),5.0,81.69,93.52
31,404,RTM,VILA GALE-SOCIEDADE LAMEGO / RTM (404),5.0,62.98,336.14
32,404,RTM,"XVINUS COMPANHIA ENOTURÍSTICA, / RTM (404)",4.0,75.79,207.68
33,404,RTM,HOTEL STAR INN PENICHE / RTM (404),4.0,106.32,301.46
34,404,RTM,"SUPERNOVE - SUPERMERCADOS, LDA / RTM (404)",4.0,94.62,254.00
35,404,RTM,"ÂNGELO AMARAL, LDA / RTM (404)",3.0,84.92,69.93
36,404,RTM,SUPER POVOA - SUPERMERCADOS S. / RTM (404),3.0,51.69,317.41
37,404,RTM,MERCEARIA ALENTEJANA SUPERMERC / RTM (404),3.0,122.09,372.32
38,404,RTM,WEX (AMERICOLD LEIXÕES) / Arias stock (338),3.0,57.04,238.26
39,404,RTM,"SUPERAVIS,LDA / RTM (404)",3.0,114.59,249.19
40,404,RTM,"DAVID MANUEL GOMES, UNIPESSOAL / RTM (404)",3.0,47.34,343.19
41,404,RTM,LAMEGUIPER - E.LECLERC LAMEGO / XPO Haribo (667),3.0,39.12,153.71
42,404,RTM,MANUEL FERNANDO FERREIRA GUEDE / RTM (404),3.0,89.58,117.62
43,404,RTM,"SUPERAMARES - SUPERMERCADOS, L / RTM (404)",3.0,57.07,226.33
44,404,RTM,GRUPO PESTANA POUSADAS INVESTI / RTM (404),2.0,50.36,146.01
45,404,RTM,"TERESA COCHICHO,UNIPESSOAL-COR / RTM (404)",2.0,47.24,162.58
46,404,RTM,SODIBOURO - SUPERMERCADOS LDA / RTM (404),2.0,40.40,153.87
47,404,RTM,MIRAGURTES COMERCIO LACTICINIO / RTM (404),2.0,59.10,87.77
48,404,RTM,"DISTRILOUSÃ - SUPERMERCADOS, L / RTM (404)",2.0,33.79,5.28
49,404,RTM,HOTEL SOL E SERRA / RTM (404),2.0,101.72,97.91
50,404,RTM,HOTEL DOS ARCOS LDA / RTM (404),2.0,37.50,102.54
51,404,RTM,"DISTRIARRAIOLOS SUPERMERCADOS, / RTM (404)",1.0,44.41,164.89
52,404,RTM,MEIGAL ALIMENTACAO S A / Lourofoods (415),1.0,29.27,32.74
53,404,RTM,"LISQUEIJO UNIPESSOAL, LDA / RTM (404)",1.0,21.28,63.50
54,404,RTM,INTERFERREIRA DO ALENTEJO - / RTM (404),1.0,56.79,86.18
55,404,RTM,"INTERMEALHADA - SUPERMERCADOS, / RTM (404)",1.0,16.51,5.23
56,404,RTM,SUPERMIRANDADOCORVO-SUPERMERCA / RTM (404),1.0,33.01,7.25
57,404,RTM,MEIGAL ALIMENTAÇÃO S.A / RTM (404),1.0,30.79,52.92
58,404,RTM,VILA GALE INTERNACIONAL INVEST / RTM (404),1.0,45.53,64.06
59,404,RTM,"INTERANSIÃO - SUPERMERCADOS, L / RTM (404)",1.0,15.39,5.23
60,404,RTM,PEDRAIS & SANTOS LDA-MORTÁGUA / RTM (404),1.0,33.34,9.43
61,404,RTM,"INTERPESO SUPERMERCADOS , LDA / RTM (404)",1.0,19.50,59.15
62,405,LACTACORES,SALVESEN LOGISTICA PORTUGAL / Lactacores (405),620.0,0.00,725.00
63,405,LACTACORES,"MAKRO CASH & CARRY PORTUGAL, SA / Lactacores (...",129.0,2372.91,2774.65
64,405,LACTACORES,AMARAL & FILHOS / Lactacores (405),115.0,3306.19,5430.43
65,405,LACTACORES,TRANP.FERNANDO SIMÕES MONTEIRO / Alpro Portuga...,80.0,1411.63,801.82
66,405,LACTACORES,AUCHAN - SALVESEN - REFRIGERAD / Lactacores (405),67.0,568.83,0.00
67,405,LACTACORES,NaN,22.0,287.58,505.22
68,405,LACTACORES,SOGENAVE SOC. GER.AB.NAV.IND.HOT.SA / Lactacor...,20.0,537.71,323.10
69,405,LACTACORES,,16.0,342.78,384.98
70,405,LACTACORES,"ARCOL - A.ROD.CO.LOP.BEB.E ALIME.,SA / Lactaco...",11.0,298.11,362.62
71,405,LACTACORES,A. RIBEIRO DA SILVA E RIBEIRO / Lactacores (405),6.0,129.15,249.18
72,405,LACTACORES,"A.S. SIMÕES, LDA / Lactacores (405)",5.0,137.58,154.36
73,405,LACTACORES,LACTAÇORES (REFRIGERADO) / Lactacores (405),4.0,33.96,177.26
74,405,LACTACORES,LACTAÇORES (SECO) / Lactacores (405),4.0,0.00,97.54
75,405,LACTACORES,"J.V.LOBATO, LDA / Lactacores (405)",2.0,45.52,135.18
76,405,LACTACORES,YOÇOR - GARCEZ & SANTOS LDA / Lactacores (405),2.0,42.71,279.84
77,405,LACTACORES,PINGO DOCE DIST.ALIM.SA / Lactacores (405),1.0,24.36,107.01
78,405,LACTACORES,MODELO CONTINENTE HIPERMERCADOS / Lactacores (...,1.0,18.03,112.04
79,407,NUVIFRUITS,SALVESEN LOGISTICA PORTUGAL / Nuvifruits (407),525.0,0.00,515.93
80,407,NUVIFRUITS,CATERINGPOR CATERING DE PORTUG / Nuvifruits (407),71.0,2149.28,3062.93
81,407,NUVIFRUITS,MODIS AZAMBUJA / Nuvifruits (407),51.0,971.55,722.16
82,407,NUVIFRUITS,"AUCHAN RETAIL PORTUGAL II, S.A / Nuvifruits (407)",23.0,438.15,0.00
83,407,NUVIFRUITS,MODIS MAIA / Nuvifruits (407),22.0,687.94,318.64
84,407,NUVIFRUITS,"MODELO CONTINENTE,HIP.SA-MAIA/ / Rana España (...",21.0,328.36,661.50
85,407,NUVIFRUITS,GLOVOAPP PORTUGAL UNIPESSOAL L / Nuvifruits (407),21.0,385.17,1045.01
86,407,NUVIFRUITS,"SOGENAVE, SA / Nuvifruits (407)",20.0,405.51,268.34
87,407,NUVIFRUITS,NaN,19.0,275.91,143.52
88,407,NUVIFRUITS,NUVIFRUITS / Nuvifruits (407),16.0,214.64,112.00
89,407,NUVIFRUITS,MODIS AZAMBUJA AMBIENTE / Nuvifruits (407),15.0,285.75,38.78
90,407,NUVIFRUITS,MODIS MAIA AMBIENTE / Nuvifruits (407),11.0,343.97,14.87
91,407,NUVIFRUITS,EL CORTE ARMAZEN ALCOCHETE / Nuvifruits (407),11.0,242.33,66.72
92,407,NUVIFRUITS,AUCHAN VENDA DO PINHEIRO / Nuvifruits (407),8.0,125.16,277.23
93,407,NUVIFRUITS,NUVIFRUIT / Nuvifruits (407),7.0,149.90,269.98
94,407,NUVIFRUITS,,7.0,103.93,44.13
95,407,NUVIFRUITS,ALDI RETAIL UNIPESSOAL LDA / Nuvifruits (407),6.0,132.18,40.63
96,407,NUVIFRUITS,COLMEIA DO MESTRE- QTA DO ANJO / Nuvifruits (407),4.0,93.32,94.47
97,407,NUVIFRUITS,LIDL SANTO TIRSO / Nuvifruits (407),4.0,125.08,41.12
98,407,NUVIFRUITS,INSCO / Nuvifruits (407),4.0,74.75,18.01
99,407,NUVIFRUITS,LIDL TORRES NOVAS / Nuvifruits (407),3.0,73.89,15.90
100,407,NUVIFRUITS,"RESTFLIGHT-SERV. CATERING,UNIP / Nuvifruits (407)",3.0,45.86,22.03
101,407,NUVIFRUITS,APOLÓNIA FARO / Nuvifruits (407),2.0,10.10,3.90
102,407,NUVIFRUITS,D.J.V.-COM. DE PROD. ALIMENTAR / Nuvifruits (407),2.0,43.94,44.78
103,407,NUVIFRUITS,FRUSEL-FRUTOS SELECCIONADOS LD / Nuvifruits (407),1.0,25.93,38.62
104,407,NUVIFRUITS,PLUSMATIC-MAQ DE VENDA AUTOMAT / Nuvifruits (407),1.0,17.88,7.63
105,407,NUVIFRUITS,"COMBINAÇAO PURA, UNIPESSOAL LD / Nuvifruits (407)",1.0,21.11,27.39
106,407,NUVIFRUITS,"JOSE FRANCO SILVESTRE, UNIP, L / Nuvifruits (407)",1.0,21.11,30.28
107,407,NUVIFRUITS,"NUVIFRUITS, SA - NC / Nuvifruits (407)",1.0,0.00,0.96
108,407,NUVIFRUITS,"QUINTA ENCANTADA UNIPESSOAL, L / Nuvifruits (407)",1.0,17.88,13.83
109,415,LOUROFOODS,SALVESEN LOGISTICA PORTUGAL / Lourofoods (415),497.0,8383.65,7686.00
110,415,LOUROFOODS,ARMAZEM NOATUM LOGISTICS - MÓD / Lourofoods (415),99.0,1504.87,1045.20
111,415,LOUROFOODS,CENTROS DISTRIBUIC.AZAMBUJA / Lourofoods (415),93.0,867.30,670.87
112,415,LOUROFOODS,"AUCHAN RETAIL PORTUGAL II, S.A / Lourofoods (415)",72.0,908.81,923.61
113,415,LOUROFOODS,PD SILVES / Lourofoods (415),29.0,925.05,774.97
114,415,LOUROFOODS,PAULO LIMA-VIZELA / Lourofoods (415),17.0,468.97,390.69
115,415,LOUROFOODS,DREAM PLUS - SINTRA / Lourofoods (415),17.0,366.96,636.67
116,415,LOUROFOODS,NaN,16.0,409.32,351.29
117,415,LOUROFOODS,"BOLAMA SUPERMERCADOS, LDA / Lourofoods (415)",13.0,369.86,431.54
118,415,LOUROFOODS,ALEXANDRINO PEREIRA & SILVA PE / Lourofoods (415),7.0,172.32,276.35
119,415,LOUROFOODS,COVIRAN S COOP AND SUCURSAL EM / Lourofoods (415),7.0,172.64,241.22
120,415,LOUROFOODS,CATARPLUS(RECHEIO MASTERCHEF) / Lourofoods (415),7.0,163.13,208.43
121,415,LOUROFOODS,D.J.V COMERCIO PROD. ALIMEN / Lourofoods (415),7.0,163.13,284.97
122,415,LOUROFOODS,SOC PRODUTOS ALIMENTARES JOFER / Lourofoods (415),6.0,139.91,310.98
123,415,LOUROFOODS,SOGENAVE TOJAL / Lourofoods (415),6.0,139.32,116.35
124,415,LOUROFOODS,COZINHA CENTRAL DE ODIVELAS II / Lourofoods (415),6.0,139.91,188.45
125,415,LOUROFOODS,PISABELL / Lourofoods (415),6.0,139.32,91.41
126,415,LOUROFOODS,JOSE VILHENA - MEAT TRADING LD / Lourofoods (415),6.0,135.90,173.64
127,415,LOUROFOODS,COME OVO - AMORA / Lourofoods (415),5.0,161.32,267.54
128,415,LOUROFOODS,GUERREIRO E PRATA - FARO / Lourofoods TLD (408),5.0,128.13,113.69
129,415,LOUROFOODS,"BENTO & NASCIMENTO, LDA / Lourofoods (415)",5.0,147.30,305.41
130,415,LOUROFOODS,ARCOL GUIMARÃES / Lourofoods (415),5.0,117.84,251.53
131,415,LOUROFOODS,JOPAMA - COVILHA / Lourofoods (415),5.0,269.20,170.81
132,415,LOUROFOODS,BELAVE LEIRIA / Lourofoods (415),5.0,65.84,331.28
133,415,LOUROFOODS,ZOLVE MOLDIVAS - LOGIFRIO / Lourofoods (415),5.0,121.25,163.70
134,415,LOUROFOODS,RAMOS E PEREIRA LDA / Lourofoods (415),4.0,128.40,228.68
135,415,LOUROFOODS,ESTRELA DA SERRA SOCIEDADE COM / Lourofoods (415),4.0,71.43,414.59
136,415,LOUROFOODS,BENTOVO UNIPESSOAL LDA / Lourofoods (415),4.0,94.06,223.46
137,415,LOUROFOODS,,4.0,103.20,103.53
138,415,LOUROFOODS,GEL SILVES / Lourofoods (415),4.0,101.46,75.96
139,415,LOUROFOODS,"RECHEIO, S.A. - RECHEIO EXP. 2 / Lourofoods (415)",4.0,94.06,133.74
140,415,LOUROFOODS,TRANP.FERNANDO SIMÕES MONTEIRO / Alpro Portuga...,4.0,58.36,46.29
141,415,LOUROFOODS,MOS - ARMAZEM EXP. PORTWAY HAN / Lourofoods (415),3.0,69.66,104.44
142,415,LOUROFOODS,REGIONAL MERCADORIAS ALCANENA / Lourofoods (415),3.0,57.66,24.24
143,415,LOUROFOODS,ALCAFER COM. IND. PROD. ALIM / Lourofoods (415),3.0,96.30,83.80
144,415,LOUROFOODS,DISTINTADELÍCIA - PRODUTOS ALI / Lourofoods (415),3.0,76.53,62.46
145,415,LOUROFOODS,JVLOBATO VIALONGA / Lourofoods (415),3.0,46.44,167.02
146,415,LOUROFOODS,CONSUMINTENSO - BRAGA / Lourofoods (415),3.0,86.90,146.49
147,415,LOUROFOODS,RECEITAS DA AVO - ARRUDA VINHO / Lourofoods (415),3.0,47.62,125.14
148,415,LOUROFOODS,CONGELBRAGA - PRODUTOS ALIMENT / Lourofoods (415),3.0,88.38,110.46
149,415,LOUROFOODS,NATUREZA CONG. - MENDALVE / Lourofoods (415),3.0,70.25,110.36
150,415,LOUROFOODS,DUNANY FOODS S.A. / Lourofoods (415),3.0,96.30,123.63
151,415,LOUROFOODS,PEREIRA PINTO-PAÇOS DE FERREIR / Lourofoods (415),3.0,74.58,65.55
152,415,LOUROFOODS,"FERNANDO ANES UNIPESSOAL, LDA. / Lourofoods (415)",3.0,66.62,111.62
153,415,LOUROFOODS,"PEREIRA & RIBEIRO, LDA / Lourofoods (415)",3.0,86.16,97.92
154,415,LOUROFOODS,JM CASTRO / Lourofoods (415),3.0,98.76,111.11
155,415,LOUROFOODS,COSTA & PIMPÃO - PRODUTOS LÁCT / Lourofoods (415),2.0,64.20,137.98
156,415,LOUROFOODS,VIPANI - MIRANDELA / Lourofoods (415),2.0,72.26,82.54
157,415,LOUROFOODS,NORTENHO - T.VEDRAS / Lourofoods (415),2.0,46.44,66.10
158,415,LOUROFOODS,SEGREDOS IBERICOS - AVEIRO / Lourofoods (415),2.0,58.92,127.15
159,415,LOUROFOODS,APRECIARUMOS / Lourofoods (415),2.0,47.62,60.45
160,415,LOUROFOODS,"M. CUNHA, S.A. - FELGUEIRAS / Lourofoods (415)",2.0,51.00,120.77
161,415,LOUROFOODS,VANIBRU - COMÉRCIO DE PRODUTOS / Lourofoods (415),2.0,57.44,86.29
162,415,LOUROFOODS,CASCARNES - COMÉRCIO E IND STR / Lourofoods (415),2.0,46.44,65.10
163,415,LOUROFOODS,"CARDO SRA DO MONTE,LDA-ARRABAL / Lourofoods (415)",2.0,32.92,134.64
164,415,LOUROFOODS,"RECHEIO MASTERCHEF, LDA / Lourofoods (415)",2.0,51.60,38.63
165,415,LOUROFOODS,SUPER 2004 SINTRA / Lourofoods (415),2.0,47.62,91.81
166,415,LOUROFOODS,"A.S.SIMOES PRODUTOS ALIM, LDA / Lourofoods (415)",2.0,47.62,52.95
167,415,LOUROFOODS,O AZEITEIRO - ANTONIO CARVALHO / Lourofoods (415),2.0,64.20,116.19
168,415,LOUROFOODS,BESAVES LOULE / Lourofoods (415),1.0,25.80,20.55
169,415,LOUROFOODS,REIS E PACHECO / Lourofoods (415),1.0,25.50,55.96
170,415,LOUROFOODS,FA E MIGUEL - COVILHA / Lourofoods (415),1.0,56.60,14.01
171,415,LOUROFOODS,"VAGALIMENTAR, DISTRIBUÇÃO PROD / Lourofoods (415)",1.0,30.64,59.42
172,415,LOUROFOODS,AVICUIMA - UNIDADE DE PRODUÇÃO / Lourofoods (415),1.0,36.13,25.71
173,415,LOUROFOODS,BARSTOCK LISBOA / Lourofoods (415),1.0,23.81,41.82
174,415,LOUROFOODS,SIFORTE LEIRIA / Lourofoods (415),1.0,16.46,31.13
175,415,LOUROFOODS,MEIGAL ALIMENTAÇÃO - FRIELAS / Lourofoods (415),1.0,23.81,55.28
176,415,LOUROFOODS,MEAT HERITAGE LDA / Lourofoods (415),1.0,32.92,46.64
177,415,LOUROFOODS,QUINTA DAS ARCAS - VALONGO / Lourofoods (415),1.0,25.50,55.96
178,415,LOUROFOODS,EUROPFOODS - ALGARVE / Lourofoods (415),1.0,25.80,25.31
179,415,LOUROFOODS,SANER SOC ALIMENTAR DO NORTE S / Lourofoods (415),1.0,25.50,54.68
180,415,LOUROFOODS,AVILOULÉ - COMÉRCIO DE PRODUTO / Lourofoods (415),1.0,25.80,22.42
181,415,LOUROFOODS,BIDFOOD / Lourofoods (415),1.0,23.81,35.52
182,415,LOUROFOODS,MANUEL RODRIGO DOS SANTOS TELO / Lourofoods (415),1.0,32.92,58.10
183,415,LOUROFOODS,ALVARO & MAGDA LDA / Lourofoods (415),1.0,23.81,52.92
184,415,LOUROFOODS,RUMIEMA COMÉRCIO E DISTRIBUIÇÃO DE PRODUTOS ...,1.0,29.46,41.07
185,415,LOUROFOODS,DISTRIBUI - COM. DIST. PRODUTO / Lourofoods (415),1.0,36.13,56.67
186,415,LOUROFOODS,SPEEDYFOOD SERVICE LDA / Lourofoods (415),1.0,20.95,11.09
187,415,LOUROFOODS,PANIOVO - PRODUTOS ALIMENTARES / Lourofoods (415),1.0,36.13,43.03
188,415,LOUROFOODS,BLOCO FRIO - PRODUTOS ALIMENTA / Lourofoods (415),1.0,25.50,55.96
189,415,LOUROFOODS,HELDER R S MARQUES LDA / Lourofoods (415),1.0,20.95,20.11
190,415,LOUROFOODS,ANCORA PRATEADA COM. PROD. ALI / Lourofoods (415),1.0,62.94,56.31
191,415,LOUROFOODS,JOAO EVARISTO - VIANA CASTELO / Lourofoods (415),1.0,30.64,24.72
192,415,LOUROFOODS,EUROBAR-SOC. ABAST.DE PRODUTOS / Lourofoods (415),1.0,23.81,46.84
193,415,LOUROFOODS,LUCSTOCKFOOD / Lourofoods (415),1.0,32.92,80.18
194,415,LOUROFOODS,LARDOMUS SOC ALIMENTOS LDA / Lourofoods (415),1.0,29.46,58.63
195,551,UPFIELD,SALVESEN LOGISTICA GETAFE / Upfield (551),726.0,13200.00,12150.00
196,680,XPO SUMOLCOMPAL,SALVESEN LOGISTICA PORTUGAL / Xpo Sumolcompal ...,163.0,3531.89,6317.39
197,680,XPO SUMOLCOMPAL,NaN,55.0,671.47,822.95
198,680,XPO SUMOLCOMPAL,TRANP.FERNANDO SIMÕES MONTEIRO / Alpro Portuga...,25.0,224.98,138.12
199,680,XPO SUMOLCOMPAL,,19.0,235.39,278.27
200,680,XPO SUMOLCOMPAL,ALMODOVAR A.S. - ARS - REST / Xpo Sumolcompal ...,12.0,108.21,72.41
201,680,XPO SUMOLCOMPAL,VG ELVAS / Xpo Sumolcompal (680),9.0,336.04,198.44
202,680,XPO SUMOLCOMPAL,AUCHAN GONDOMAR / Xpo Sumolcompal (680),9.0,114.02,273.40
203,680,XPO SUMOLCOMPAL,AUCHAN MAIA / Xpo Sumolcompal (680),8.0,103.11,190.91
204,680,XPO SUMOLCOMPAL,AUCHAN ALFRAGIDE / Xpo Sumolcompal (680),8.0,122.11,211.20
205,680,XPO SUMOLCOMPAL,IKEA MATOSINHOS / TIBA (788),8.0,99.79,268.32
206,680,XPO SUMOLCOMPAL,AUCHAN SETUBAL / Xpo Sumolcompal (680),8.0,200.25,317.93
207,680,XPO SUMOLCOMPAL,AUCHAN FARO / Xpo Sumolcompal (680),8.0,131.45,101.63
208,680,XPO SUMOLCOMPAL,AUCHAN CASTELO BRANCO / Xpo Sumolcompal (680),8.0,459.87,197.97
209,680,XPO SUMOLCOMPAL,A2 ALMODOVAR (LIS/ALG) ES63375 / Xpo Sumolcomp...,8.0,108.95,75.96
210,680,XPO SUMOLCOMPAL,AUCHAN FIGUEIRA FOZ / Xpo Sumolcompal (680),7.0,48.96,154.19
211,680,XPO SUMOLCOMPAL,VG ALTER DO CHÃO / Xpo Sumolcompal (680),7.0,346.57,249.84
212,680,XPO SUMOLCOMPAL,AUCHAN VISEU / Xpo Sumolcompal (680),6.0,88.16,111.96
213,680,XPO SUMOLCOMPAL,AUCHAN SINTRA / Xpo Sumolcompal (680),5.0,44.56,45.58
214,680,XPO SUMOLCOMPAL,AUCHAN GAIA / Xpo Sumolcompal (680),5.0,38.59,74.34
215,680,XPO SUMOLCOMPAL,AUCHAN PAÇO DE ARCOS / Xpo Sumolcompal (680),5.0,51.57,70.03
216,680,XPO SUMOLCOMPAL,A.S VILA VELHA RODAO I (11548) / Xpo Sumolcomp...,5.0,280.82,160.23
217,680,XPO SUMOLCOMPAL,AUCHAN VILA DO CONDE / Xpo Sumolcompal (680),5.0,87.78,176.95
218,680,XPO SUMOLCOMPAL,AUCHAN COIMBRA / Xpo Sumolcompal (680),4.0,51.69,66.63
219,680,XPO SUMOLCOMPAL,AUCHAN ALVERCA / Xpo Sumolcompal (680),4.0,63.51,109.17
220,680,XPO SUMOLCOMPAL,AUCHAN CASCAIS NASCENTE / Xpo Sumolcompal (680),4.0,64.28,111.79
221,680,XPO SUMOLCOMPAL,AUCHAN VILA REAL / Xpo Sumolcompal (680),4.0,97.88,239.74
222,680,XPO SUMOLCOMPAL,CELTEJO / Xpo Sumolcompal (680),4.0,169.42,64.09
223,680,XPO SUMOLCOMPAL,AUCHAN CALDAS DA RAINHA / Xpo Sumolcompal (680),4.0,87.49,110.72
224,680,XPO SUMOLCOMPAL,AUCHAN AVEIRO / Xpo Sumolcompal (680),4.0,24.88,94.39
225,680,XPO SUMOLCOMPAL,AUCHAN TORRES VEDRAS / Xpo Sumolcompal (680),3.0,30.10,43.49
226,680,XPO SUMOLCOMPAL,AUCHAN GUIMARÃES / Xpo Sumolcompal (680),3.0,35.29,133.38
227,680,XPO SUMOLCOMPAL,A.S VILA VELHA RODAO II (11545 / Xpo Sumolcomp...,3.0,172.54,95.98
228,680,XPO SUMOLCOMPAL,GRAB&GO MOGADOURO / Xpo Sumolcompal (680),2.0,13.78,9.06
229,680,XPO SUMOLCOMPAL,BP VILA VELHA DE RÓDÃO / Xpo Sumolcompal (680),2.0,97.17,66.83
230,680,XPO SUMOLCOMPAL,AUCHAN AMOREIRAS / Xpo Sumolcompal (680),2.0,21.50,52.98
231,680,XPO SUMOLCOMPAL,PALACETE BARÃO FORRESTER ALIJÒ / Xpo Sumolcomp...,2.0,21.57,52.55
232,680,XPO SUMOLCOMPAL,AUCHAN FAMALICÃO / Xpo Sumolcompal (680),2.0,18.22,11.44
233,680,XPO SUMOLCOMPAL,A.S VILA VELHA RODAO II (11545) / Xpo Sumolcom...,2.0,94.49,55.04
234,680,XPO SUMOLCOMPAL,REPSOL PEDROGÃO GRANDE IC8 ES1076 / Xpo Sumolc...,2.0,15.90,3.28
235,680,XPO SUMOLCOMPAL,ALVES BANDEIRA CASTANHEIRA DE / Xpo Sumolcompa...,1.0,6.50,0.33
236,680,XPO SUMOLCOMPAL,CAMPING MONTE DA ROCHA / Xpo Sumolcompal (680),1.0,18.79,3.39
237,680,XPO SUMOLCOMPAL,MA ALMIRANTE REIS / Xpo Sumolcompal (680),1.0,5.47,6.89
238,680,XPO SUMOLCOMPAL,ALVES BANDEIRA CASTANHEIRA DE PERA / Xpo Sumol...,1.0,6.50,0.21
239,680,XPO SUMOLCOMPAL,MERCEARIA CAVACO / Xpo Sumolcompal (680),1.0,10.84,2.85
240,757,SUMOLCOMPAL MARKETING,ALMEIRIM - PUBLICIDADE / Sumolcompal Marketing...,65.0,850.86,1020.15
241,757,SUMOLCOMPAL MARKETING,NaN,28.0,355.25,204.49
242,757,SUMOLCOMPAL MARKETING,SUMOL-COMPAL DISTRIBUIÇÃO PÓVO / Sumolcompal M...,26.0,283.39,541.48
243,757,SUMOLCOMPAL MARKETING,,14.0,124.80,295.02
244,757,SUMOLCOMPAL MARKETING,TRANP.FERNANDO SIMÕES MONTEIRO / Alpro Portuga...,11.0,80.33,42.14
245,757,SUMOLCOMPAL MARKETING,DIAMANTINO BORGES / Sumolcompal Marketing (757),5.0,73.81,174.88
246,757,SUMOLCOMPAL MARKETING,A.MARQUES LDA / Sumolcompal Marketing (757),4.0,64.24,140.54
247,757,SUMOLCOMPAL MARKETING,POMBAL - PUBLICIDADE / Sumolcompal Marketing (...,4.0,32.08,50.44
248,757,SUMOLCOMPAL MARKETING,MANUEL JOAO DA SILVA FERRAZ / A-Ware Iberia (433),3.0,15.43,21.68
249,757,SUMOLCOMPAL MARKETING,DOMINGOS TEIXEIRA & C LDA / Sumolcompal Market...,2.0,19.30,31.78
250,757,SUMOLCOMPAL MARKETING,SUMOL+COMPAL MARCAS - FARO / Sumolcompal Marke...,2.0,25.07,4.09
251,757,SUMOLCOMPAL MARKETING,JORGE PEREIRA LDA / Sumolcompal Marketing (757),2.0,19.30,23.52
252,757,SUMOLCOMPAL MARKETING,SODREL SOC DIST RACOES E REFRI / Sumolcompal M...,2.0,60.65,32.98
253,757,SUMOLCOMPAL MARKETING,FABRICA LICORES E XAROPES ERBE / Sumolcompal M...,2.0,59.32,70.54
254,757,SUMOLCOMPAL MARKETING,SANTOS SILVA & FILHOS LDA / Sumolcompal Market...,2.0,9.49,3.48

Excel exportado: C:\Users\LISARR\Documents\Destinos_Clientes_Agosto_2026.xlsx

In [ ]:
# ==========================
# 13. Destinos por cliente e distrito
# Agosto 2026
# ==========================

ANO = 2026
MES = 8

CLIENTES = ['391', '404', '405', '407', '415', '551', '680', '757']

# 1. Extrair dados
dados_destinos = CON[ANO].execute(
    f"""
    SELECT
        LPAD(TRIM(CAST(CODACT AS VARCHAR)), 3, '0') AS CODACT,
        ACTIVIDAD,
        DESTINO,
        PROV_DESTINO,

        SUM(
            TRY_CAST(REPLACE(CAST(PALETS AS VARCHAR), ',', '.') AS DOUBLE)
        ) AS PALETS,

        SUM(
            TRY_CAST(REPLACE(CAST(INGRESODT AS VARCHAR), ',', '.') AS DOUBLE)
        ) AS INGRESODT,

        SUM(
            TRY_CAST(REPLACE(CAST(COSTEDT AS VARCHAR), ',', '.') AS DOUBLE)
        ) AS COSTEDT

    FROM inform_27_{ANO}

    WHERE Gestion = ?
      AND SUBSTR(TRIM(CAST(FENTREGA AS VARCHAR)), 1, 6) = ?
      AND LPAD(TRIM(CAST(CODACT AS VARCHAR)), 3, '0')
          IN ({','.join(['?'] * len(CLIENTES))})

    GROUP BY 1, 2, 3, 4
    """,
    [GESTAO, f"{ANO}{MES:02d}", *CLIENTES]
).df()

# 2. Normalizar distrito
# Reutiliza as variáveis 'normalizar' e 'mapa'

dados_destinos["DISTRITO"] = (
    dados_destinos["PROV_DESTINO"]
    .map(normalizar)
    .map(mapa)
    .fillna("NÃO MAPEADO")
)

# 3. Agrupar por cliente, destino e distrito
df_destinos = (
    dados_destinos
    .groupby(
        ["CODACT", "ACTIVIDAD", "DESTINO", "DISTRITO"],
        dropna=False,
        as_index=False
    )[["PALETS", "INGRESODT", "COSTEDT"]]
    .sum()
)

# 4. Arredondar valores
df_destinos[["PALETS", "INGRESODT", "COSTEDT"]] = (
    df_destinos[["PALETS", "INGRESODT", "COSTEDT"]].round(2)
)

# 5. Ordenar por cliente e paletes (decrescente)
df_destinos = df_destinos.sort_values(
    ["CODACT", "PALETS"],
    ascending=[True, False]
).reset_index(drop=True)

# 6. Visualizar
with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None
):
    display(df_destinos)

# 7. Exportar para Excel
ficheiro = (
    Path.home()
    / "Documents"
    / "Destinos_Clientes_Distritos_Agosto_2026.xlsx"
)

df_destinos.to_excel(ficheiro, index=False)

print(f"Excel exportado: {ficheiro}")

,CODACT,ACTIVIDAD,DESTINO,DISTRITO,PALETS,INGRESODT,COSTEDT
0,391,GL IMPORTAÇÃO E EXPORTAÇÃO,SALVESEN LOGISTICA PORTUGAL / GL Importação E ...,Lisboa,525.0,0.00,537.12
1,391,GL IMPORTAÇÃO E EXPORTAÇÃO,LIDL PALMELA / GL Importação E Exportação (391),Setúbal,118.0,2261.50,2209.91
2,391,GL IMPORTAÇÃO E EXPORTAÇÃO,LIDL TORRES NOVAS / GL Importação E Exportação...,Santarém,103.0,2034.90,2083.85
3,391,GL IMPORTAÇÃO E EXPORTAÇÃO,LIDL SANTO TIRSO / GL Importação E Exportação ...,Porto,102.0,3124.28,4127.91
4,391,GL IMPORTAÇÃO E EXPORTAÇÃO,LIDL LOURES / GL Importação E Exportação (391),Lisboa,97.0,1891.32,1722.02
5,391,GL IMPORTAÇÃO E EXPORTAÇÃO,ITMP ALCANENA / GL Importação E Exportação (391),Santarém,82.0,1435.26,647.49
6,391,GL IMPORTAÇÃO E EXPORTAÇÃO,ITMP PAÇOS FERREIRA / GL Importação E Exportaç...,Porto,36.0,1220.44,583.67
7,391,GL IMPORTAÇÃO E EXPORTAÇÃO,PETRÓLEOS DE PORTUGAL - PETROG / GL Importação...,Aveiro,16.0,307.16,972.24
8,391,GL IMPORTAÇÃO E EXPORTAÇÃO,LIDL & CIA - SANTO TIRSO / Carmonti (403),Porto,9.0,147.27,284.82
9,391,GL IMPORTAÇÃO E EXPORTAÇÃO,NaN,Porto,6.0,95.16,51.38
10,391,GL IMPORTAÇÃO E EXPORTAÇÃO,PETRÓLEOS DE PORTUGAL - PETROG / GL Importação...,Évora,5.0,201.75,330.69
11,391,GL IMPORTAÇÃO E EXPORTAÇÃO,,Porto,3.0,52.11,24.22
12,391,GL IMPORTAÇÃO E EXPORTAÇÃO,PETRÓLEOS DE PORTUGAL - PETROG / GL Importação...,Coimbra,3.0,121.05,184.46
13,391,GL IMPORTAÇÃO E EXPORTAÇÃO,"GL IMPORTAÇÃO E EXPORTAÇÃO, SA / GL Importação...",Lisboa,2.0,20.77,25.96
14,404,RTM,SALVESEN LOGISTICA PORTUGAL / RTM (404),Lisboa,858.0,0.00,651.97
15,404,RTM,PAÇO-FOOD / RTM (404),Faro,237.0,6991.48,5085.20
16,404,RTM,"AUCHAN RETAIL PORTUGAL, S.A. / RTM (404)",Lisboa,196.0,1672.44,156.52
17,404,RTM,NaN,Porto,32.0,620.94,338.39
18,404,RTM,,Porto,17.0,324.34,163.23
19,404,RTM,TRANP.FERNANDO SIMÕES MONTEIRO / Alpro Portuga...,Coimbra,16.0,240.00,126.61
20,404,RTM,DISTRIHOTEL LDA - SUCURSAL EM / RTM (404),Lisboa,12.0,342.48,173.38
21,404,RTM,"ÁGUA HOTELS SPA & RESORTS, S.A / RTM (404)",Vila Real,9.0,184.49,605.02
22,404,RTM,"BIDFOOD PORTUGAL, S.A. / RTM (404)",Lisboa,7.0,207.83,475.09
23,404,RTM,INTERALCACER - SUPERMERCADOS L / RTM (404),Setúbal,7.0,189.06,456.79
24,404,RTM,ARCOL CACÉM / RTM (404),Setúbal,6.0,250.78,292.31
25,404,RTM,"PEDRAIS E SANTOS, LDA / Vitacress Portugal (462)",Viseu,6.0,92.62,81.13
26,404,RTM,"PORTSPAR RETAIL, LDA / RTM (404)",Leiria,6.0,117.52,459.98
27,404,RTM,RTM / RTM (404),Lisboa,6.0,101.00,65.48
28,404,RTM,"ANDRÉ E BRANCO, LDA / RTM (404)",Leiria,5.0,96.82,452.62
29,404,RTM,"HAVI LOGISTICS, UNIPESSOAL LDA / RTM (404)",Lisboa,5.0,69.95,301.97
30,404,RTM,INTERALTER - SUPERMERCADOS LDA / RTM (404),Portalegre,5.0,228.17,504.24
31,404,RTM,PALÁCIO DA LOUSA-SERRA DA LOUS / RTM (404),Coimbra,5.0,81.69,93.52
32,404,RTM,"VENTO DA SERRA HOTEIS, UNIPESS / RTM (404)",Vila Real,5.0,94.41,296.75
33,404,RTM,VILA GALE-SOCIEDADE LAMEGO / RTM (404),Viseu,5.0,62.98,336.14
34,404,RTM,HOTEL STAR INN PENICHE / RTM (404),Leiria,4.0,106.32,301.46
35,404,RTM,"SUPERNOVE - SUPERMERCADOS, LDA / RTM (404)",Aveiro,4.0,94.62,254.00
36,404,RTM,"XVINUS COMPANHIA ENOTURÍSTICA, / RTM (404)",Aveiro,4.0,75.79,207.68
37,404,RTM,"DAVID MANUEL GOMES, UNIPESSOAL / RTM (404)",Viana do Castelo,3.0,47.34,343.19
38,404,RTM,LAMEGUIPER - E.LECLERC LAMEGO / XPO Haribo (667),Viseu,3.0,39.12,153.71
39,404,RTM,MANUEL FERNANDO FERREIRA GUEDE / RTM (404),Vila Real,3.0,89.58,117.62
40,404,RTM,MERCEARIA ALENTEJANA SUPERMERC / RTM (404),Évora,3.0,122.09,372.32
41,404,RTM,SUPER POVOA - SUPERMERCADOS S. / RTM (404),Braga,3.0,51.69,317.41
42,404,RTM,"SUPERAMARES - SUPERMERCADOS, L / RTM (404)",Braga,3.0,57.07,226.33
43,404,RTM,"SUPERAVIS,LDA / RTM (404)",Aveiro,3.0,114.59,249.19
44,404,RTM,WEX (AMERICOLD LEIXÕES) / Arias stock (338),Porto,3.0,57.04,238.26
45,404,RTM,"ÂNGELO AMARAL, LDA / RTM (404)",Lisboa,3.0,84.92,69.93
46,404,RTM,"DISTRILOUSÃ - SUPERMERCADOS, L / RTM (404)",Coimbra,2.0,33.79,5.28
47,404,RTM,GRUPO PESTANA POUSADAS INVESTI / RTM (404),Leiria,2.0,50.36,146.01
48,404,RTM,HOTEL DOS ARCOS LDA / RTM (404),Viana do Castelo,2.0,37.50,102.54
49,404,RTM,HOTEL SOL E SERRA / RTM (404),Portalegre,2.0,101.72,97.91
50,404,RTM,MIRAGURTES COMERCIO LACTICINIO / RTM (404),Bragança,2.0,59.10,87.77
51,404,RTM,SODIBOURO - SUPERMERCADOS LDA / RTM (404),Braga,2.0,40.40,153.87
52,404,RTM,"TERESA COCHICHO,UNIPESSOAL-COR / RTM (404)",Santarém,2.0,47.24,162.58
53,404,RTM,"DISTRIARRAIOLOS SUPERMERCADOS, / RTM (404)",Évora,1.0,44.41,164.89
54,404,RTM,"INTERANSIÃO - SUPERMERCADOS, L / RTM (404)",Leiria,1.0,15.39,5.23
55,404,RTM,INTERFERREIRA DO ALENTEJO - / RTM (404),Beja,1.0,56.79,86.18
56,404,RTM,"INTERMEALHADA - SUPERMERCADOS, / RTM (404)",Coimbra,1.0,16.51,5.23
57,404,RTM,"INTERPESO SUPERMERCADOS , LDA / RTM (404)",Vila Real,1.0,19.50,59.15
58,404,RTM,"LISQUEIJO UNIPESSOAL, LDA / RTM (404)",Leiria,1.0,21.28,63.50
59,404,RTM,MEIGAL ALIMENTACAO S A / Lourofoods (415),Viana do Castelo,1.0,29.27,32.74
60,404,RTM,MEIGAL ALIMENTAÇÃO S.A / RTM (404),Lisboa,1.0,30.79,52.92
61,404,RTM,PEDRAIS & SANTOS LDA-MORTÁGUA / RTM (404),Viseu,1.0,33.34,9.43
62,404,RTM,SUPERMIRANDADOCORVO-SUPERMERCA / RTM (404),Coimbra,1.0,33.01,7.25
63,404,RTM,VILA GALE INTERNACIONAL INVEST / RTM (404),Beja,1.0,45.53,64.06
64,405,LACTACORES,SALVESEN LOGISTICA PORTUGAL / Lactacores (405),Lisboa,620.0,0.00,725.00
65,405,LACTACORES,"MAKRO CASH & CARRY PORTUGAL, SA / Lactacores (...",Coimbra,80.0,1411.63,1300.22
66,405,LACTACORES,TRANP.FERNANDO SIMÕES MONTEIRO / Alpro Portuga...,Coimbra,80.0,1411.63,801.82
67,405,LACTACORES,AMARAL & FILHOS / Lactacores (405),Lisboa,70.0,1799.66,3291.29
68,405,LACTACORES,AUCHAN - SALVESEN - REFRIGERAD / Lactacores (405),NÃO MAPEADO,67.0,568.83,0.00
69,405,LACTACORES,"MAKRO CASH & CARRY PORTUGAL, SA / Lactacores (...",Porto,29.0,449.43,634.16
70,405,LACTACORES,AMARAL & FILHOS / Lactacores (405),Setúbal,25.0,842.95,1331.97
71,405,LACTACORES,SOGENAVE SOC. GER.AB.NAV.IND.HOT.SA / Lactacor...,Lisboa,20.0,537.71,323.10
72,405,LACTACORES,NaN,Porto,20.0,260.16,458.02
73,405,LACTACORES,"MAKRO CASH & CARRY PORTUGAL, SA / Lactacores (...",Lisboa,18.0,484.43,796.93
74,405,LACTACORES,,Porto,16.0,342.78,384.98
75,405,LACTACORES,AMARAL & FILHOS / Lactacores (405),Santarém,11.0,409.35,484.62
76,405,LACTACORES,"ARCOL - A.ROD.CO.LOP.BEB.E ALIME.,SA / Lactaco...",Lisboa,11.0,298.11,362.62
77,405,LACTACORES,AMARAL & FILHOS / Lactacores (405),Leiria,9.0,254.23,322.55
78,405,LACTACORES,A. RIBEIRO DA SILVA E RIBEIRO / Lactacores (405),Porto,6.0,129.15,249.18
79,405,LACTACORES,"A.S. SIMÕES, LDA / Lactacores (405)",Lisboa,5.0,137.58,154.36
80,405,LACTACORES,LACTAÇORES (REFRIGERADO) / Lactacores (405),Lisboa,4.0,33.96,177.26
81,405,LACTACORES,LACTAÇORES (SECO) / Lactacores (405),Lisboa,4.0,0.00,97.54
82,405,LACTACORES,"J.V.LOBATO, LDA / Lactacores (405)",Lisboa,2.0,45.52,135.18
83,405,LACTACORES,"MAKRO CASH & CARRY PORTUGAL, SA / Lactacores (...",Faro,2.0,27.42,43.34
84,405,LACTACORES,YOÇOR - GARCEZ & SANTOS LDA / Lactacores (405),Lisboa,2.0,42.71,279.84
85,405,LACTACORES,NaN,Faro,2.0,27.42,47.20
86,405,LACTACORES,MODELO CONTINENTE HIPERMERCADOS / Lactacores (...,Santarém,1.0,18.03,112.04
87,405,LACTACORES,PINGO DOCE DIST.ALIM.SA / Lactacores (405),Porto,1.0,24.36,107.01
88,407,NUVIFRUITS,SALVESEN LOGISTICA PORTUGAL / Nuvifruits (407),Lisboa,525.0,0.00,515.93
89,407,NUVIFRUITS,CATERINGPOR CATERING DE PORTUG / Nuvifruits (407),Lisboa,71.0,2149.28,3062.93
90,407,NUVIFRUITS,MODIS AZAMBUJA / Nuvifruits (407),Lisboa,51.0,971.55,722.16
91,407,NUVIFRUITS,"AUCHAN RETAIL PORTUGAL II, S.A / Nuvifruits (407)",Lisboa,23.0,438.15,0.00
92,407,NUVIFRUITS,MODIS MAIA / Nuvifruits (407),Porto,22.0,687.94,318.64
93,407,NUVIFRUITS,GLOVOAPP PORTUGAL UNIPESSOAL L / Nuvifruits (407),Lisboa,21.0,385.17,1045.01
94,407,NUVIFRUITS,"MODELO CONTINENTE,HIP.SA-MAIA/ / Rana España (...",Porto,21.0,328.36,661.50
95,407,NUVIFRUITS,"SOGENAVE, SA / Nuvifruits (407)",Lisboa,18.0,374.23,248.77
96,407,NUVIFRUITS,NaN,Porto,17.0,265.81,140.48
97,407,NUVIFRUITS,NUVIFRUITS / Nuvifruits (407),Lisboa,16.0,214.64,112.00
98,407,NUVIFRUITS,MODIS AZAMBUJA AMBIENTE / Nuvifruits (407),Lisboa,15.0,285.75,38.78
99,407,NUVIFRUITS,EL CORTE ARMAZEN ALCOCHETE / Nuvifruits (407),Setúbal,11.0,242.33,66.72
100,407,NUVIFRUITS,MODIS MAIA AMBIENTE / Nuvifruits (407),Porto,11.0,343.97,14.87
101,407,NUVIFRUITS,AUCHAN VENDA DO PINHEIRO / Nuvifruits (407),Lisboa,8.0,125.16,277.23
102,407,NUVIFRUITS,NUVIFRUIT / Nuvifruits (407),Lisboa,7.0,149.90,269.98
103,407,NUVIFRUITS,,Porto,6.0,93.83,41.82
104,407,NUVIFRUITS,ALDI RETAIL UNIPESSOAL LDA / Nuvifruits (407),Setúbal,6.0,132.18,40.63
105,407,NUVIFRUITS,COLMEIA DO MESTRE- QTA DO ANJO / Nuvifruits (407),Setúbal,4.0,93.32,94.47
106,407,NUVIFRUITS,INSCO / Nuvifruits (407),Lisboa,4.0,74.75,18.01
107,407,NUVIFRUITS,LIDL SANTO TIRSO / Nuvifruits (407),NÃO MAPEADO,4.0,125.08,41.12
108,407,NUVIFRUITS,LIDL TORRES NOVAS / Nuvifruits (407),Santarém,3.0,73.89,15.90
109,407,NUVIFRUITS,APOLÓNIA FARO / Nuvifruits (407),Faro,2.0,10.10,3.90
110,407,NUVIFRUITS,D.J.V.-COM. DE PROD. ALIMENTAR / Nuvifruits (407),Lisboa,2.0,43.94,44.78
111,407,NUVIFRUITS,"RESTFLIGHT-SERV. CATERING,UNIP / Nuvifruits (407)",Lisboa,2.0,35.76,19.75
112,407,NUVIFRUITS,"SOGENAVE, SA / Nuvifruits (407)",Porto,2.0,31.28,19.57
113,407,NUVIFRUITS,NaN,Faro,2.0,10.10,3.04
114,407,NUVIFRUITS,,Faro,1.0,10.10,2.31
115,407,NUVIFRUITS,"COMBINAÇAO PURA, UNIPESSOAL LD / Nuvifruits (407)",Lisboa,1.0,21.11,27.39
116,407,NUVIFRUITS,FRUSEL-FRUTOS SELECCIONADOS LD / Nuvifruits (407),Santarém,1.0,25.93,38.62
117,407,NUVIFRUITS,"JOSE FRANCO SILVESTRE, UNIP, L / Nuvifruits (407)",Lisboa,1.0,21.11,30.28
118,407,NUVIFRUITS,"NUVIFRUITS, SA - NC / Nuvifruits (407)",Lisboa,1.0,0.00,0.96
119,407,NUVIFRUITS,PLUSMATIC-MAQ DE VENDA AUTOMAT / Nuvifruits (407),Lisboa,1.0,17.88,7.63
120,407,NUVIFRUITS,"QUINTA ENCANTADA UNIPESSOAL, L / Nuvifruits (407)",Lisboa,1.0,17.88,13.83
121,407,NUVIFRUITS,"RESTFLIGHT-SERV. CATERING,UNIP / Nuvifruits (407)",Faro,1.0,10.10,2.28
122,415,LOUROFOODS,SALVESEN LOGISTICA PORTUGAL / Lourofoods (415),Lisboa,497.0,8383.65,7686.00
123,415,LOUROFOODS,ARMAZEM NOATUM LOGISTICS - MÓD / Lourofoods (415),Lisboa,99.0,1504.87,1045.20
124,415,LOUROFOODS,CENTROS DISTRIBUIC.AZAMBUJA / Lourofoods (415),Lisboa,93.0,867.30,670.87
125,415,LOUROFOODS,"AUCHAN RETAIL PORTUGAL II, S.A / Lourofoods (415)",Lisboa,43.0,509.58,420.94
126,415,LOUROFOODS,"AUCHAN RETAIL PORTUGAL II, S.A / Lourofoods (415)",Santarém,29.0,399.23,502.67
127,415,LOUROFOODS,PD SILVES / Lourofoods (415),Faro,29.0,925.05,774.97
128,415,LOUROFOODS,DREAM PLUS - SINTRA / Lourofoods (415),Lisboa,17.0,366.96,636.67
129,415,LOUROFOODS,PAULO LIMA-VIZELA / Lourofoods (415),Braga,17.0,468.97,390.69
130,415,LOUROFOODS,NaN,Faro,16.0,409.32,351.29
131,415,LOUROFOODS,"BOLAMA SUPERMERCADOS, LDA / Lourofoods (415)",Braga,13.0,369.86,431.54
132,415,LOUROFOODS,ALEXANDRINO PEREIRA & SILVA PE / Lourofoods (415),Braga,7.0,172.32,276.35
133,415,LOUROFOODS,CATARPLUS(RECHEIO MASTERCHEF) / Lourofoods (415),Lisboa,7.0,163.13,208.43
134,415,LOUROFOODS,D.J.V COMERCIO PROD. ALIMEN / Lourofoods (415),Lisboa,7.0,163.13,284.97
135,415,LOUROFOODS,COZINHA CENTRAL DE ODIVELAS II / Lourofoods (415),Lisboa,6.0,139.91,188.45
136,415,LOUROFOODS,JOSE VILHENA - MEAT TRADING LD / Lourofoods (415),Lisboa,6.0,135.90,173.64
137,415,LOUROFOODS,PISABELL / Lourofoods (415),Lisboa,6.0,139.32,91.41
138,415,LOUROFOODS,SOC PRODUTOS ALIMENTARES JOFER / Lourofoods (415),Lisboa,6.0,139.91,310.98
139,415,LOUROFOODS,SOGENAVE TOJAL / Lourofoods (415),Lisboa,6.0,139.32,116.35
140,415,LOUROFOODS,ARCOL GUIMARÃES / Lourofoods (415),Braga,5.0,117.84,251.53
141,415,LOUROFOODS,BELAVE LEIRIA / Lourofoods (415),Leiria,5.0,65.84,331.28
142,415,LOUROFOODS,"BENTO & NASCIMENTO, LDA / Lourofoods (415)",Aveiro,5.0,147.30,305.41
143,415,LOUROFOODS,COME OVO - AMORA / Lourofoods (415),Setúbal,5.0,161.32,267.54
144,415,LOUROFOODS,GUERREIRO E PRATA - FARO / Lourofoods TLD (408),Faro,5.0,128.13,113.69
145,415,LOUROFOODS,JOPAMA - COVILHA / Lourofoods (415),Castelo Branco,5.0,269.20,170.81
146,415,LOUROFOODS,ZOLVE MOLDIVAS - LOGIFRIO / Lourofoods (415),Porto,5.0,121.25,163.70
147,415,LOUROFOODS,,Faro,4.0,103.20,103.53
148,415,LOUROFOODS,BENTOVO UNIPESSOAL LDA / Lourofoods (415),Lisboa,4.0,94.06,223.46
149,415,LOUROFOODS,COVIRAN S COOP AND SUCURSAL EM / Lourofoods (415),Lisboa,4.0,95.24,154.96
150,415,LOUROFOODS,ESTRELA DA SERRA SOCIEDADE COM / Lourofoods (415),Lisboa,4.0,71.43,414.59
151,415,LOUROFOODS,GEL SILVES / Lourofoods (415),Faro,4.0,101.46,75.96
152,415,LOUROFOODS,RAMOS E PEREIRA LDA / Lourofoods (415),Santarém,4.0,128.40,228.68
153,415,LOUROFOODS,"RECHEIO, S.A. - RECHEIO EXP. 2 / Lourofoods (415)",Lisboa,4.0,94.06,133.74
154,415,LOUROFOODS,TRANP.FERNANDO SIMÕES MONTEIRO / Alpro Portuga...,Coimbra,4.0,58.36,46.29
155,415,LOUROFOODS,ALCAFER COM. IND. PROD. ALIM / Lourofoods (415),Santarém,3.0,96.30,83.80
156,415,LOUROFOODS,CONGELBRAGA - PRODUTOS ALIMENT / Lourofoods (415),Braga,3.0,88.38,110.46
157,415,LOUROFOODS,CONSUMINTENSO - BRAGA / Lourofoods (415),Braga,3.0,86.90,146.49
158,415,LOUROFOODS,COVIRAN S COOP AND SUCURSAL EM / Lourofoods (415),Faro,3.0,77.40,86.26
159,415,LOUROFOODS,DISTINTADELÍCIA - PRODUTOS ALI / Lourofoods (415),Faro,3.0,76.53,62.46
160,415,LOUROFOODS,DUNANY FOODS S.A. / Lourofoods (415),Santarém,3.0,96.30,123.63
161,415,LOUROFOODS,"FERNANDO ANES UNIPESSOAL, LDA. / Lourofoods (415)",Vila Real,3.0,66.62,111.62
162,415,LOUROFOODS,JM CASTRO / Lourofoods (415),Setúbal,3.0,98.76,111.11
163,415,LOUROFOODS,JVLOBATO VIALONGA / Lourofoods (415),Lisboa,3.0,46.44,167.02
164,415,LOUROFOODS,MOS - ARMAZEM EXP. PORTWAY HAN / Lourofoods (415),Lisboa,3.0,69.66,104.44
165,415,LOUROFOODS,NATUREZA CONG. - MENDALVE / Lourofoods (415),Lisboa,3.0,70.25,110.36
166,415,LOUROFOODS,"PEREIRA & RIBEIRO, LDA / Lourofoods (415)",Braga,3.0,86.16,97.92
167,415,LOUROFOODS,PEREIRA PINTO-PAÇOS DE FERREIR / Lourofoods (415),Porto,3.0,74.58,65.55
168,415,LOUROFOODS,RECEITAS DA AVO - ARRUDA VINHO / Lourofoods (415),Lisboa,3.0,47.62,125.14
169,415,LOUROFOODS,REGIONAL MERCADORIAS ALCANENA / Lourofoods (415),Santarém,3.0,57.66,24.24
170,415,LOUROFOODS,"A.S.SIMOES PRODUTOS ALIM, LDA / Lourofoods (415)",Lisboa,2.0,47.62,52.95
171,415,LOUROFOODS,APRECIARUMOS / Lourofoods (415),Lisboa,2.0,47.62,60.45
172,415,LOUROFOODS,"CARDO SRA DO MONTE,LDA-ARRABAL / Lourofoods (415)",Leiria,2.0,32.92,134.64
173,415,LOUROFOODS,CASCARNES - COMÉRCIO E IND STR / Lourofoods (415),Lisboa,2.0,46.44,65.10
174,415,LOUROFOODS,COSTA & PIMPÃO - PRODUTOS LÁCT / Lourofoods (415),Santarém,2.0,64.20,137.98
175,415,LOUROFOODS,"M. CUNHA, S.A. - FELGUEIRAS / Lourofoods (415)",Porto,2.0,51.00,120.77
176,415,LOUROFOODS,NORTENHO - T.VEDRAS / Lourofoods (415),Lisboa,2.0,46.44,66.10
177,415,LOUROFOODS,O AZEITEIRO - ANTONIO CARVALHO / Lourofoods (415),Setúbal,2.0,64.20,116.19
178,415,LOUROFOODS,"RECHEIO MASTERCHEF, LDA / Lourofoods (415)",Faro,2.0,51.60,38.63
179,415,LOUROFOODS,SEGREDOS IBERICOS - AVEIRO / Lourofoods (415),Aveiro,2.0,58.92,127.15
180,415,LOUROFOODS,SUPER 2004 SINTRA / Lourofoods (415),Lisboa,2.0,47.62,91.81
181,415,LOUROFOODS,VANIBRU - COMÉRCIO DE PRODUTOS / Lourofoods (415),Braga,2.0,57.44,86.29
182,415,LOUROFOODS,VIPANI - MIRANDELA / Lourofoods (415),Bragança,2.0,72.26,82.54
183,415,LOUROFOODS,ALVARO & MAGDA LDA / Lourofoods (415),Lisboa,1.0,23.81,52.92
184,415,LOUROFOODS,ANCORA PRATEADA COM. PROD. ALI / Lourofoods (415),Évora,1.0,62.94,56.31
185,415,LOUROFOODS,AVICUIMA - UNIDADE DE PRODUÇÃO / Lourofoods (415),Bragança,1.0,36.13,25.71
186,415,LOUROFOODS,AVILOULÉ - COMÉRCIO DE PRODUTO / Lourofoods (415),Faro,1.0,25.80,22.42
187,415,LOUROFOODS,BARSTOCK LISBOA / Lourofoods (415),Lisboa,1.0,23.81,41.82
188,415,LOUROFOODS,BESAVES LOULE / Lourofoods (415),Faro,1.0,25.80,20.55
189,415,LOUROFOODS,BIDFOOD / Lourofoods (415),Lisboa,1.0,23.81,35.52
190,415,LOUROFOODS,BLOCO FRIO - PRODUTOS ALIMENTA / Lourofoods (415),Porto,1.0,25.50,55.96
191,415,LOUROFOODS,DISTRIBUI - COM. DIST. PRODUTO / Lourofoods (415),Bragança,1.0,36.13,56.67
192,415,LOUROFOODS,EUROBAR-SOC. ABAST.DE PRODUTOS / Lourofoods (415),Lisboa,1.0,23.81,46.84
193,415,LOUROFOODS,EUROPFOODS - ALGARVE / Lourofoods (415),NÃO MAPEADO,1.0,25.80,25.31
194,415,LOUROFOODS,FA E MIGUEL - COVILHA / Lourofoods (415),Castelo Branco,1.0,56.60,14.01
195,415,LOUROFOODS,HELDER R S MARQUES LDA / Lourofoods (415),NÃO MAPEADO,1.0,20.95,20.11
196,415,LOUROFOODS,JOAO EVARISTO - VIANA CASTELO / Lourofoods (415),Viana do Castelo,1.0,30.64,24.72
197,415,LOUROFOODS,LARDOMUS SOC ALIMENTOS LDA / Lourofoods (415),Braga,1.0,29.46,58.63
198,415,LOUROFOODS,LUCSTOCKFOOD / Lourofoods (415),Santarém,1.0,32.92,80.18
199,415,LOUROFOODS,MANUEL RODRIGO DOS SANTOS TELO / Lourofoods (415),Setúbal,1.0,32.92,58.10
200,415,LOUROFOODS,MEAT HERITAGE LDA / Lourofoods (415),Leiria,1.0,32.92,46.64
201,415,LOUROFOODS,MEIGAL ALIMENTAÇÃO - FRIELAS / Lourofoods (415),Lisboa,1.0,23.81,55.28
202,415,LOUROFOODS,PANIOVO - PRODUTOS ALIMENTARES / Lourofoods (415),Bragança,1.0,36.13,43.03
203,415,LOUROFOODS,QUINTA DAS ARCAS - VALONGO / Lourofoods (415),NÃO MAPEADO,1.0,25.50,55.96
204,415,LOUROFOODS,REIS E PACHECO / Lourofoods (415),Porto,1.0,25.50,55.96
205,415,LOUROFOODS,RUMIEMA COMÉRCIO E DISTRIBUIÇÃO DE PRODUTOS ...,Braga,1.0,29.46,41.07
206,415,LOUROFOODS,SANER SOC ALIMENTAR DO NORTE S / Lourofoods (415),Porto,1.0,25.50,54.68
207,415,LOUROFOODS,SIFORTE LEIRIA / Lourofoods (415),Leiria,1.0,16.46,31.13
208,415,LOUROFOODS,SPEEDYFOOD SERVICE LDA / Lourofoods (415),Aveiro,1.0,20.95,11.09
209,415,LOUROFOODS,"VAGALIMENTAR, DISTRIBUÇÃO PROD / Lourofoods (415)",Aveiro,1.0,30.64,59.42
210,551,UPFIELD,SALVESEN LOGISTICA GETAFE / Upfield (551),NÃO MAPEADO,726.0,13200.00,12150.00
211,680,XPO SUMOLCOMPAL,SALVESEN LOGISTICA PORTUGAL / Xpo Sumolcompal ...,Lisboa,163.0,3531.89,6317.39
212,680,XPO SUMOLCOMPAL,NaN,Porto,34.0,406.50,641.33
213,680,XPO SUMOLCOMPAL,TRANP.FERNANDO SIMÕES MONTEIRO / Alpro Portuga...,Coimbra,25.0,224.98,138.12
214,680,XPO SUMOLCOMPAL,NaN,Faro,21.0,264.97,181.62
215,680,XPO SUMOLCOMPAL,ALMODOVAR A.S. - ARS - REST / Xpo Sumolcompal ...,Beja,12.0,108.21,72.41
216,680,XPO SUMOLCOMPAL,,Porto,11.0,140.91,214.94
217,680,XPO SUMOLCOMPAL,AUCHAN GONDOMAR / Xpo Sumolcompal (680),Porto,9.0,114.02,273.40
218,680,XPO SUMOLCOMPAL,VG ELVAS / Xpo Sumolcompal (680),Portalegre,9.0,336.04,198.44
219,680,XPO SUMOLCOMPAL,,Faro,8.0,94.48,63.33
220,680,XPO SUMOLCOMPAL,A2 ALMODOVAR (LIS/ALG) ES63375 / Xpo Sumolcomp...,Beja,8.0,108.95,75.96
221,680,XPO SUMOLCOMPAL,AUCHAN ALFRAGIDE / Xpo Sumolcompal (680),Lisboa,8.0,122.11,211.20
222,680,XPO SUMOLCOMPAL,AUCHAN CASTELO BRANCO / Xpo Sumolcompal (680),Castelo Branco,8.0,459.87,197.97
223,680,XPO SUMOLCOMPAL,AUCHAN FARO / Xpo Sumolcompal (680),Faro,8.0,131.45,101.63
224,680,XPO SUMOLCOMPAL,AUCHAN MAIA / Xpo Sumolcompal (680),Porto,8.0,103.11,190.91
225,680,XPO SUMOLCOMPAL,AUCHAN SETUBAL / Xpo Sumolcompal (680),Setúbal,8.0,200.25,317.93
226,680,XPO SUMOLCOMPAL,IKEA MATOSINHOS / TIBA (788),Porto,8.0,99.79,268.32
227,680,XPO SUMOLCOMPAL,AUCHAN FIGUEIRA FOZ / Xpo Sumolcompal (680),Coimbra,7.0,48.96,154.19
228,680,XPO SUMOLCOMPAL,VG ALTER DO CHÃO / Xpo Sumolcompal (680),Portalegre,7.0,346.57,249.84
229,680,XPO SUMOLCOMPAL,AUCHAN VISEU / Xpo Sumolcompal (680),Viseu,6.0,88.16,111.96
230,680,XPO SUMOLCOMPAL,A.S VILA VELHA RODAO I (11548) / Xpo Sumolcomp...,Castelo Branco,5.0,280.82,160.23
231,680,XPO SUMOLCOMPAL,AUCHAN GAIA / Xpo Sumolcompal (680),Porto,5.0,38.59,74.34
232,680,XPO SUMOLCOMPAL,AUCHAN PAÇO DE ARCOS / Xpo Sumolcompal (680),Lisboa,5.0,51.57,70.03
233,680,XPO SUMOLCOMPAL,AUCHAN SINTRA / Xpo Sumolcompal (680),Lisboa,5.0,44.56,45.58
234,680,XPO SUMOLCOMPAL,AUCHAN VILA DO CONDE / Xpo Sumolcompal (680),Porto,5.0,87.78,176.95
235,680,XPO SUMOLCOMPAL,AUCHAN ALVERCA / Xpo Sumolcompal (680),Lisboa,4.0,63.51,109.17
236,680,XPO SUMOLCOMPAL,AUCHAN AVEIRO / Xpo Sumolcompal (680),Aveiro,4.0,24.88,94.39
237,680,XPO SUMOLCOMPAL,AUCHAN CALDAS DA RAINHA / Xpo Sumolcompal (680),Leiria,4.0,87.49,110.72

Excel exportado: C:\Users\LISARR\Documents\Destinos_Clientes_Distritos_Agosto_2026.xlsx

In [ ]:
# ==========================
# Entregas Machado e Brites
# Agosto 2026
# ==========================

ANO = 2026
MES = 8

df_entregas = CON[ANO].execute(
    f"""
    SELECT DISTINCT
        FENTREGA,
        CODEUT

    FROM inform_27_{ANO}

    WHERE Gestion = ?
      AND SUBSTR(TRIM(CAST(FENTREGA AS VARCHAR)), 1, 6) = ?
      AND TRANSPORTISTA ILIKE '%MACHADO%'
      AND TRANSPORTISTA ILIKE '%BRITES%'

    ORDER BY FENTREGA, CODEUT
    """,
    [GESTAO, f"{ANO}{MES:02d}"]
).df()

display(df_entregas)

print(f"Total de combinações distintas de data e CODEUT: {len(df_entregas)}")

    FENTREGA   CODEUT
0   20260806  3514019
1   20260807  3514775
2   20260810  3515749
3   20260811  3517262
4   20260811  3518568
5   20260812  3518143
6   20260812  3519571
7   20260813  3519221
8   20260814  3520565
9   20260817  3521477
10  20260818  3522544
11  20260820  3524015
12  20260821  3524916
13  20260824  3525912
14  20260825  3527022

Total de combinações distintas de data e CODEUT: 15

In [ ]:
# ==========================================
# CUSTOS, INGRESSOS E PALETES POR CLIENTE
# Agosto e Setembro de 2026
# ==========================================

ANO = 2026

CLIENTES = [
    '391', '404', '405', '407', '415',
    '551', '680', '757', '311'
]

df_clientes = CON[ANO].execute(
    f"""
    SELECT
        SUBSTR(TRIM(CAST(FENTREGA AS VARCHAR)), 1, 6) AS MES,

        LPAD(TRIM(CAST(CODACT AS VARCHAR)), 3, '0') AS CODACT,

        ACTIVIDAD,

        ROUND(SUM(
            TRY_CAST(REPLACE(CAST(INGRESODT AS VARCHAR), ',', '.') AS DOUBLE)
        ), 2) AS INGRESODT,

        ROUND(SUM(
            TRY_CAST(REPLACE(CAST(COSTEDT AS VARCHAR), ',', '.') AS DOUBLE)
        ), 2) AS COSTEDT,

        ROUND(SUM(
            TRY_CAST(REPLACE(CAST(PALETS AS VARCHAR), ',', '.') AS DOUBLE)
        ), 2) AS PALETS

    FROM inform_27_{ANO}

    WHERE Gestion = ?

      AND SUBSTR(TRIM(CAST(FENTREGA AS VARCHAR)), 1, 6)
          IN ('202608', '202609')

      AND LPAD(TRIM(CAST(CODACT AS VARCHAR)), 3, '0')
          IN ({','.join(['?'] * len(CLIENTES))})

    GROUP BY 1, 2, 3

    ORDER BY CODACT, MES
    """,
    [GESTAO, *CLIENTES]
).df()

display(df_clientes)